### ISSUE TITLE
app::version() seems to use deprecated FL_VERSION

### ISSUE THREAD

**Issue by mark-summerfield** [fltk-rs/fltk-rs#1005]
`app::version()` seems to use deprecated `FL_VERSION` (see 1.3 or 1.4 docs https://www.fltk.org/doc-1.4/enumerations.html )

It would be nice to have `app::version_str()` that returned, e.g., "1.4.0" or whatever the underlying FLTK version is.

PS Thank you for creating this binding, I'm just starting out with it but so far it works great on Linux and Windows.

**Comment by MoAlyousef** [comment]
Thanks for pointing out the deprecation. I've added a new function app::version_str() based on the FL_API_VERSION value.
