### ISSUE TITLE
Implement `WidgetExt` on custom widgets

### ISSUE THREAD

**Issue by Natoandro** [fltk-rs/fltk-rs#1011]
**Is your feature request related to a problem? Please describe.**
I cannot use my custom widget as a template parameter to a generic struct that requires a `WidgetExt`.

```rs
use fltk::button::Button;
use fltk::prelude::*;
use fltk::widget_extends;

#[derive(Default)]
struct MyCustomButton {
    button: Button,
}

widget_extends!(MyCustomButton, Button, button);

struct WidgetWrapper<W: WidgetExt> {
    wrapped_widget: W,
}

fn wrap<W: WidgetExt>(widget: W) -> WidgetWrapper<W> {
    WidgetWrapper {
        wrapped_widget: widget,
    }
}

fn main() {
    wrap(Button::default());
    wrap(MyCustomButton::default()); // this does not work
}
```
**Describe the solution you'd like**
`widget_extends` could implement `WidgetExt` and (optionally `GroupExt`) on the custom widget, delegating method calls to the `base`.

**Comment by MoAlyousef** [comment]
I plan to expose more trait macros to the user. The currently exposed macros handle widgets which have an underlying widget pointer. I plan to add macros similar to wodget_extends which basically implement the trait macro via the passed widget. 
Adding that functionality to widget_extends is difficult, since finding out what traits a widget implements is difficult.

**Comment by MoAlyousef** [comment]
I'm running into issues creating such a macro for WidgetExt, since it requires changing the closure signature in set_callback to accomodate for the custom widget, and this breaks the trait. Another problem with macros is that they don't accommodate generic types. 

For the time being, you can still benefit from the Deref impl:
```rust
use fltk::button::Button;
use fltk::prelude::*;
use fltk::widget_extends;

#[derive(Default)]
struct MyCustomButton {
    button: Button,
}

widget_extends!(MyCustomButton, Button, button);

struct WidgetWrapper<'a, W: WidgetExt> {
    wrapped_widget: &'a W,
}

fn wrap<'a, W: WidgetExt>(widget: &'a W) -> WidgetWrapper<'a, W> {
    WidgetWrapper {
        wrapped_widget: widget,
    }
}

fn main() {
    wrap(&Button::default());
    wrap(&*MyCustomButton::default()); 
}
```

**Comment by Natoandro** [comment]
Thanks, but I intend to implement additionnal methods on `WidgetWrapper<MyCustomButton>`...

We could require that the custom widget implements the `Clone` trait, like all the other widgets. In that case `set_callback` could be implemented:

```rs
impl WidgetExt for $widget
where $widget: Clone
{
    // ...
    fn set_callback<F: FnMut(&mut Self) + 'static>(&mut self, cb: F)
         where Self: Sized
    {
        let mut widget = self.clone();
        self.$member.set_callback(move |_| {
            cb(&mut widget);
        });
    }
    // ...
}
```

**Comment by MoAlyousef** [comment]
I've used your suggestion, and have added several trait macros (for WidgetExt, GroupExt, and WidgetBase). The widget base macro probably doesn't work as expected. You can try things out:
```rust
use fltk::button::Button;
use fltk::prelude::*;
use fltk::enums::{self, *};
use fltk::app;
use fltk::group;
use fltk::macros::widget::*;


#[derive(Clone, Default)]
struct MyCustomButton {
    button: Button,
}

impl_widget_ext_via!(MyCustomButton, button);
impl_widget_base_via!(MyCustomButton, Button, button);

struct WidgetWrapper<W: WidgetExt> {
    wrapped_widget: W,
}

fn wrap<W: WidgetExt>(widget: W) -> WidgetWrapper<W> {
    WidgetWrapper {
        wrapped_widget: widget,
    }
}

fn main() {
    wrap(Button::default());
    wrap(MyCustomButton::default());
}
```

**Comment by Natoandro** [comment]
The definition of `impl_widget_ext_via` refers to fltk modules as `crate::<mod>` which causes the compiler to search for the definitions in my crate when the macro is expanded.
[macros/widget.rs:1103](https://github.com/fltk-rs/fltk-rs/blob/015c9b59982338a24861686cd3c111713f5e4882/fltk/src/macros/widget.rs#L1103)
[macros/widget.rs:1268](https://github.com/fltk-rs/fltk-rs/blob/015c9b59982338a24861686cd3c111713f5e4882/fltk/src/macros/widget.rs#L1268)
[macros/widget.rs:1366](https://github.com/fltk-rs/fltk-rs/blob/015c9b59982338a24861686cd3c111713f5e4882/fltk/src/macros/widget.rs#L1366)
[macros/widget.rs:1454](https://github.com/fltk-rs/fltk-rs/blob/015c9b59982338a24861686cd3c111713f5e4882/fltk/src/macros/widget.rs#L1454)
[macros/group.rs:306](https://github.com/fltk-rs/fltk-rs/blob/015c9b59982338a24861686cd3c111713f5e4882/fltk/src/macros/group.rs#L306)

The macro also uses `fltk_sys::widget::Fl_Widget` which will require the user to add a dependency to `fltk_sys`.
The `fltk` crate would need to expose `fltk_sys::widget::Fl_Widget`.
[macros/widget.rs:1219](https://github.com/fltk-rs/fltk-rs/blob/015c9b59982338a24861686cd3c111713f5e4882/fltk/src/macros/widget.rs#L1219)
[macros/group.rs:1536](https://github.com/fltk-rs/fltk-rs/blob/015c9b59982338a24861686cd3c111713f5e4882/fltk/src/macros/widget.rs#L1536)

**Comment by MoAlyousef** [comment]
The changes are in master and haven’t been published yet.

**Comment by LaBatata101** [comment]
Do you have a date planned for publishing the changes?

**Comment by MoAlyousef** [comment]
Around 5 days. It’s usually a week between releases.
