### ISSUE TITLE
It isn't possible to detect function key presses, e.g., F1

### ISSUE THREAD

**Issue by mark-summerfield** [fltk-rs/fltk-rs#1017]
I want to be able to detect an F1 key press e.g., to pop up a help window.
Apparently in C++/FLTK the solution is to do Fl_F + 1; see
https://groups.google.com/g/fltkgeneral/c/gWd9z4H5M7M
but you can't convert enums to ints in Rust.
Could you add these (F1 to F12) to the Key enum please?
https://docs.rs/fltk/1.2.18/src/fltk/enums.rs.html#730-814

**Comment by MoAlyousef** [comment]
I have added Key::F1 thru to Key::F12. Also a const method Key::fn_key(n):
```rust
    win.handle(|w, ev| match ev {
        Event::KeyUp => match app::event_key() {
            Key::F2 => {
                dbg!("F2");
                true
            }
            _ => false,
        },
        _ => false,
    });
```

Using fn_key():
```rust
    const F12: Key = Key::fn_key(12); // inlined
    win.handle(|w, ev| match ev {
        Event::KeyUp => match app::event_key() {
            F12 => {
                dbg!("F12");
                true
            }
            _ => false,
        },
        _ => false,
    });
```
You can acquire the integral value of the key by using the .bits() method. `Key::F1.bits()` etc.

**Comment by mark-summerfield** [comment]
Thank you! I just added F1 handling and it works great:-)
And thanks for the tip about `.bits()`.
