### ISSUE TITLE
frame::Frame::set_label() doesn't clear the existing text

### ISSUE THREAD

**Issue by mark-summerfield** [fltk-rs/fltk-rs#1018]
This code works fine, clearning the text in the statusbar frame after 2 seconds:
```rust
statusbar.set_frame(fltk::enums::FrameType::FlatBox);
fltk::app::add_timeout(2.0, {
    let mut statusbar = statusbar.clone();
    move || {
	statusbar.set_label("");
    }
});
```
But this code doesn't work:
```rust
statusbar.set_frame(fltk::enums::FrameType::EngravedFrame);
fltk::app::add_timeout(2.0, {
    let mut statusbar = statusbar.clone();
    move || {
	statusbar.set_label("");
	statusbar.redraw();
    }
});
```
with or without the redraw.

Surely this is a bug?

**Comment by MoAlyousef** [comment]
It's an FLTK behaviour where FrameTypes without a solid background actually would require a redraw of their parent (if the parent has a solid background) or the application.

EngravedFrame has no solid background, so you can replace statusbar.redraw() with fltk::app::redraw().

**Comment by mark-summerfield** [comment]
Thank you that worked great.
