### ISSUE TITLE
[BUG] Possible bug with theme/draw functions

### ISSUE THREAD

**Issue by mark-summerfield** [fltk-rs/fltk-rs#1023]
When I run my program with the draw functions in `board.rs` commented out the buttons and status frames show up correctly as per screenshot "no-draw.png".
However if I uncomment the draw functions the status frames show up incorrectly as per screenshot "draw-before-redraw.png". And then after the timeout forces a redraw the whole thing looks much worse (all pixelated) as per screenshot "draw-after-redraw.png".
Is this a bug in my code or in fltk-rs or in fltk? I don't know. I did all this under Ubuntu 20.04 LTS Linux. Full source code and screenshots referred to are attached:
[gravitate.tar.gz](https://github.com/fltk-rs/fltk-rs/files/7653098/gravitate.tar.gz)

**Comment by mark-summerfield** [comment]
Similar problems occur on Windows 7. See corresponding screenshot
![win-draw-after-draw](https://user-images.githubusercontent.com/1773348/144692320-4d6a4327-b4a0-4a72-8c9b-4e3b36471f47.png)
![win-draw-before-draw](https://user-images.githubusercontent.com/1773348/144692321-e70b93f8-81a0-4962-aa5a-8fc37d0d1b79.png)
![win-no-draw](https://user-images.githubusercontent.com/1773348/144692322-4541df0b-7980-4243-acf7-2940e69bd7e7.png)
s.

**Comment by MoAlyousef** [comment]
Can you try adding `fltk::draw::set_line_style(fltk::draw::LineStyle::Solid, 0);` to the end of the draw method?

i.e.
```rust
board.widget.draw(move |widget| {
    // draw stuff
    fltk::draw::set_line_style(fltk::draw::LineStyle::Solid, 1);
}
```
It basically resets the line style.

**Comment by mark-summerfield** [comment]
Thank you. I added the line you said I needed and tested on both Linux and Windows and now everything works!
