### ISSUE TITLE
[BUG] Window title doesn't appear in the Alt-Tab list on Linux

### ISSUE THREAD

**Issue by mark-summerfield** [fltk-rs/fltk-rs#1024]
For my application's main window (of type `fltk::window::Window`) I create the window using `.with_label()` passing the application's name. This name appears in the main window's title bar on Linux (Ubuntu 20.04 LTS) and Windows (7) and in the task bar (on both), and in the Alt+Tab list on Windows but *not* in the Alt+Tab list on Linux. For Linux the Alt+Tab list shows the icon correctly, but instead of the window's label (title), it shows the text "FLTK". You can see this with the gravitate example I sent early this morning.

**Comment by MoAlyousef** [comment]
Does it make a difference if you use the `::new` constructor instead of the `::default` constructor to create the main window. If it doesn’t, you might wanna ask at the mailing list. Unfortunately I don’t have access to a linux machine at the moment (only windows and wsl).

**Comment by MoAlyousef** [comment]
Also this might be relevant:
https://stackoverflow.com/questions/63087842/give-a-qt-application-a-name-which-shows-up-in-alt-tab-window-switch-list

**Comment by MoAlyousef** [comment]
It seems gnome's alt-tab switcher queries XA_WM_CLASS to get a name. This is set by FLTK's xclass and default_xclass methods which aren't exposed in the bindings.
I'll add them in a bit then you can `cargo update` and set these to your app's name.

**Comment by MoAlyousef** [comment]
You can try to update now. 
```rust
let mut win = window::Window::default();
win.set_xclass("gravitate");
// Or
window::Window::set_default_xclass("gravitate");
```

**Comment by mark-summerfield** [comment]
Thank you. I tried both and both set the name for both the main window and for the modal about dialog as shown in the Alt+Tab list.

Incidentally, if you have the time and 20GB spare disk space you could install VirtualBox on Windows (free) and then install a Linux distro (also free). VirtualBox lets you share folders between both Windows and Linux so it is easy to have a common folder of examples and build and test on both. But no matter, I do all my development on Linux and then test on Windows, so naturally I'll let you know if I hit any issues.

PS Your bindings are the first time I've had any cross-platform success at all with FLTK. I found your wiki very helpful and also the 7 GUIs esp. the circles eg.

**Comment by MoAlyousef** [comment]
Thanks. That's great to hear.

Thanks for the tip regarding virtualbox. I actually used it before on my mac. I had issues with it and hyper-V on windows. I'll try it again.
