### ISSUE TITLE
Macros should make fewer assumptions about their environment

### ISSUE THREAD

**Issue by AshfordN** [fltk-rs/fltk-rs#1027]
I notice several macros, some of which were recently introduced, are making assumptions about the environment in which are used. For example, `impl_widget_ext_via!()` is written in a way that assumes `enums::Align` is already in scope (see [line 1104](https://github.com/fltk-rs/fltk-rs/blob/master/fltk/src/macros/widget.rs#L1104)) and there is a heavy use of `crate` instead of `$crate` (see [line 1220](https://github.com/fltk-rs/fltk-rs/blob/master/fltk/src/macros/widget.rs#L1220)) which causes problems when using the macro from library crates.
I'm thinking that all references should be written as flexible as possible - such as `$crate::enums::Align` and `$crate::app::WidgetPtr`. What are your thoughts on this? If you agree, I would be willing to open a PR.

**Comment by MoAlyousef** [comment]
I agree. There wasn’t a plan to expose these impl_* macros until recently, so they do require more cleanup which I haven’t had the chance to work on.

**Comment by AshfordN** [comment]
Fixed by #1028
