### ISSUE TITLE
Accept closure for `set_frame_type_cb`

### ISSUE THREAD

**Issue by KillTheMule** [fltk-rs/fltk-rs#1057]
**Is your feature request related to a problem? Please describe.**
I want to override the frame type for `Choice`, and I need to use `set_frame_type_cb` for this, as you showed me. I want to switch the colors for that frame, and the function signature just allows for the outer color to passed in by the color theme. I'm using code like this:

```rust
fn set_choice_border_color_green() {
  fn my_down_box(x: i32, y: i32, w: i32, h: i32, col: Color) {
    draw::draw_rect_fill(x, y, w, h, GREEN);
    draw::draw_rect_fill(x + 1, y + 1, w - 2, h - 2, col);
  }
  app::set_frame_type_cb(FrameType::DownBox, my_down_box, 0, 0, 0, 0);
}
```
which does the job, but I need a new function for each color. If I could pass a closure to `set_frame_type_cb`, I could make a function that accepts a color and sets the callback accordingly, not matter the color.

**Describe the solution you'd like**
Maybe the parameter `cb` of [`set_frame_type_cb`](https://docs.rs/fltk/latest/fltk/app/fn.set_frame_type_cb.html) could be a generic one that implements [`Fn`](https://doc.rust-lang.org/std/ops/trait.Fn.html).

**Describe alternatives you've considered**
I could kind of make a function for each color I want, but I'm already seeing a lot of repetition happening in my code which I could solve with this.

**Additional context**
I have absolutely no idea if that's actually feasible given the callback needs to be passed to C++ code. Just asking :)

**Comment by MoAlyousef** [comment]
Afraid it can't be done. This is a method of a static type initiated externally in C++ prior to app initialization, the Fl object. It's not possible to subclass it and add a `void *data` member to it which can hold external data (necessary for capturing closures).

The only way I can think of at the moment is by using some statics as well:
```rust
extern crate once_cell;

use once_cell::sync::OnceCell;
use fltk::{enums::*, prelude::*, *};

static CHOICE_BORDER_COLOR: OnceCell<Color> = OnceCell::new();

fn set_choice_border_color(color: Color) {
    CHOICE_BORDER_COLOR.set(color).unwrap();
    fn my_down_box(x: i32, y: i32, w: i32, h: i32, col: Color) {
        draw::draw_rect_fill(x, y, w, h, *CHOICE_BORDER_COLOR.get().unwrap());
        draw::draw_rect_fill(x + 1, y + 1, w - 2, h - 2, col);
    }
    app::set_frame_type_cb(FrameType::DownBox, my_down_box, 0, 0, 0, 0);
}

fn main() {
    let a = app::App::default();
    set_choice_border_color(Color::Green);
    let mut win = window::Window::default().with_size(400, 300);
    let mut choice = menu::Choice::new(160, 200, 80, 30, "Choice");
    choice.add_choice("rew|wer");
    win.end();
    win.show();
    a.run().unwrap();
}
```

**Comment by KillTheMule** [comment]
Yeah, I was afraid of that, thanks! But your solution does not look problematic really... although I'd personally be afraid that the synchronisation of `sync::OnceCell` isn't FFI-safe. I've found [this thread](https://users.rust-lang.org/t/how-can-threads-calling-ffi-code-in-rust-communicate-with-other-threads-or-modify-shared-state/36029/7) though which says it is, so I'm gonna go ahead with this. Thanks!

**Comment by KillTheMule** [comment]
Ok, I need to ask another question: I need to change the color during runtime, so `OnceCell` itself doesn't cut it. I can put a `Mutex` inside, so it works... but, same worry, is that safe to use here wrt FFI-safety?

**Comment by MoAlyousef** [comment]
I think it's safe. Color is a wrapper around u32, which is Send+Sync. You can use an AtomicU32 for example:
```rust
use fltk::{enums::*, prelude::*, *};
use std::sync::atomic::{AtomicU32, Ordering};

const RED: u32 = 0xff0000;

static CHOICE_BORDER_COLOR: AtomicU32 = AtomicU32::new(0);

fn set_choice_border_color(color: u32) {
    CHOICE_BORDER_COLOR.store(color, Ordering::Relaxed);
    fn my_down_box(x: i32, y: i32, w: i32, h: i32, col: Color) {
        draw::draw_rect_fill(x, y, w, h, Color::from_u32(CHOICE_BORDER_COLOR.load(Ordering::Relaxed) as _));
        draw::draw_rect_fill(x + 1, y + 1, w - 2, h - 2, col);
    }
    app::set_frame_type_cb(FrameType::DownBox, my_down_box, 0, 0, 0, 0);
}

fn main() {
    let a = app::App::default();
    set_choice_border_color(RED);
    let mut win = window::Window::default().with_size(400, 300);
    let mut choice = menu::Choice::new(160, 200, 80, 30, "Choice");
    choice.add_choice("rew|wer");
    win.end();
    win.show();

    a.run().unwrap();
}
```

**Comment by KillTheMule** [comment]
Ohhh that looks even better! Thanks a lot again!
