### ISSUE TITLE
Window and input widget lose focus after invoking a std::process::Command

### ISSUE THREAD

**Issue by wellitecho** [fltk-rs/fltk-rs#1068]
## Describe the bug
The application has a text input widget, and if the text satisfies certain pattern, the application will start a std::process::Command and send .prn file to a printer for printing. After printing, the text input widget will be cleared, and wait for next input, rinse and repeat.
The problem is, after the first time the app sends instruction to the printer(with the following code by using cmd), there is a flash(cannot see clearly what it is because it all happened in an instant, but I guess it's a cmd window), which makes the gui window not active, and the input widget loses focus, which means if I want to input again, I need to select the gui window again(or manually click into the input widget). But I want the gui window stays active and the input widget stays focused.

## To Reproduce
```rust
use fltk::{app::*, enums::*, group, input::*, prelude::*};
use fltk_theme::{ThemeType, WidgetTheme};

use std::process::{Command, Output, ExitStatus};
use anyhow::Error;


#[derive(Clone, Copy)]
enum Message {
    Scan,
}

/*
cargo.toml

# without fltk-bundled, it will panic with linking error 1120
fltk = {version = "^1.2", features = ["fltk-bundled"]}
fltk-theme = "0.1"
*/


#[tokio::main]
async fn main() -> Result<(), Error> {
    let app = App::default();
    let widget_theme = WidgetTheme::new(ThemeType::Aqua);
    widget_theme.apply();

    let mut wind = Window::new(100, 100, 1200, 600, "printer");
    let (sender, receiver) = channel::<Message>();

    let mut text_in = Input::new(105, 260, 1000, 50, "input: ");
    text_in.set_trigger(CallbackTrigger::Changed);
    text_in.emit(sender, Message::Scan);
    set_focus(&text_in);

    wind.end();
    wind.make_resizable(true);
    wind.show();

    // these are made-up values
    let pc_name = "my_pc";
    // content of the print_file is like:
    /*
    <xpml><page quantity='0' pitch='30.0 mm'></xpml>
    SIZE 38.7 mm, 30 mm
    DIRECTION 0,0
    REFERENCE 0,0
    OFFSET 0 mm
    SET PEEL OFF
    SET CUTTER OFF
    SET TEAR ON
    CLS
    QRCODE 135,78,L,4,A,90,M2,S7,"some random text"
    TEXT 25,10,"TSS24.BF2",90,1,1,"some text"
    CODEPAGE 1254
    TEXT 279,20,"1",90,2,2,"0000"
    TEXT 235,122,"TSS24.BF2",90,1,1,"text, well"
    TEXT 232,10,"TSS24.BF2",90,1,1,"good morning"
    TEXT 182,10,"1",90,1,1,"more text"
    TEXT 154,10,"1",90,1,1,"text at last"
    PRINT 1,1
    <xpml></page></xpml><xpml><end/></xpml>
    */
    let print_file = "to_print.prn";
    let printer_name = "my_printer";

    while app.wait() {
        match receiver.recv() {
            Some(Message::Scan) => {
                let scanned_value = text_in.value();
                if scanned_value.ends_with("_scan") {


                    match call_printer(&print_file, &pc_name, &printer_name) {
                        Ok(status) => {
                            if !status.success() {
                                // remind user; beep_alert("failed to print!")
                            } else {

                            }
                }
                Err(e) => log::error!("Error printing: {}", e),
            };
                    text_in.set_value("");
                    set_focus(&text_in);

                }
                }
            }
        }


}


pub fn call_printer(prn_file: &str, _pc_name: &str, printer_name: &str) -> Result<ExitStatus, Error> {
    // PROBLEM: this will make a cmd window flash
    let cmd = format!("COPY /B {} \\\\127.0.0.1\\{}", prn_file, printer_name);
    match Command::new("cmd").args(&["/C", &cmd]).spawn() {
        Ok(mut child) => {
            Ok(child.wait()?)
        },
        Err(e) => {
            return Err(anyhow::anyhow!(e))
        }
    }
}
```

## Expected behavior
I want the gui window stays active and the input widget stays focused and wait for next input.

## Screenshots
focused:
![focused](https://user-images.githubusercontent.com/79682683/147193046-e8ee7be1-26f0-4152-ba9e-05a3b669972d.png)
--
not active and not focused:
![not_focused](https://user-images.githubusercontent.com/79682683/147193090-9f742987-2f8f-45db-aeab-bd4f2a08ff6f.png)

## Desktop info
 - OS: Windows 11 x64
 - Version: 21H2

## Additional info
Frankly I don't know if this is fltk related or I did something wrong with std::process::Command. Sorry if this has nothing to do with fltk-rs. Also, if there is any way to instruct the printer without using cmd, this problem may be avoided?

**Comment by MoAlyousef** [comment]
If a printing dialog pops up, the window will certainly lose focus. Now whether your app's window regains focus depends on the window manager itself. You can try add `text_in.take_focus().unwrap()` in the match of call_printer() in main.

**Comment by wellitecho** [comment]
Just tried it, no luck. I guess this is simply not about fltk-rs.

**Comment by MoAlyousef** [comment]
You can also try making the window a system modal, it requires calling certain win32 apis:
```rust
fn make_topmost(w: &window::Window) {
    assert!(w.shown());
    use std::os::raw::*;
    const SWP_NOSIZE: u32 = 0x0001; // ignore the width and height params
    const SWP_NOMOVE: u32 = 0x0002; // ignore the x and y params
    pub type HWND = *mut c_void;
    extern "C" {
        pub fn SetWindowPos(
            hwnd: HWND,
            hwnd: HWND,
            x: i32,
            y: i32,
            cx: i32,
            cy: i32,
            uflags: u32,
        ) -> i32;
    }
    unsafe {
        let handle = w.raw_handle();
        let val: *mut i64 = std::mem::transmute(-1 as i64);
        SetWindowPos(handle as _, val as _, 0, 0, 0, 0, SWP_NOMOVE | SWP_NOSIZE);
    }
}
```

**Comment by wellitecho** [comment]
I'll try this, thanks. Another thing to add is, I tried to compile the app without `#![windows_subsystem = "windows"]`, so that it keeps a console. Then there is no pop-up, but still, the window will become non-active.

**Comment by wellitecho** [comment]
I tried to use `make_topmost` in my code, but the symptom is still the same.
Also, after the printing, even if I manually Ctrl+tab to switch back to my app window, the app still appears non-active, from the look of its grayed-out window title.

**Comment by MoAlyousef** [comment]
One last suggestion is to try not using process::Command::spawn. This here uses the system() call:
```rust
use fltk::{app::*, enums::*, group, input::*, prelude::*, window};

#[derive(Clone, Copy)]
enum Message {
    Scan,
}

fn main() {
    let app = App::default();
    // set_visible_focus(false);

    let mut wind = window::Window::new(100, 100, 1200, 600, "printer");
    let (sender, receiver) = channel::<Message>();

    let mut text_in = Input::new(105, 260, 1000, 50, "input: ");
    text_in.set_trigger(CallbackTrigger::Changed);
    text_in.emit(sender, Message::Scan);
    set_focus(&text_in);

    wind.end();
    wind.make_resizable(true);
    wind.make_modal(true);
    wind.show();

    let pc_name = "my_pc";
    let print_file = "to_print.prn";
    let printer_name = "HP OfficeJet Pro 6960";

    while app.wait() {
        match receiver.recv() {
            Some(Message::Scan) => {
                let scanned_value = text_in.value();
                if scanned_value.ends_with("_scan") {
                    match call_printer(&print_file, &pc_name, &printer_name) {
                        0 => {}
                        _ => eprintln!("Error printing"),
                    };
                    text_in.set_value("");
                    set_focus(&text_in);
                }
            }
            None => (),
        }
    }
}

pub fn call_printer(prn_file: &str, _pc_name: &str, printer_name: &str) -> i32 {
    // PROBLEM: this will make a cmd window flash
    use std::ffi::CString;
    use std::os::raw::c_char;
    extern "C" {
        pub fn system(args: *const c_char) -> i32;
    }
    let cmd = format!("cmd /C COPY /B {} \\\\127.0.0.1\\{}", prn_file, printer_name);
    let cmd = CString::new(cmd).unwrap();
    unsafe { system(cmd.as_ptr()) }
}
```

**Comment by wellitecho** [comment]
Thanks for your patience and your suggestions.

After hours of looking into it, I think probably the newline string '\n' and my combination of widgets may be part of the cause.

First of all, sorry for not making things clearer from the start:
1. that in reality, the input content comes from a handheld scanner. I use a handheld scanner to scan a qrcode, and the content of the qrcode will be put in the input widget.
2. besides aforementioned Input widget, there is also a check button that is unchecked, another Input widget that's deactivated, two menu::Choice widgets, and several TextDisplay widgets.

The thing is, once the scanner scans the qrcode, it will automatically start a newline after the actual content of the qrcode, same effect as you type some text followed by pressing the Enter key. So if the qrcode contains abc, then the output of the scanner will be like abc followed by a newline.

Even if there is no visual indication for focus switching to other widgets in the app, I suspect it's that newline(or the press of the Enter key) and my combination of widgets that makes the input widget lose focus.

Thanks again for bearing with me.

**Comment by wellitecho** [comment]
To avoid creating a console while running std::process::Command, the solution is described [here by using creation_flags](https://stackoverflow.com/questions/60750113/how-do-i-hide-the-console-window-for-a-process-started-with-stdprocesscomman).

copy/paste here for your reference:

```rust
use std::process::Command;
use std::os::windows::process::CommandExt;

const CREATE_NO_WINDOW: u32 = 0x08000000;
const DETACHED_PROCESS: u32 = 0x00000008;

let mut command = Command::new("cmd").args(&["/C", "start", &exe_path]);
command.creation_flags(DETACHED_PROCESS); // Be careful: This only works on windows

// If you use DETACHED_PROCESS you could set stdout, stderr, and stdin to Stdio::null() to avoid possible allocations.

```

**Comment by MoAlyousef** [comment]
Thanks for sharing this info.
