### ISSUE TITLE
[BUG] fltk::dialog::file_chooser's pattern doesn't work with a description

### ISSUE THREAD

**Issue by mark-summerfield** [fltk-rs/fltk-rs#1072]
```rust
        if let Some(filename) = fltk::dialog::file_chooser(
            "Choose Track — AMP",
            "*.{oga,ogg,mp3}",
            &util::get_track_dir().to_string_lossy(),
            false,
        ) {
            dbg!("on_open", filename); // TODO
        }
```
The above works correctly. However, according to the docs this is a valid pattern too: `"Audio Files\t*.{oga,ogg,mp3}"`, but when I tried it I had two separate entries "Audio Files" and "*.{oga,ogg,mp3}".

Also, note that `fltk::dialog::file_chooser()` really ought to accept a `&str` (as it does), or a `Path` or `PathBuf` for the path (neither of which it does).

**Comment by MoAlyousef** [comment]
I've updated file_chooser to be able to take a &str or a Path/PathBuf. Regarding the docs, I think I just copied the NativeFileChooser's docs on patterns into FLTK's FileChooser, which are apparently different. I've updated the docs. Normailly you should be able to do:
```
"Audio Files (*.{oga,ogg,mp3})",
```
Can you check with the latest master?

**Comment by mark-summerfield** [comment]
Both those fixes work great! I now use the string you quoted above for the pattern and pass in a PathBuf with no problem. Thanks.
