### ISSUE TITLE
[BUG] native file dialog with dir browse type give empty directory 

### ISSUE THREAD

**Issue by cstkingkey** [fltk-rs/fltk-rs#1074]
console gives out following msg:
onecore\com\combase\objact\objact.cxx(4080)\combase.dll!00007FFC7F0E5105: (caller: 00007FFC7F0E1B12) ReturnHr(4) tid(7014) 80040154 class not registered.

onecore\com\combase\dcomrem\security.cxx(3022)\combase.dll!00007FFC7F12CAF0: (caller: 00007FFC753B2BF6) ReturnHr(5) tid(7930) 80010117 Call context cannot be accessed after call completed.

**Comment by MoAlyousef** [comment]
What's in your Cargo.toml?
Is it msvc or mingw toolchain?
Windows version?
Minimal code reproducer?

**Comment by cstkingkey** [comment]
I'm using msvc from vs2022 installation on Win11 22000.376 builds.

can reprodeuce with  following lines inserted to save fn in example editor
        let mut flg = dialog::FileDialog::new(dialog::FileDialogType::BrowseDir);
        flg.show();
        println!("{:?}", flg.directory());

**Comment by MoAlyousef** [comment]
Are you using the fltk-bundled flag in the Cargo.toml?

**Comment by cstkingkey** [comment]
> Are you using the fltk-bundled flag in the Cargo.toml?
No. And tried cargo run --example editor --features use-ninja --target=i686-pc-windows-msvc, same result.

> Also what if you use flg.set_directory("."); before calling flg.show()?
with flg.set_directory(&".".to_string())?;, nothing changed. still get "" result

**Comment by MoAlyousef** [comment]
How about:
```rust
        let mut dlg = dialog::FileDialog::new(dialog::FileDialogType::BrowseDir);
        dlg.show();
        println!("{:?}", dlg.filename());
```

**Comment by cstkingkey** [comment]
> How about:
> 
> ```rust
>         let mut dlg = dialog::FileDialog::new(dialog::FileDialogType::BrowseDir);
>         dlg.show();
>         println!("{:?}", dlg.filename());
> ```

It works. 
For some reason, I also get empty result by dlg.filename() several times. But I can't reproduce it anymore. Maybe cross-thread message related. Anyway, this is invalid. Sorry for the bother.
