### ISSUE TITLE
Implement cursor2rowcol

### ISSUE THREAD

**Issue by AshfordN** [fltk-rs/fltk-rs#1077]
**Is your feature request related to a problem? Please describe.**
I'm trying to identify which table cell the cursor is hovering over, so that I can set an appropriate tooltip if part of the text is clipped. For this I need to find the table cell's row and column, using the cursors XY coordinates.

**Describe the solution you'd like**
From the [FLTK docs](https://www.fltk.org/doc-1.4/classFl__Table.html#a0a60096041f992f032a077238b50e277) the `cursor2rowcol()` function seems to provide this functionality. So I would like to be able to access this function. Perhaps the wrapping function can return `Option<(i32, i32)>` since this check is not guaranteed to find a cell.

**Describe alternatives you've considered**
There is really no alternative way of achieving this, unless you loop through all the visible cells and check them, individually, against the cursor position.

**Additional context**
None necessary, since the feature request is straightforward, and links directly to a function in the underlying API.

**Comment by MoAlyousef** [comment]
I've added `TableExt::cursor2rowcol(&self) -> (TableContext, Option<i32>, Option<i32>, TableResizeFlag);` to the master branch. Can you try it out?

**Comment by MoAlyousef** [comment]
I've changed the signature to `TableExt::cursor2rowcol(&self) -> Option<(TableContext, i32, i32, TableResizeFlag)>;`.

**Comment by AshfordN** [comment]
Heh, I was just typing a comment on the PR, to point out that the row and column checks were a bit off.

**Comment by AshfordN** [comment]
Does this function name follow rust's naming convention though? It seems a bit off.

**Comment by MoAlyousef** [comment]
It does. Rustc & Clippy don’t complain though

**Comment by AshfordN** [comment]
alright, well everything seems to be working correctly
