### ISSUE TITLE
expose fl_add_symbol()

### ISSUE THREAD

**Issue by AshfordN** [fltk-rs/fltk-rs#1098]
**Is your feature request related to a problem? Please describe.**
I want to be able to define custom symbols for use throughout my application -- within labels and other similar contexts.

**Describe the solution you'd like**
Based on the FLTK documentation [here](https://www.fltk.org/doc-1.3/common.html), under the section **Making your own symbols**, and the documentation for `fl_add_symbol()` [here](https://www.fltk.org/doc-1.3/group__fl__drawings.html#ga4a4771df55d9ab87de12da62799e290b), `fl_add_symbol()` is the idiomatic way of achieving this.
 Perhaps this could be exposed as: `app::add_symbol(&str, fn(enums::Color), bool)`

**Describe alternatives you've considered**
I've considered using images via the `WidgetExt::set_image()` and `WidgetExt::set_deimage()` functions, but static images do not provide the kind of flexibility I need. For example, If I use static images in labels it's not easy to change the color of the image dynamically if the font color changes.

**Additional context**
NA

**Comment by MoAlyousef** [comment]
I've added app::add_symbol with the following signature:
```rust
fn add_symbol(label: &str, scalable: bool, draw_cb: fn(Color)) -> Result<(), FltkError>;
```
The callback being the last parameter to allow for inline definition of the draw function.

**Comment by AshfordN** [comment]
Thank you.
