### ISSUE TITLE
fltk + reqwest fails !

### ISSUE THREAD

**Issue by gopakumarce** [fltk-rs/fltk-rs#1102]
I am hitting a very wierd issue. I have been using reqwest in my module quite fine till I added in fltk. And with fltk in picture, reqwest client new/build fails with error reqwest::Error { kind: Builder, source: Normal(ErrorStack([])) }

I traced it into the reqwest stack and the failure is because Connector::new_default_tls() in client.rs in reqwest fails - thats basically traced back to rust-native-tls new connector initialization - I have not dug deeper than that yet, wanted to check if anyone has ideas on why this is failing ? I got fltk working in 45 mins, but have spent a whole day debugging why my reqwest fails ;-(. Any clues will be appreciated !

-- More digging: The exact failure is below--

```
openssl-0.10.34/src/ssl/mod.rs:

impl SslContextBuilder {
    /// Creates a new `SslContextBuilder`.
    ///
    /// This corresponds to [`SSL_CTX_new`].
    ///
    /// [`SSL_CTX_new`]: https://www.openssl.org/docs/manmaster/man3/SSL_CTX_new.html
    pub fn new(method: SslMethod) -> Result<SslContextBuilder, ErrorStack> {
        unsafe {
            init();
            let ctx = cvt_p(ffi::SSL_CTX_new(method.as_ptr()))?;  <<==== THE SSL_CTX_new() returns NULL !!!!

            Ok(SslContextBuilder::from_ptr(ctx))
        }
    }
<snip>
```

Rgds,
Gopa.

**Comment by MoAlyousef** [comment]
It might be a problem with the initialization of openssl, can you try initializing it before any fltk code?

**Comment by gopakumarce** [comment]
Hi @MoAlyousef - so we dont directly initialize openssl, we use reqwest::Client which internally uses openssl. I tried calling reqwest::Client even before all fltk calls are made, that doesnt help. I even commented out all fltk calls, but just the lib itself being linked in causes the problem !!

**Comment by gopakumarce** [comment]
Finally I decided to work around it by using vendored openssl (ie compiled-in openssl rather than relying on the system). I believe its something happening with the FFI initialization order since like I mentioned the issue happens without me making any calls to fltk, just linking in fltk is enough to cause the issue

**Comment by MoAlyousef** [comment]
Yeah it could be a shared dependency version mismatch (libc, pthread …etc)
