### ISSUE TITLE
Flex component exchanging row for column?

### ISSUE THREAD

**Issue by jcbritobr** [fltk-rs/fltk-rs#1122]
fltk-rs version - 1.2.28
rust version - 1.58.1 - gnu toolchain
os - Microsoft Windows 11 64 bits

Description
I was trying some examples and using flex component had noticed that when I choose group::FlexType::Row, the components inside are are organized in columns, and vice versa, as we can see in printscreen, and the source code. Maybe I'm wrong but it seems very strange.

```rust
  let mut wind = Window::new(0, 0, 400, 300, "Simple Window");
  let mut flex = Flex::new(0, 0, 400, 300, None);
  flex.set_type(group::FlexType::Row);
  let _expanding = Button::default().with_label("Expanding");
  let mut cmd_load = Button::default().with_label("Load");
  flex.set_size(&mut cmd_load, 30);
  flex.end();
  wind.show_with_env_args();
```

![image](https://user-images.githubusercontent.com/6579862/151604631-6ef04c16-64af-4691-9015-1446f4be36bb.png)

Whats Wrong?

group::FlexType::Row seems have exchange value with group::FlexType::Column

Expected

group::FlexType::Row organize components in rows.

**Comment by MoAlyousef** [comment]
Hi
This is the correct behaviour. A row is filled from left to right, while a column is filled from top to bottom.
