### ISSUE TITLE
[BUG] Setting size_range to i32::MAX causes window to never be resizable

### ISSUE THREAD

**Issue by EthanWeegee** [fltk-rs/fltk-rs#1130]
## Describe the bug
When setting `window.size_range()` to i32::MAX, Windows builds will be broken and are no longer sizable. In particular, I found that by uncommenting [this line](https://github.com/EthanWeegee/simple-nus3audio-gui/blob/5ab5d3512b2cd2938bfa0bfb1e7daf46fc581286/src/main.rs#L68), I can cause the bug.

## To Reproduce
```rust
use fltk::prelude::*;
fn main() {
	let app = fltk::app::App::default();
    let mut window = fltk::window::Window::default();
	window.size_range(20, 20, i32::MAX, i32::MAX);
	window.end();
	window.show();

	while app.wait() {}
}
```
This example works as expected in Linux builds and is bugged in Windows builds. Changing i32::MAX to 900 for example works as expected.

## Expected behavior
The window should be resizable to the full range, and on every platform.

## Desktop info
 - Host OS: openSUSE Tumbleweed
 - Snapshot 20220201
 Also reproducible when building on another machine running openSUSE Leap 15.3.

**Comment by MoAlyousef** [comment]
Hi
You can pass 0 instead of i32::MAX and this will enable ulimited upward resizing of the window.
I've updated the docs and added a check on size_range() in master.

**Comment by EthanWeegee** [comment]
Ah! That's my bad then. I find the fltk.org documentation hard to read, so I never bothered checking them. Now that you mention it, this [was mentioned there](https://www.fltk.org/doc-1.3/classFl__Window.html#aa0f717a52f23e54d7db8fee71a5f299e). Sorry for the trouble.
