### ISSUE TITLE
Expose fl_message_icon

### ISSUE THREAD

**Issue by abau** [fltk-rs/fltk-rs#1136]
Hi,

is there a way to change/disable the icon for standard dialogs like `fltk::dialog::choice`?

FLTK itself provides [`fl_message_icon`](https://www.fltk.org/doc-1.3/group__group__comdlg.html#gac761d3edfeb4b4e78d36c4c0d19c8906) which seems not to be exposed by `fltk-rs`.

Thanks for your help!

**Comment by MoAlyousef** [comment]
Hello

Currently there’s no way to change it. I can expose fl_message_icon before the next release in a few days.

**Comment by abau** [comment]
> I can expose fl_message_icon before the next release in a few days.

That would be great. Thanks.

**Comment by MoAlyousef** [comment]
I've exposed dialog::message_icon. Although I'm able to modify several things in the box, I can't modify the message. It might be a platform issue, I tried the suggestion here:
https://groups.google.com/g/fltkgeneral/c/s6y_xy9Wfzo

But that didn't work out. Tried with a C++ repro and it's the same issue.

**Comment by abau** [comment]
> Tried with FLTK 1.3.5 and it seems to work

Nice, thanks for your efforts!

**Comment by MoAlyousef** [comment]
Related issue in the FLTK repo:
https://github.com/fltk/fltk/issues/395
