### ISSUE TITLE
FileDialog disables resizing

### ISSUE THREAD

**Issue by ThiNei2l** [fltk-rs/fltk-rs#1146]
Hello,

it seems that opening a FileDialog messes with resizing:
```rust
use fltk::{app, prelude::*, window::Window, button::Button, dialog};

fn main() {
    let app = app::App::default();
    let mut wind = Window::new(100, 100, 400, 300, "Hello from rust");
    let mut but = Button::new(160, 210, 80, 40, "Click me!");
    wind.end();
    wind.make_resizable(true);
    wind.show();

    let mut dlg = dialog::FileDialog::new(dialog::FileDialogType::BrowseFile);
    but.set_callback(move |_| dlg.show());

    app.run().unwrap();
}
```
This will open a resizable window as expected:
![before](https://user-images.githubusercontent.com/76494498/155854267-be362d12-33c0-40de-81d7-99beeae763f8.png)
However, as soon as the FileDialog is opened the main window cannot be resized anymore:
![after](https://user-images.githubusercontent.com/76494498/155854265-f0273d4f-70d7-4750-ae87-8382e0abe68a.png)

## Desktop info
ArchLinux(5.16.11), xorg 21.1.3

## Additional info
I believe this was introduced in 1.2.28.

**Comment by MoAlyousef** [comment]
Hello
Thanks for reporting this.
It seems the maximize button disappears after opening the dialog. This also occurs with a C++ repro. I'll try to investigate further then open an issue upstream.

**Comment by ThiNei2l** [comment]
Good point.
I hadn't thought about different window managers.
The screens are using xfce4 (xfwm4 4.16.1).

However, under lxqt (using openbox) everything works fine.
I might try a few different managers this evening.

Also: It's not just the button disappearing. The window cannot be resized at all (e.g. using the windows border)

**Comment by MoAlyousef** [comment]
Interesting. On kubuntu resizing is possible. But I’ll update the issue upstream.

**Comment by ThiNei2l** [comment]
I can reproduce your behaviour: on plasma only the button disappears, but resizing using the window border still works.

What I have seen for now:
LXQt / openbox and MATE / marco: Everything works fine.
Plasma / KWin: Only the button disappearing.
Xfce / Xfwm: Resizing completely broken.

**Comment by MoAlyousef** [comment]
Do you know the type of file dialog that appears on your xfce/xfwm system?
On my kubuntu system, I was able to pin the issue to some work on the kdialog, but if xfce uses another dialog, it might be a different/later commit causing the issue.

**Comment by ThiNei2l** [comment]
I'm not sure tbh. How many file dialogs are there?
Since Xfce is based on GTK3, that would make kdialog unlikely I guess.
Sadly I won't have much time this week, but I will try to take a closer look when I find some time.

**Comment by MoAlyousef** [comment]
I've pulled the fix from FLTK and checked on my Kubuntu system and it works. Can you check on Xfce?

**Comment by ThiNei2l** [comment]
I think it's probably fixed, but I need to take a closer look.

On my regular system (which uses Xfce) the bug is fixed and everything seems to work perfectly again.

However: I have a separate installation in a VM which I used to check different desktop environments (LXQt, MATE, KDE, Xfce).
On that system the bug is still present.

This seems to be a problem at compile time.
If I compile the program on the host everything works and when I copy it over to the guest it works there too.
If I compile on the guest the bug is still present - on both systems.

Right now I'm assuming that the bug is fixed and I'm overlooking something.
I just cannot figure out where the difference is yet.
Both systems use the same versions of pretty much everything, including rust and cargo.
They compile the same code, using the same `.lock`-file.
I can see that both use https://github.com/fltk-rs/fltk-rs/commit/91e0474799b17301eb0e99869fbf9e50278ea697.
To be sure I ran `cargo clean` and deleted the `~/.cargo` directory on both systems before compiling.
The difference is still there.

I will take another look this weekend.

**Comment by MoAlyousef** [comment]
If you're building a clone of fltk-rs, you'll have to cd into fltk-sys/cfltk/fltk directory and perform a `git pull` to get the updated commit.

**Comment by ThiNei2l** [comment]
Hello again.
I found it now.

I really used a basic setup.
The `Cargo.toml` is just this:
```toml
[package]
name = "fltk_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = { git = "https://github.com/moalyousef/fltk-rs" }
#fltk = { version = "1.2.27" }
```

The problem was that not all build-tools were installed on the guest system (e.g. cmake was missing).
After a simple `pacman -S base-devel` everything works fine now.
I'm still a bit puzzled as to why the build process went through and then produced a still bugged binary, even though cargo did use https://github.com/fltk-rs/fltk-rs/commit/91e0474799b17301eb0e99869fbf9e50278ea697.

But as far as I'm concerned everything is fine now (and finally reproducible 🥳).
Builds from both systems now work perfectly on both systems on all desktop environments (including Xfce).

Many thanks for the help!

**Comment by MoAlyousef** [comment]
When CMake is absent, cargo downloads the prebuilt binaries automatically and links them. It does output a warning that it's not building FLTK from source, but that would only show if the build failed.
Anyways, great to read. Thanks for confirming :)
