### ISSUE TITLE
Terminal example `state` comparison instead bit mask check

### ISSUE THREAD

**Issue by vit1251** [fltk-rs/fltk-rs#1148]
Terminal example check application state on `==` with Control in https://github.com/fltk-rs/fltk-rs/blob/1e0a28f09e378ff47401802a5eaefce9cadd00d0/fltk/examples/terminal.rs#L197

But active state is 

```
state = Ctrl | Command | 0x100000
```
You should check bit mask instead use equal operator.

**Comment by MoAlyousef** [comment]
It's ok to check exact equality when you're only expecting the same bit representation as Shortcut::Ctrl.
The "active state" you're seeing is just the debug output of event_state() since it uses the bitflags macro.
