### ISSUE TITLE
A Screen type

### ISSUE THREAD

**Issue by joseluis** [fltk-rs/fltk-rs#1161]
Hi, first of all thank you for all the good work you're doing here. I'm loving how light, portable, versatile, customizable, stable, and simple to use FLTK seems to be, and I'm very happy that it really looks totally usable from Rust, idiomatically and without sugar/dark-magic. Your examples and videos are also helping a lot to figure out things quicker so thank you very much for that.

When looking on how to get screen information I was surprised to found only a [thinly wrapped subset](https://docs.rs/fltk/latest/src/fltk/app/screen.rs.html) of the [fltk-1.4 screen functions](https://www.fltk.org/doc-1.4/group__fl__screen.html).

I don't know if you have considered it before, but it maybe nice to have a `Screen` abstraction (like `Window` and `App`), and have the `screen_` funtions under its namespace.

Exposing the missing overloaded functions of `screen_num`, `screen_work_area` and `screen_xywh` as differently suffixed methods would be nice too, like for example: 

```rust
// Gets the screen number for the screen which intersects the most with the rectangle defined by x, y, w, h. 
fn screen_num_intersecting(x: i32, y: i32, w: i32, h: i32) // or screen_num_most_inside?...
```

Another step would be to allow instantation of a `Screen`, wrapping a screen number, and then making the relevant methods can `&self` so that they can be used both as instance's methods and also as uninstanced associated functions.

Does this make sense to you in the context of the vision of the API you have?

**Comment by MoAlyousef** [comment]
The old implementation used to divide the returned values by 0.96. 
The problem was my dev pc, and that wasn’t really required since it was a scaling issue.

**Comment by joseluis** [comment]
Thanks, understood.

I have another question, regarding returning bounding boxes for the work area, instead of returning a tuple of 4 unnamed values (x,y,w,h) ideally I think it would be more user friendly and versatile to return something like a `struct BoundingBox { x:i32, y:i32, w:i32, h:i32 }`.

The only problem I see is global coherence with the rest of the API, since there are 21 other functions places returning a tuple of four `i32`s (although I'm not sure if in every case its `x,y,w,h` or in some cases may be `x1,y1,x2,y2`. Most of those are public traits functions so it would be a breaking change. 

What is your opinion on this? Do you like the idea of return a bounding box, or a rect, for the upcoming version 2.0?

**Comment by MoAlyousef** [comment]
I would prefer Rect over BoundingBox. 

Generally returns of a tuple of four i32 vals is x, y, w, h. 

Theres a Coords struct which can also be used especially to refactor the drawing methods, prior to a 2.0 version.

**Comment by joseluis** [comment]
> Theres a Coords struct which can also be used especially to refactor the drawing methods, prior to a 2.0 version.

Ok, I can make a new generic `Rect` struct under the `draw` module, too, in the style of `Coord`.

1. I see there are several cases like `draw_point(i32, i32)` alongside `draw_point2(Coord<i32>)`. Are those created in preparation for 2.0? Will they be unified/deprecated?

2. In that case do you see the creation of a `measure2(...) -> Coord` function, `wrap_measure2(...)`, `text_extents2(...) -> Rect<i32>`, etc.? 

3. I see some naming inconsistencies like `draw_arc()` which takes `i32` and `draw_arc2()` which takes `f64`. Maybe cases like that should be renamed for 2.0 adding a more semantic suffix?

**Comment by joseluis** [comment]
Another thing, regarding the ergonomics of using the generic `Coord` and future `Rect`, in order to avoid entering `Coord<i32>` everywhere, maybe some type aliases could be created to make `Coord` more convenient to use in the most common case? Some like this: 
```rust
pub struct Coordinates<T: Copy>(pub T, pub T); //rename the generic
pub type Coord = Coordinates<i32>; // the most common case the briefest to write
pub type Coord_f64 = Coordinantes<f64>;

// the more fields there are, the most important is they're named
pub struct Rectangle<T: Copy>{
  pub x: T,
  pub y: T,
  pub w: T,
  pub h: T,
}
pub type Rect = Rectangle<i32>;
pub type Rect_f64 = Rectangle<f64>;
```

Finally, do you have a strong preference regarding using unnamed tuple fields for `Coord` instead of named `x, y` struct fields?

**Comment by MoAlyousef** [comment]
Yeah it can be generic along with aliasing for convenience. Coords can also be tuple struct with unnamed fields.
