### ISSUE TITLE
Relaxing requirements on metod set_column_widths() of Browser widget

### ISSUE THREAD

**Issue by captchaKing** [fltk-rs/fltk-rs#1162]
**Is your feature request related to a problem? Please describe.**
Right now it's hard to assign dynamically created columns (by reading from configuration file or something) because of static lifetime requirement on set_column_widths() of Browser widget. As i understand it, array holding widths should be of static length.

**Describe the solution you'd like**
Relaxing requirements to `fn set_column_widths(&mut self, arr: &[i32])` that allows passing `Vec<i32>` in this method.

**Comment by MoAlyousef** [comment]
I've relaxed the static requirement.

**Comment by captchaKing** [comment]
Thnak you!
