### ISSUE TITLE
1.3.2 Undefined references when building with fltk-bundled on x86_64-pc-windows-gnu

### ISSUE THREAD

**Issue by aaronps** [fltk-rs/fltk-rs#1174]
## Describe the bug

Undefined references when building with `fltk-bundled` on `x86_64-pc-windows-gnu` using fltk-rs 1.3.2, the missing functions are:

- Fl_screen_work_area_mouse
- Fl_screen_xywh_mouse
- Fl_keyboard_screen_scaling

I verified that these functions are not within the library file in the gnu build (using `objdump`) and they are in the msvc build. 

I can confirm that it builds and run properly when not using the fltk-bundled feature.

## To Reproduce

Build a minimal project using fltk-bundled flag using the gnu toolchain

## Expected behavior

Should build correctly

## Desktop info

 - Win10 x64

## Additional info

First I tried to build not using my local msys2 installation but it complained that cannot find `-lglu32` and `-lgdiplus` (I think I saw an option about that on the cmakefiles), so I added the paths to my local msys2 installation and got the error.

**Comment by MoAlyousef** [comment]
Thanks for the report. I've just updated the prebuilt binary. Can you try `cargo clean` then `cargo run`?

**Comment by aaronps** [comment]
Yes, it works! Thanks.

**Comment by aaronps** [comment]
Thanks, so fast!

It builds correctly and now it requires 28 extra dll files from msys2, when running it complains there is a function missing from libpng16-16.dll maybe we are using different versions, I’m updating my environment and see how it goes.

**Comment by MoAlyousef** [comment]
I have a repo with prebuilt fltk libs:
https://github.com/MoAlyousef/fltk_prebuilds/actions/runs/3228313207

I'm not sure for the gnu toolchain, whether the msys-mingw64 one is more appropriate or the one built with rust-mingw.
You can try both and see whether one is better for your deployment needs.
