### ISSUE TITLE
support   Fl_Browser::item_first(),   item_next() ...

### ISSUE THREAD

**Issue by langzime** [fltk-rs/fltk-rs#1175]

**Comment by langzime** [comment]
I think Very useful

**Comment by MoAlyousef** [comment]
These methods are protected, so adding them isn’t straightforward.

**Comment by langzime** [comment]
Thank you very much. You've helped me！

**Comment by langzime** [comment]
close it?

**Comment by MoAlyousef** [comment]
You’re most welcome. I’ll close it.
