### ISSUE TITLE
Support data for Browser

### ISSUE THREAD

**Issue by 64kramsystem** [fltk-rs/fltk-rs#1184]
**Is your feature request related to a problem? Please describe.**

I have a list of entries, associated with some data, that, while textual, can't be displayed to the user.

**Describe the solution you'd like**

FTLK Browser class supports "data" associated to each line; a few methods are associated (e.g. [this](https://www.fltk.org/doc-1.3/classFl__Browser.html#af2761597d5618fa4d1339563ee127e29)).

From an API perspective, it's possible to extend fltk-rs APIs (at a minimum, by implementing the `data` getter/setter methods).

**Describe alternatives you've considered**

Creating a custom widget, but this is I think not trivial.

The functionality can be emulated by keeping a dictionary of the entries <> data, although this is definitely not a clean solution.

**Additional context**

(skipped)

**Comment by MoAlyousef** [comment]
Hi
I've added BrowserExt::add_with_data, insert_with_data, set_data and data methods.
I've marked BrowserExt::data() as unsafe.

**Comment by 64kramsystem** [comment]
> Hi I've added BrowserExt::add_with_data, insert_with_data, set_data and data methods in the master branch. It can be tested using:
> 
> ```toml
> [dependencies]
> fltk = { git = "https://github.com/fltk-rs/fltk-rs" }
> ```
> 
> I've marked BrowserExt::data() as unsafe.

Amazing! Thanks for your attention and efficiency :smile:
