### ISSUE TITLE
[BUG] Segfault when setting a Browser line icon to a SharedImage created from a PngImage

### ISSUE THREAD

**Issue by 64kramsystem** [fltk-rs/fltk-rs#1186]
## Describe the bug

If I set a Browser line icon to a SharedImage that was created from a PngImage, I get a segfault.

## To Reproduce

Any PNG image should trigger the issue. I've experienced the problem with several.

```rs
use fltk::{
    image::{PngImage, SharedImage},
    prelude::*,
    *,
};
fn main() {
    let app = app::App::default();

    let mut win = window::Window::default().with_size(900, 300);
    let mut b = browser::HoldBrowser::new(10, 10, 900 - 20, 300 - 20, "");
    b.add("Test");

    let image_bytes = include_bytes!("/path/to/image.png");
    let png_image = PngImage::from_data(image_bytes).unwrap();
    let shared_image = SharedImage::from_image(png_image).unwrap();

    b.set_icon(1, Some(shared_image));

    win.end();
    win.show();
    app.run().unwrap();
}
```

## Expected behavior

No crash.

## Screenshots

N.A.

## Desktop info

 - OS: Ubuntu MATE
 - Version: 20.04.4

## Additional info

(none)

## Build failures

N.A.

**Comment by MoAlyousef** [comment]
Thanks for the report. I’ll check it this evening. Is it only limited to png images?
Also would b.set_icon(1, Some(png_image)) work correctly?

**Comment by 64kramsystem** [comment]
> Thanks for the report. I’ll check it this evening. Is it only limited to png images? Also would b.set_icon(1, Some(png_image)) work correctly?

Hello! I've tried only with PNG images. Setting the icon as unconverted`PngImage` works correctly!

**Comment by MoAlyousef** [comment]
I think it’s a SharedImage problem. 
It could be that browser widgets don’t support SharedImage icons, like Window:

https://github.com/fltk-rs/fltk-rs/blob/8a28c59903a2b7e6a22d776e53bed758f9dc5e49/fltk/src/macros/window.rs#L114

In which case I’ll add an assert macro. Or SharedImages might require special handling. I’ll try to check things out.

**Comment by MoAlyousef** [comment]
The issue was in the implementation of SharedImage::from_image(). It should now be fixed in master.

**Comment by 64kramsystem** [comment]
Thanks! I've tested the new master version, and the crash doesn't happen anymore!
