### ISSUE TITLE
[BUG] Switch to stable for docs building

### ISSUE THREAD

**Issue by 64kramsystem** [fltk-rs/fltk-rs#1187]
Currently, the projects docs don't build (see [here](https://docs.rs/crate/fltk/1.3.4/builds/539596)).

Seemingly, this is caused by a bug in the nightly cargo doc, for which I've [opened an issue](https://github.com/rust-lang/rust/issues/96079) on the rust compiler repository.

Building the fltk-rs documentation with stable rust currently succeeds. I think that if possible (I'm not familiar with docs.rs), building via stable would be both more consistent with the project (which doesn't require nightly) and more stable (since nightly is relatively unstable).

**Comment by MoAlyousef** [comment]
I think docs.rs by default uses a nightly compiler. Can that be changed?

I can remove the rustdoc-scrape-examples arg until the rustdoc issue is fixed.

**Comment by 64kramsystem** [comment]
> I think docs.rs by default uses a nightly compiler. Can that be changed?
> 
> I can remove the rustdoc-scrape-examples arg until the rustdoc issue is fixed.

Hi there! I'm not familiar with docs.rs, but it seems that one can't set the compiler (I was hoping for it...).

I think it's important to have up to date docs, so removing the troublesome examples would be best - but that's my opinion :smile:

**Comment by MoAlyousef** [comment]
I’ll inquire whether it’s possible to specify a stable compiler or not in the rustdoc team’s discord.

**Comment by MoAlyousef** [comment]
I’ve disabled the scrape-examples flag and still the docs.rs build failed. It’s also not possible to switch to a stable compiler on docs.rs. I guess we’d have to wait till the nightly problem is fixed.

**Comment by MoAlyousef** [comment]
Closing since the rustdoc bug was fixed.
