### ISSUE TITLE
high cpu usage in rdp session

### ISSUE THREAD

**Issue by cstkingkey** [fltk-rs/fltk-rs#1207]
run example editor on windows host machine. close remote desktop client. reconnect to the host machine. the app is using one full core.

 -host machine OS: Windows 11 22000.675
 -rdp client: Microsoft remote desktop, Version 10.5.2 (1863)

**Comment by MoAlyousef** [comment]
Is it only the editor example? How about the hello_button example?

**Comment by cstkingkey** [comment]
> Is it only the editor example? How about the hello_button example?

same issue. it's not example specific.

the cpu usage will drop to 0 after a "minimize and restore" operation.

**Comment by MoAlyousef** [comment]
It might be an FLTK issue in that case. I’ll try to reproduce in C++ and report upstream.

**Comment by MoAlyousef** [comment]
It seems to be a known issue with dwm (the desktop window manager):
https://www.repairwin.com/fix-dwm-exe-high-cpu-usage-while-connecting-through-rdp-in-windows-10-solved/

You can try building with feature `no-gdiplus` to see if that helps. Otherwise, the linked page shows several methods of circumventing the issue. I’ll still try to reproduce the issue and see if the above suggestion helps.

**Comment by cstkingkey** [comment]
no-gdiplus has no effects.

do a simple break

calling stack

win32u.dll!00007ff906a2abf4()
user32.dll!00007ff906d3d1ee()
user32.dll!00007ff906d3d0e5()
Fl_WinAPI_System_Driver::wait(double)
Fl::wait(void)
Fl_Window_Driver::wait_for_expose(void)
Fl_Screen_Driver::rescale_all_windows_from_screen(int,float)
Fl_Menu_Window::`vector deleting destructor'(unsigned int)
user32.dll!00007ff906d31c4c()
user32.dll!00007ff906d3179c()
user32.dll!00007ff906d50ada()
ntdll.dll!00007ff908f27e04()
win32u.dll!00007ff906a213b4()
user32.dll!00007ff906d39f0f()
user32.dll!00007ff906d39e7a()
Fl_WinAPI_System_Driver::wait(double)
Fl::wait(void)
fltk::app::rt::wait()
fltk::app::App::wait(fltk::app::App self)

**Comment by MoAlyousef** [comment]
Since I don't have a windows host I can access via rdp, can you try with a native FLTK C++ application like Fluid. If the problem occurs also with Fluid, it might be better to report upstream as well.

**Comment by cstkingkey** [comment]
> Since I don't have a windows host I can access via rdp, can you try with a native FLTK C++ application like Fluid. If the problem occurs also with Fluid, it might be better to report upstream as well.

Fluid do have the same issue.

**Comment by MoAlyousef** [comment]
Yeah it would be better if you could open an issue at the FLTK repo.
