### ISSUE TITLE
[BUG] Resize event is not being called

### ISSUE THREAD

**Issue by DrTheodor** [fltk-rs/fltk-rs#1211]
## Describe the bug
For some reason `Event::Resize` is not being called.

## To Reproduce
```rust
self.wid.handle({
    move |b, ev| match ev {
        Event::Resize => {
            println!("E");
            true
         }
         _ => false,
    }
});
```

This code doesn't print anything in console.

**Comment by DrTheodor** [comment]
UPD: I have really similar `Resize` event handling in my code in another custom widget and it works.

**Comment by MoAlyousef** [comment]
Hi

The Resize event happens at the window level, so when you handle it in some widget and return `true`, the Resize event isn't propagated to other widgets.
You can return false in this case, or use WidgetExt::resize_callback() method, as long as you don't modify the size/coords inside of it, or use the widget parent's resize_callback() if you need to modify the size/coords of the widget.

**Comment by DrTheodor** [comment]
Hello. Thank you, changing it to return `false` fixes my problem :D
