### ISSUE TITLE
Regression issue in 1.3.8 - x86_64-pc-windows-gnu

### ISSUE THREAD

**Issue by yveszoundi** [fltk-rs/fltk-rs#1218]
## Describe the bug
Since `1.3.8` I can no longer cross-compile Windows builds from Linux docker containers. The build now complains about being unable to find `the native static library cfltk` (`fltk-bundled` feature, `+crt-static` in `RUSTFLAGS`) . 

The problem was observed only with Windows and the `x86_64-pc-windows-gnu` architecture target
- No errors observed with `1.3.8` when cross-compiling for Mac OS (`x86_64-apple-darwin`)
- Everything is also still fine for Linux (`x86_64-unknown-linux-musl` and `x86_64-unknown-linux-gnu`).

## To Reproduce

You need [Docker](https://docs.docker.com/get-docker/) or [Podman](https://podman.io/) to quickly reproduce exactly the issue

```
git clone https://github.com/yveszoundi/fltk-rs-issues-windows-gnu
cd fltk-rs-issues-windows-gnu
docker run --privileged -v "${PWD}":/src docker.io/uycyjnzgntrn/rust-windows:1.60.0 sh -c "cd /src && RUSTFLAGS='-C target-feature=+crt-static' cargo build --verbose --release --target x86_64-pc-windows-gnu"
```

## Expected behavior
The code should compile cleanly with `1.3.8` similarly to `1.3.7`, I don't know exactly what's different. 

I re-verified that everything was indeed fine in `1.3.7`, by forcing a fixed version in my build dependencies:
`fltk = { version = "=1.3.7", features = ["fltk-bundled"] }`

## Screenshots
Build failures of [dangerzone-rust](https://github.com/rimerosolutions/dangerzone-rust)

![cross-compile-error](https://user-images.githubusercontent.com/5206067/172510277-e3acb191-ba54-4e9b-9830-fc41d103c3d2.png)

## Desktop info
 - Build environment: `Podman` running official Rust docker image
   - `Debian bullseye` (11)
   - Rust `1.6.0`
   - `x86_64-pc-windows-gnu` architecture target
   - `g++-mingw-w64-x86-64` extra package installed via `apt install`
   - `fltk-bundled` feature and `+crt-static` set in RUSTFLAGS
 - Guest machine running the build: `Ubuntu jammy` (22.04) QEMU virtual machine,  `podman` build containers
 - Host machine: iMac pro running `MacOS Monterey` (12.4)

## Additional info
As soon as I realized that `1.3.8` was officially released, I switched back from `git master` to the latest official release.
The build failures were first noticed in [dangerzone-rust](https://github.com/rimerosolutions/dangerzone-rust):

- Branch: `spiral15`
- Build script: `ci_cd/windows/build.sh`

## Build failures
`No fltk-rs release build failures` per say, apparently a behavior change in `fltk-sys` and/or `cfltk`

**Comment by Ar37-rs** [comment]
Rust flags: +crt-static is only for MSVC toolchain i think

**Comment by yveszoundi** [comment]
Thanks for the reply,

I confirm that =+crt-static= also works for windows-gnu, per bug report. I only started observing issues with `1.3.8`. 

As a current mitigation approach, I modified my CI/CD shell scripts for Windows builds:
- Create a dedicated Cargo file for Windows with a fixed release `1.3.7`
- At build time in my shell scripts rename the Windows `Cargo.toml` 

Again, it "just works" with `fltk-1.3.7`
<img width="797" alt="Screen Shot 2022-06-08 at 3 13 02 AM" src="https://user-images.githubusercontent.com/5206067/172554756-4157114b-5e3e-42ec-a2f3-df4d2c312279.png">

**Comment by Ar37-rs** [comment]
i confirm that the static libraries inside lib_x64-windows-gnu.tar.gz and lib_x64-windows-msvc.tar.gz they are the same. that's probably the cause, the static libraries inside both tar.gz files are compiled for MSVC toolchain.

**Comment by MoAlyousef** [comment]
Oops. That was a mistake in the release process. I've updated the lib_x64-windows-gnu.tar.gz archives.

**Comment by Ar37-rs** [comment]
@MoAlyousef thank you,  i had no idea what's was going on. i thought there's something wrong on CI side.

**Comment by MoAlyousef** [comment]
WindowExt::icon_label and set_icon_label were the last symbols to be added. It seems to suggest that the generated archive is somehow not seeing them. I’ll clean the build, update everything then upload a new (and tested archive). Unfortunately I can’t do it in the coming hours. But hopefully tonight.

**Comment by yveszoundi** [comment]
Thanks a bunch.

No stress or need to rush, please take your time: I do appreciate your pro-activeness and your work.

**Comment by MoAlyousef** [comment]
I've uploaded a new archive, and have tested before and after and it seems to work. Can you try things on your side?
Thank you

**Comment by yveszoundi** [comment]
Thank you both @Ar37-rs and @MoAlyousef , it's now working just fine.

I can't reproduce the bug anymore on both a dummy project, as well as on the application where I first noticed the issue.
