### ISSUE TITLE
Reset Fl_Group::current

### ISSUE THREAD

**Issue by abau** [fltk-rs/fltk-rs#1231]
I have the following use-case: when certain conditions are being met during runtime, my program does the following:

1. It modifies a `group::Flex` (removes some widgets, adds some widgets) via `add`.
2. It generates a top-level window containing some more widgets

Unfortunately, adding to a `Flex` in step 1 appears to modify FLTK's `Fl_Group::current` variable. Thus, when generating the window in step 2, it is added to the modified `Fl_Group::current`.

My workaround right now is to call
```
unsafe { fltk_sys::group::Fl_Group_set_current(std::ptr::null_mut()); }
```
between step 1 and 2 in order to reset the current group.

So, I have two questions:

1. My impression from FLTK was that `Fl_Group::current` is modified only when constructing new groups, or when explicitly calling `begin` or `end`. When glancing over `Fl_Group.cxx` it appears that `Fl_Group::add` does **not** modify `Fl_Group::current`. So, I'm surprised to see that, for example, `Flex` actually does modify `Fl_Group::current` when in `Flex::add`. Is this intentional?
2. Would it make sense to expose `fltk_sys::group::Fl_Group_set_current` in `fltk-rs`?

**Comment by MoAlyousef** [comment]
I've exposed Group::set_current.
It seems the call to current happens in the widget's constructor, from the FLTK docs:
```
  The Fl_Widget constructor automatically does current()->add(widget) if this
  is not null. To prevent new widgets from being added to a group, call
  Fl_Group::current(0).
```
As you also noted, I don't see anything in Fl_Flex or Fl_Group code which touches `current` when adding a widget.
However, it seems the second Fl_Window constructor `Fl_Window::Fl_Window(int W, int H, const char *l)` modifies Fl_Group::current:
```cpp
Fl_Window::Fl_Window(int W, int H, const char *l) :
// fix common user error of a missing end() with current(0):
Fl_Group((Fl_Group::current(0),0), 0, W, H, l)
{
  pWindowDriver = Fl_Window_Driver::newWindowDriver(this);
  _Fl_Window();
  clear_visible();
}
```
If you have a test case, it would be helpful in trying to pinpoint the issue.

**Comment by abau** [comment]
> If you have a test case

In the following example, I would expect that both assertions hold, but the second fails, since adding to a `Flex` modifies `Fl_Group::current`:
```
use fltk::app::App;
use fltk::frame::Frame;
use fltk::group::{Group, Flex};
use fltk::prelude::*;
use fltk::window::Window;
use fltk::enums::Color;

fn main() {
    let app = App::default();
    let mut window_1 = Window::default().with_size(400, 400).center_screen();

    window_1.set_color(Color::Red);

    let mut flex = Flex::new(0, 0, 400, 400, "").row();

    Frame::default().with_label("frame 1");
    Frame::default().with_label("frame 2");

    flex.end();
    window_1.end();
    window_1.show();

    assert!(Group::try_current().is_none());

    flex.add(&Frame::default().with_label("frame 3"));

    assert!(Group::try_current().is_none());

    app.run().unwrap();
}
```
This leads to unexpected behavior when creating additional windows afterwards. In the following example, `window_2` is not visible.

```
use fltk::app::App;
use fltk::frame::Frame;
use fltk::group::{Group, Flex};
use fltk::prelude::*;
use fltk::window::Window;
use fltk::enums::Color;

fn main() {
    let app = App::default();
    let mut window_1 = Window::default().with_size(400, 400).center_screen();

    window_1.set_color(Color::Red);

    let mut flex = Flex::new(0, 0, 400, 400, "").row();

    Frame::default().with_label("frame 1");
    Frame::default().with_label("frame 2");

    flex.end();
    window_1.end();
    window_1.show();

    flex.add(&Frame::default().with_label("frame 3"));
    
    let mut window_2 = Window::default().with_size(200, 200).center_screen();

    window_2.set_color(Color::Blue);
    window_2.show();

    app.run().unwrap();
}
```
Only when adding
```
unsafe { fltk_sys::group::Fl_Group_set_current(std::ptr::null_mut()); }
```
before creating `window_2`, `window_2` actually becomes a visible top-level window.

**Comment by MoAlyousef** [comment]
Thanks for the repro. It was an issue with Flex::recalc(), I've pushed a fix on master.
