### ISSUE TITLE
error: linking with `x86_64-w64-mingw32-gcc` failed: exit code: 1

### ISSUE THREAD

**Issue by xxyClass** [fltk-rs/fltk-rs#1252]
I have installed GCC and cmack, But still report an error。

cargo run
   Compiling first v0.1.0 (D:\xxy\work\rust\first)
error: linking with `x86_64-w64-mingw32-gcc` failed: exit code: 1
  |
  = note: "x86_64-w64-mingw32-gcc" "-fno-use-linker-plugin" "-Wl,--dynamicbase" "-Wl,--disable-auto-image-base" "-m64" "-Wl,--high-entropy-va" "C:\\Users\\xy\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\self-contained\\crt2.o" "C:\\Users\\xy\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\rsbegin.o" "C:\\Users\\xy\\AppData\\Local\\Temp\\rustc5zoRFV\\symbols.o" "D:\\xxy\\work\\rust\\first\\target\\debug\\deps\\first-fc596f40636941fd.1ll6bzm0ksvx0qqz.rcgu.o" "D:\\xxy\\work\\rust\\first\\target\\debug\\deps\\first-fc596f40636941fd.3czrlb2mn64ayuge.rcgu.o" "D:\\xxy\\work\\rust\\first\\target\\debug\\deps\\first-fc596f40636941fd.4vxs3gp5nnpcppdn.rcgu.o" "D:\\xxy\\work\\rust\\first\\target\\debug\\deps\\first-fc596f40636941fd.4yocgd6iiys0hmrd.rcgu.o" "D:\\xxy\\work\\rust\\first\\target\\debug\\deps\\first-fc596f40636941fd.504fp0zkp6pen432.rcgu.o" "D:\\xxy\\work\\rust\\first\\target\\debug\\deps\\first-fc596f40636941fd.55hzhbz57g35isx0.rcgu.o" "D:\\xxy\\work\\rust\\first\\target\\debug\\deps\\first-fc596f40636941fd.symglw45pmfztkc.rcgu.o" "D:\\xxy\\work\\rust\\first\\target\\debug\\deps\\first-fc596f40636941fd.52ls76avhezj7460.rcgu.o" "-L" "D:\\xxy\\work\\rust\\first\\target\\debug\\deps" "-L" "D:\\xxy\\work\\rust\\first\\target\\debug\\build\\fltk-sys-712aed36b1adac6e\\out\\build" "-L" "D:\\xxy\\work\\rust\\first\\target\\debug\\build\\fltk-sys-712aed36b1adac6e\\out\\build\\Release" "-L" "D:\\xxy\\work\\rust\\first\\target\\debug\\build\\fltk-sys-712aed36b1adac6e\\out\\lib" "-L" "D:\\xxy\\work\\rust\\first\\target\\debug\\build\\fltk-sys-712aed36b1adac6e\\out\\lib64" "-L" "D:\\xxy\\work\\rust\\first\\target\\debug\\build\\fltk-sys-712aed36b1adac6e\\out\\lib\\Release" "-L" "D:\\xxy\\work\\rust\\first\\target\\debug\\build\\fltk-sys-712aed36b1adac6e\\out\\lib64\\Release" "-L" "C:\\Users\\xy\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib" "-Wl,-Bstatic" "D:\\xxy\\work\\rust\\first\\target\\debug\\deps\\libfltk-93f9ae475e11317a.rlib" "D:\\xxy\\work\\rust\\first\\target\\debug\\deps\\libttf_parser-a1cd21efedf2c370.rlib" "D:\\xxy\\work\\rust\\first\\target\\debug\\deps\\libcrossbeam_channel-64d68a06a63d350e.rlib" "D:\\xxy\\work\\rust\\first\\target\\debug\\deps\\libcrossbeam_utils-79fb76a70656d3ed.rlib" "D:\\xxy\\work\\rust\\first\\target\\debug\\deps\\libonce_cell-547cffbaff346388.rlib" "D:\\xxy\\work\\rust\\first\\target\\debug\\deps\\libcfg_if-a851f9bba14b8977.rlib" "D:\\xxy\\work\\rust\\first\\target\\debug\\deps\\libbitflags-5245d8dd85dc2c8a.rlib" "D:\\xxy\\work\\rust\\first\\target\\debug\\deps\\liblazy_static-2bde52d0977b3290.rlib" "D:\\xxy\\work\\rust\\first\\target\\debug\\deps\\libfltk_sys-ca720594a7c4cf12.rlib" "-Wl,--start-group" "C:\\Users\\xy\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libstd-286d92372824ad75.rlib" "C:\\Users\\xy\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libpanic_unwind-98fbfa7e7941eb44.rlib" "C:\\Users\\xy\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libobject-9ce2fc6f473084c9.rlib" "C:\\Users\\xy\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libmemchr-60c7a9ccebc1c0df.rlib" "C:\\Users\\xy\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libaddr2line-a6c791f82a11d981.rlib" "C:\\Users\\xy\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libgimli-82449fe6dba22989.rlib" "C:\\Users\\xy\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\librustc_demangle-a0bb6c42cb40e3b2.rlib" "C:\\Users\\xy\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libstd_detect-aff674fba5d55355.rlib" "C:\\Users\\xy\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libhashbrown-3acaef96bbb1962c.rlib" "C:\\Users\\xy\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libminiz_oxide-38836d23dc28fffc.rlib" "C:\\Users\\xy\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libadler-3e94f58c71461bb0.rlib" "C:\\Users\\xy\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\librustc_std_workspace_alloc-8694d78ac5d3c596.rlib" "C:\\Users\\xy\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libunwind-f971c060b6355776.rlib" "C:\\Users\\xy\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libcfg_if-cb8714f793b7f21c.rlib" "C:\\Users\\xy\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\liblibc-06ac00fc59f0c9ac.rlib" "C:\\Users\\xy\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\liballoc-67bebcf125a98a92.rlib" "C:\\Users\\xy\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\librustc_std_workspace_core-120164796f318db1.rlib" "C:\\Users\\xy\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libcore-c926020a7e02cde7.rlib" "-Wl,--end-group" "C:\\Users\\xy\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libcompiler_builtins-50eb72b9dd1763b8.rlib" "-Wl,-Bdynamic" "-lws2_32" "-lcomctl32" "-lgdi32" "-loleaut32" "-lole32" "-luuid" "-lshell32" "-ladvapi32" "-lcomdlg32" "-lwinspool" "-luser32" "-lkernel32" "-lodbc32" "-lgdiplus" "-ladvapi32" "-luserenv" "-lkernel32" "-lws2_32" "-lbcrypt" "-lgcc_eh" "-l:libpthread.a" "-lmsvcrt" "-lmingwex" "-lmingw32" "-lgcc" "-lmsvcrt" "-luser32" "-lkernel32" "-Wl,--nxcompat" "-nostartfiles" "-L" "C:\\Users\\xy\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib" "-L" "C:\\Users\\xy\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\self-contained" "-o" "D:\\xxy\\work\\rust\\first\\target\\debug\\deps\\first-fc596f40636941fd.exe" "-Wl,--gc-sections" "-no-pie" "-nodefaultlibs" "C:\\Users\\xy\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\rsend.o"
  = note: ld: cannot find -lgdiplus

error: could not compile `first` due to previous error

**Comment by MoAlyousef** [comment]
It seems your system lacks gdi+ 

You can try:
```toml
[dependencies]
fltk = { version = "1.3", features = ["no-gdiplus"] }
```
