### ISSUE TITLE
[BUG] Updating raw-window-handle to 0.5 was a breaking change

### ISSUE THREAD

**Issue by parasyte** [fltk-rs/fltk-rs#1285]
## Describe the bug

My weekly CI build just failed: https://github.com/parasyte/pixels/actions/runs/3029886487 It looks like the cause was a patch update to the `fltk` crate which now depends on `raw-window-handle` 0.5. rwh 0.5 is incompatible with 0.4 (which I am still using).

## To Reproduce

Build the `minimal-fltk` example in the `pixels` repo on any commit prior to pinning `fltk` to `=1.3.13`. E.g. https://github.com/parasyte/pixels/commit/881033c5c7f2944c05b93a0197310b7e6c430aae

Build instructions are [here](https://github.com/parasyte/pixels/tree/main/examples/minimal-fltk#running).

## Expected behavior

Patch SemVer updates should not break the public API, including dependency re-exports. There are a lot of recommendations and varying opinions on exactly how SemVer should be interpreted, but I think this is a clear example of why a patch should not change the public interface.

It might be a good idea to yank the patch and re-publish it as a minor update with breaking changes documented.

**Comment by MoAlyousef** [comment]
Thanks for the heads up and sorry for that.
I've yanked 1.3.14 and published 1.3.15 with the reverted changes. I'll wait to publish a minor update once the ecosystem catches up to rwh 0.5.

**Comment by MoAlyousef** [comment]
Hello again
I've added a rwh05 feature which allows building fltk against raw-window-handle version 0.5. I'm keeping the "raw-window-handle" feature at version 0.4 for back compat.
Hoping the raw-window-handle 0.5 api remains stable for a while.
