### ISSUE TITLE
[BUG] widget_extends does not implement WidgetExt

### ISSUE THREAD

**Issue by rongcuid** [fltk-rs/fltk-rs#1316]
## Describe the bug
I tried to make a custom widget suing `widget_extends!` macro. It does not implement `WidgetExt`.

## To Reproduce
```rust
pub struct CustomWidget {
    root: group::Flex,
}

impl CustomWidget {
    pub fn new() -> Self {
        let mut root = group::Flex::default().row();
        root.end();
        Self {
            root,
        }
    }
}

widget_extends!(CustomWidget, group::Flex, root);

```

If I try to so something like `flex.set_size(&custom, 10)`, there is an error saying `WidgetExt` is not implemented.

## Expected behavior
Expect `WidgetExt` to be implemented for `CustomWidget`.

## Desktop info
 - OS: Fedora 36

**Comment by MoAlyousef** [comment]
Thanks. I've added more to the docs.
