### ISSUE TITLE
[BUG] HoldBrowser.insert() doesn't seem to work anymore

### ISSUE THREAD

**Issue by mark-summerfield** [fltk-rs/fltk-rs#1343]
In my [CharFind](https://github.com/mark-summerfield/charfind) application (as you can see from the screenshot on its github page) it shows matching characters in a HoldBrowser. I've been away from fltk-rs programming for a while and now I've come back I've found that the HoldBrowser shows _nothing_ even though the code hasn't changed. I looked through the change logs but didn't spot anything that gave me a clue.

**Comment by MoAlyousef** [comment]
Hi
It was because of a redundant check in BrowserExt::insert. FLTK already perform checks when inserting so I've removed it.
Can you test against the git repo?

**Comment by mark-summerfield** [comment]
Hi,
I did a clean build with these fltk dependencies:
```
[dependencies.fltk]
version = "^1.3"
features = [ "no-pango",]
git = "https://github.com/fltk-rs/fltk-rs"
```
And it works fine on Linux (Debian 11 Xfce).
Thanks.
