### ISSUE TITLE
[BUG] BrowseMultiFile dialog returns wrong filenames on Linux 

### ISSUE THREAD

**Issue by yveszoundi** [fltk-rs/fltk-rs#1346]
## Describe the bug
In `1.3.28`, a [FileDialog](https://docs.rs/fltk/latest/fltk/dialog/struct.FileDialog.html) with type [BroseMultiFile](https://docs.rs/fltk/latest/fltk/dialog/enum.FileDialogType.html#variant.BrowseMultiFile) returns wrong [filenames](https://docs.rs/fltk/latest/fltk/dialog/struct.FileDialog.html#method.filenames) results under Linux.

A single path with pipe delimiters is returned for all selected paths, instead of returning multiple file paths:
`/usr/share/ghostscript/9.55.0/lib/stcolor.ps|/usr/share/foo2qpdl/crd/black-text.ps`

## To Reproduce
Create a new project with fltk `1.3.28` as dependency with the `fltk-bundled` feature set.
```toml
fltk = { version = "1.3.28", features = ["fltk-bundled"] }
```

Create a `main.rs` file with the following contents

```rust
use fltk::{
    app,
    dialog,
    button,
    frame,
    prelude::*,
    window,
};
use std::path::PathBuf;

fn main() {
    let app = app::App::default();

    let mut wind = window::Window::default().with_size(160, 200).with_label("BrowseMultifileBug on Linux in 1.3.28");
    let mut frame = frame::Frame::default()
        .with_size(300, 40)
        .center_of(&wind);
    frame.set_label_size(20);
    let mut but_inc = button::Button::default()
        .size_of(&frame)
        .above_of(&frame, 0)
        .with_label("Browse...");
    wind.end();
    wind.show();

    but_inc.set_callback({
        move |_| {
            let mut dlg = dialog::FileDialog::new(dialog::FileDialogType::BrowseMultiFile);
            dlg.set_title("Select multiple files");
            dlg.show();

            let files: Vec<PathBuf> = dlg.filenames()
                .iter()
                .cloned()
                .collect();

            println!("File count: {}", files.len());

            for file in files {
                println!("File: {}", file.display());
            }
        }
    });

    app.run().unwrap();
}
```

Multiple files get printed as one file  with pipe ("|") as a delimiter.

```
File count: 1
File: /usr/share/ghostscript/9.55.0/lib/stcolor.ps|/usr/share/foo2qpdl/crd/black-text.ps
```

## Expected behavior

Multiple files should be returned by `filenames` (just as in `1.3.20`), and I should see 2 files printed.
With the FLTK version frozen to 1.3.20 (`=1.3.20` in `Cargo.toml`), I observe correct results

```
File count: 2
File: /usr/share/ghostscript/9.55.0/lib/stcolor.ps
File: /usr/share/foo2qpdl/crd/black-text.ps
```

## Screenshots
_Not necessarily useful_ 

## Desktop info
 - OS: Ubuntu jammy (amd64)
 - Desktop environment: [dwm window manager](https://dwm.suckless.org/)
 - fltk-rs `1.3.28` (`fltk-bundled` feature set)

## Additional info

I was able to confirm that the issue doesn't happen on Mac OS Ventura `13.2`. I don't know if MS Windows is impacted.

The regression seems to have been introduced in `1.3.25` but I didn't notice (I stuck with `1.3.20` to keep compatibility with Mac OS 11, as my builds were failing for `macos-11` on GitHub actions, apparently all recent `fltk-rs` releases require at least Mac OS 12).

## Build failures

Not applicable

**Comment by MoAlyousef** [comment]
I think this is an upstream issue when FLTK switched to the Zenity file chooser. I'll try to repro in C++ and open an issue in FLTK.
Regarding the macos requirement, fltk-rs will still run on older macs. The fltk-bundled feature is built on macos-12 in CI since macos-11 was deprecated. You can try building without the feature, or you can enable it while overriding CFLTK_BUNDLE_DIR to point to a directory with the prebuilt FLTK and cfltk libs.

**Comment by yveszoundi** [comment]
Thanks, I'm glad to hear that `fltk-rs` can still run on older macs. I think that nowadays most people keep up with version upgrades, unless they have strong reasons not to do so.

I suspected that it could be an upstream issue after taking a brief look at the code, thank you for confirming that.

**Comment by yveszoundi** [comment]
Just confirming that the latest master branch changes resolve this issue (commit https://github.com/fltk-rs/fltk-rs/commit/478e83fa8531b58aa6e7c287a9a39fc7eb20b5d0).

I made the following changes in my `Cargo.toml` to validate the bug fix on Linux.

```toml
fltk = { git = "https://github.com/fltk-rs/fltk-rs", branch = "master" }
```
