### ISSUE TITLE
[BUG] Tile does not always redraw/expand when window dragged or maximized

### ISSUE THREAD

**Issue by mark-summerfield** [fltk-rs/fltk-rs#1348]
Hi Mo,
When I run your tiletest eg or my variation of it that followed and maximize the window or simple drag the window corner to make the window larger, the tile and widgets within it automatically expand to fill the space -- exactly as you'd want & expect.
However, with my real application (which I can't share because it is commercial) this doesn't happen at all on Linux and only once have I seen it on Windows. Instead a large grey area is left on the right. If you then drag the rightmost tile handle all the way to the right edge and then back, the problem is fixed. But for end-users it just looks like a bug.
Is there a workaround for this?
Thanks.

**Comment by MoAlyousef** [comment]
Hmm I'm not sure. 
If the tile is inside a Scroll for example, the Scroll will override the resizing of the tile (as it does for everything inside it). If so, you can place the tile inside a Flex for example. 
Do you have any resize_callback methods or do you somewhere handle the Resize event?
You can probably set the tile to be the resizable widget of the window:
```
window.resizable(&tile);
```

**Comment by mark-summerfield** [comment]
Setting the tile resizable made no difference.
Also, the problem isn't reliably reproducable.
Actually, I think the problem wasn't fltk-rs at all but rather a video driver I was using: sorry to bother you!
