### ISSUE TITLE
Would it be possible to add support for the Tabs::handle_overflow() method?

### ISSUE THREAD

**Issue by mark-summerfield** [fltk-rs/fltk-rs#1353]
The Tabs::handle_overflow() method would be useful to me:
https://fltk.gitlab.io/fltk/classFl__Tabs.html#a9f6136aad01a797b16638223672ae675

**Comment by MoAlyousef** [comment]
I've added Tabs::handle_overflow in the latest change a few moments ago.
It requires a TabsOverflow enum value:
```rust
tabs.handle_overflow(TabsOverflow::Compress);
```

**Comment by mark-summerfield** [comment]
Thanks, I'm using Pulldown & it works great :-)
