### ISSUE TITLE
Possibility to establish  automatically the name of file in dialog::FileDialogType::BrowseSaveFile

### ISSUE THREAD

**Issue by lizzard88** [fltk-rs/fltk-rs#1357]
Hello, Mo! Thanks a lot for you great job!

I use dialog::FileDialogType::BrowseSaveFile for selection of directory, but name of file is generated by soft and it would be great if the PathBuf was introduced into input line automatically.

pub fn save_file_as(&mut self) -> Result<bool, Box<dyn error::Error>> {
        let mut dlg = dialog::FileDialog::new(dialog::FileDialogType::BrowseSaveFile);
        dlg.set_option(dialog::FileDialogOptions::SaveAsConfirm);
        dlg.show();
        if dlg.filename().to_string_lossy().to_string().is_empty() {
            dialog::alert(center().0 - 200, center().1 - 100, "Please specify a file!");
            return Ok(false);
        }
        self.buf.save_file(&dlg.filename())?;

**Comment by MoAlyousef** [comment]
Hello 
Thanks for the kind words. 

Can you try using `dlg.set_preset_file("yourfilename");` before showing the dialog. 
I can’t test currently since I’m traveling. 
This currently takes a `&str` but I can probably change this to take a Path using `AsRef<Path>` without breaking user code.

**Comment by lizzard88** [comment]
> Hello Thanks for the kind words.
> 
> Can you try using `dlg.set_preset_file("yourfilename");` before showing the dialog. I can’t test currently since I’m traveling. This currently takes a `&str` but I can probably change this to take a Path using `AsRef<Path>` without breaking user code.


I have tried 2 variants:

                                let file_name = (lines.clone()).next().unwrap();				
				let mut dlg = dialog::FileDialog::new(dialog::FileDialogType::BrowseSaveFile);
				dlg.set_option(dialog::FileDialogOptions::SaveAsConfirm);
				dlg.show();
				let path_directory = dlg.filename().to_string_lossy().to_string();
				let path = path_directory + file_name + &".txt".to_string();
               			dlg.set_preset_file(&file_name);
				let filename = dlg.filename();
				buf.save_file(&filename).expect("Could not save file");

At this first variant the input line is empty and to save file I have to input some symbols wich become prefix of saved file after the Save button is pressed.


				let file_name = (lines.clone()).next().unwrap();
				let mut dlg = dialog::FileDialog::new(dialog::FileDialogType::BrowseSaveFile);
				dlg.set_option(dialog::FileDialogOptions::SaveAsConfirm);
				dlg.show();
				let mut path = PathBuf::new();
				path.push(&dlg.filename());
				path.push(&file_name);
				path.set_extension("txt");
				let filename = dlg.filename();
				buf.save_file(&filename).expect("Could not save file");

At this second variant the input line is also empty, but I can input "/" symbol to save file with correct file name after the  Save button is pressed..

The desired solution is automatic entry of full Path with predifined name of file to save it.

**Comment by MoAlyousef** [comment]
Can you try:
```rust
let file_name = (lines.clone()).next().unwrap();				
let mut dlg = dialog::FileDialog::new(dialog::FileDialogType::BrowseSaveFile);
dlg.set_option(dialog::FileDialogOptions::SaveAsConfirm);
dlg.set_preset_file(&file_name);
dlg.show();
let filename = dlg.filename();
buf.save_file(&filename).expect("Could not save file");
```

**Comment by lizzard88** [comment]
It works fine.
Thank you very much!
