### ISSUE TITLE
[BUG] Offscreen object is not created and always none on Windows and MacOS

### ISSUE THREAD

**Issue by Postrediori** [fltk-rs/fltk-rs#1375]
## Describe the bug
Creation of `Offscreen` object always returns `None`. The following code always throws runtime exception on Windows and macOS:

```
use fltk::{*};

fn main() {
  ...
  let offs = Offscreen::new(WIDTH, HEIGHT).unwrap();
  ...
}
```

This code will throw exception in `.unwrap()`:

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src\main.rs:33:62
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

## To Reproduce
* Create empty project
* Copy 'RustyPainter' rource code from the book; https://fltk-rs.github.io/fltk-book/Drawing.html#offscreen-drawing
* Specify dependency
```
fltk = "1"
```
* Build the project and run the binary

Adding a call of `fl_open_display()` in the beginning does not fix the runtime exception:
```
unsafe {
  fl_open_display();
}
```

Changing dependency options in `.toml` project file didn't affect the issue:
* bundled binaries (`fltk = { version = "1", features = ["fltk-bundled"] } `)
* specific crate option (`fltk = { version = "1.3.33"}`)

## Expected behavior
An application starts normally as it happens on Linux. 'RustyPainter' code runs corerctly on Fedora 37 x64:

![Fedora 37.png](https://user-images.githubusercontent.com/856993/226173034-725ae3c1-7869-4f08-b4ba-a7ba1ccc7e10.png)

## Screenshots

Exception backtrace on Windows 10 Pro x64:

![windows 10 pro x64.png](https://user-images.githubusercontent.com/856993/226172030-e9df6832-f15f-4078-a6f6-56ca0f60fcc4.png)

The same exception on macOS Catalina 10.15.7:

![macOS 10.15.7.png](https://user-images.githubusercontent.com/856993/226173083-3521dc38-382a-4613-9be7-2f4e8cba6de0.png)

## Desktop info
General compiler info:
 - Rust & Cargo version: 1.68
 - fltk-rs version: 1.3.33

On Windows this was checked on:
 - OS: Windows 10 Pro x64 21H2, Windows 11 Pro
 - C/C++ compiler: MS Visual Studio 2019, 16.11

On macOS this was checked on:
 - OS: macOS Catalina 10.15.7

## Additional info
This is not an issue for [cfltk](https://github.com/MoAlyousef/cfltk) that the rust crate is based on. `Fl_create_offscreen` returns correct object on all platforms.

**Comment by MoAlyousef** [comment]
Thanks for the report. This was due to improper checks of the graphics context which should be fixed in master. 
Can you try:
```toml
[dependencies]
fltk = { git = "https://github.com/fltk-rs/fltk-rs" }
```

**Comment by Postrediori** [comment]
Using the module from git seems to work. Thanks

![Screenshot 2023-03-19 at 14 39 51](https://user-images.githubusercontent.com/856993/226178071-b5dbeb89-e4bf-49e7-aef8-10685629fc55.png)

![windows](https://user-images.githubusercontent.com/856993/226178080-101913b1-57b2-4cc1-be81-a5a95b7172c4.PNG)

**Comment by MoAlyousef** [comment]
The latest release now contains the fix
