### ISSUE TITLE
Inconsistent font at index 0 between related functions

### ISSUE THREAD

**Issue by correabuscar** [fltk-rs/fltk-rs#1377]
## Describe the bug
this sets the wrong font: `frame.set_label_font( enums::Font::by_index(0) );`
it uses the font that was set by `app::set_font(enums::Font::CourierBold);`
because `enums::Font::by_index(0)` returns the wrong font...

## To Reproduce

I made a project that shows the bugs: https://github.com/correabuscar/font_selection_bugs_for_fltk-rs
but basically, these are different and are supposed to be the same(i believe):
```
    let fonts = app::fonts();
    let index = 0;
    ...
    println!("First font is(these should all be equal,right?): [{:?}] [{}] [{}] [{}]",
             
             enums::Font::by_index(index),
             fonts[index],
             app::fonts()[index], // just making sure this is still fonts[index], and it is !
             app::get_font_names()[index],

    );
```
When using index 0, you get something like:
```
First font is(these should all be equal,right?): [Helvetica] [ Arial] [ Arial] [BCourier New]
```
when using index 2, you get:
```
First font is(these should all be equal,right?): [HelveticaItalic] [IArial] [IArial] [IArial]
```

## Expected behavior
These should all be the same font:
```
app::fonts()[0]
enums::Font::by_index(0)
app::get_font_names()[0]
```

## Screenshots
i forgot, but you can `cargo run` this: https://github.com/correabuscar/font_selection_bugs_for_fltk-rs
and see two sequential windows pop up, then exit.

## Desktop info
 - OS: Windows 11 x64 
 - Version i dno, 22H2 ?

## Additional info
not using `let app = app.load_system_fonts();` changes the behavior somewhat.

## Build failures
If you're having build difficulties, please check:
- The required dependencies for your platform, mentioned in the [README](https://github.com/fltk-rs/fltk-rs#dependencies).
- The [FAQ](https://github.com/fltk-rs/fltk-rs/blob/master/FAQ.md). 
- That you have a working CMake and C++11 compiler. At least CMake should be in your PATH. 
- That your Rust's target arch is similar to your C/C++ target arch. 
- The [Setup chapter](https://fltk-rs.github.io/fltk-book/Setup.html). 

Otherwise you can open a github discussion [here](https://github.com/fltk-rs/fltk-rs/discussions) describing your difficulties, along with the output of:
- `cargo install fltk-check-env && fltk-check-env`
- `cargo build -vv`

Please only open a bug report if the repo/crate used to build and currently fails. The github-actions CI already checks for the 3 major desktop platforms. Also include the outputs of:
 - `cargo build -vv`
 - `rustup toolchain list`
 - CMake error and log files

Also remember if you're git cloning the fltk-rs repo, to run `git submodule update --init --recursive` since this repo uses git submodules.

**Comment by MoAlyousef** [comment]
These are effectively not the same. 
Font::by_index is the value representation of the Font enum. app::fonts() is the default font names for an application which are loaded by default by FLTK unless using load_system_fonts. app::get_font_names gives you the fonts made available by the OS to your application. 

This could use some better documentation, but effectively they differ between use cases.
