### ISSUE TITLE
[BUG] Passing the flag -C target-feature=+crt-static will make the build fail with explicitly specified triple

### ISSUE THREAD

**Issue by vstojkovic** [fltk-rs/fltk-rs#1379]
When passing `-C target-feature=+crt-static` either via `RUSTFLAGS` environment variable or via `.cargo/config.toml' file, building a project that depends on `fltk-sys` will fail if the target triple is specified explicitly:
```
cargo build --release --target x86_64-pc-windows-msvc
```

However, the build will *succeed* if the target triple is not specified:
```
cargo build --release
```

## To Reproduce

I've created a small repo to allow you to easily reproduce the problem: https://github.com/vstojkovic/fltk-link-bug-repro

Running `build-without-target.bat` should result in a successful build, and running `build-with-target.bat` should fail.

## Expected behavior
Considering that I'm not doing cross-compilation, the build should either succeed or fail consistently, regardless of whether the target triple was specified.

## Desktop info
 - OS: Windows 10 x64
 - fltk-rs version: 1.3.34
 - CMake version: 3.19.8
 - MSVC version: either 2019 or 2022 (tested with both, same results)

## Build failures
Please find attached the error message from the linker.
[linker-error-msg.txt](https://github.com/fltk-rs/fltk-rs/files/11058304/linker-error-msg.txt)

**Comment by vstojkovic** [comment]
By running cargo with `--verbose` flag, I've noticed that the flag is not being passed to the build script when the target triple is explicitly specified.

Here's the `rustc` invocation *without* `--target`:
```
rustc --crate-name build_script_main --edition=2018 C:\Users\CodeMage\.cargo\registry\src\github.com-1ecc6299db9ec823\fltk-sys-1.3.34\build/main.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debug-assertions=off --cfg "feature=\"default\"" -C metadata=7476b54cb66187bf -C extra-filename=-7476b54cb66187bf --out-dir E:\Projects\Experiments\fltk-link-bug-repro\target\release\build\fltk-sys-7476b54cb66187bf -L dependency=E:\Projects\Experiments\fltk-link-bug-repro\target\release\deps --extern cmake=E:\Projects\Experiments\fltk-link-bug-repro\target\release\deps\libcmake-e92ed122b1fa343c.rlib --cap-lints allow -Ctarget-feature=+crt-static
```

And here's the one used when the target is specified:
```
rustc --crate-name build_script_main --edition=2018 C:\Users\CodeMage\.cargo\registry\src\github.com-1ecc6299db9ec823\fltk-sys-1.3.34\build/main.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debug-assertions=off --cfg "feature=\"default\"" -C metadata=7476b54cb66187bf -C extra-filename=-7476b54cb66187bf --out-dir E:\Projects\Experiments\fltk-link-bug-repro\target\release\build\fltk-sys-7476b54cb66187bf -L dependency=E:\Projects\Experiments\fltk-link-bug-repro\target\release\deps --extern cmake=E:\Projects\Experiments\fltk-link-bug-repro\target\release\deps\libcmake-e92ed122b1fa343c.rlib --cap-lints allow
```

**Comment by MoAlyousef** [comment]
I'm not sure why cargo doesn't pass crt-static when specifying the target. Could be a cargo issue?
https://github.com/rust-lang/cargo/issues/4423

**Comment by MoAlyousef** [comment]
Personally I’m not sure how fltk-rs could work around the issue, so a PR would be welcome.
