### ISSUE TITLE
[BUG] frame.set_image cannot render image at all.

### ISSUE THREAD

**Issue by AllenDang** [fltk-rs/fltk-rs#1384]
## Describe the bug
Here is the minimal code to repo the bug
```rust
use fltk::{prelude::*, *};
use fltk_theme::{color_themes, ColorTheme, WidgetScheme};

mod mainview {
    fl2rust_macro::include_ui!("gui/mainview.fl");
}

mod img;

fn main() {
    let app = app::App::default();
    let theme = ColorTheme::new(color_themes::BLACK_THEME);
    theme.apply();
    let scheme = WidgetScheme::new(fltk_theme::SchemeType::Fluent);
    scheme.apply();

    let ui = mainview::UserInterface::make_window();
    ui.win.center_screen();

    let img = img::read_image("/Users/allen/Downloads/InFunIcon.png")
        .unwrap()
        .to_rgba8();

    let mut frame = ui.frame_viewer;

    // Option1: I can see colors, even it's incorrect
    // fltk::draw::draw_rgba(&mut frame, &img).unwrap();

    // Option2: No thing is drawn
    let s_img = fltk::image::RgbImage::new(
        &img,
        img.width() as i32,
        img.height() as i32,
        enums::ColorDepth::Rgba8,
    )
    .unwrap();

    frame.set_image(Some(s_img));

    app.run().unwrap();
}
```

I loaded a png from file system, and want to draw it to a frame, with `set_image` nothing is drawn, with `draw_rgba` at least I can see some pixels, what do i do wrong here?

## To Reproduce
Loaded image is not rendered.

## Expected behavior
Image could be rendered.

## Screenshots
![截屏2023-04-10 21 10 17](https://user-images.githubusercontent.com/18550/230907556-dbf467c7-a7ac-4202-b26f-504a4f9f95f5.png)
![截屏2023-04-10 21 10 03](https://user-images.githubusercontent.com/18550/230907567-80f899c6-f9b4-459b-a036-1df38dfb7edf.png)

## Desktop info
 - OS: macOS v13
 - Version 1.4.0

**Comment by MoAlyousef** [comment]
Can you share the implementation of img read_image and to_rgba8. 

You can also try different colordepths when creating the RgbImage.

**Comment by AllenDang** [comment]
@MoAlyousef Thing is, even if I load the image via SharedImage, it still cannot be rendered correctly.
```rust
use fltk::{prelude::*, *};
use fltk_theme::{color_themes, ColorTheme, WidgetScheme};

mod mainview {
    fl2rust_macro::include_ui!("gui/mainview.fl");
}

mod img;

fn main() {
    let app = app::App::default();
    let theme = ColorTheme::new(color_themes::BLACK_THEME);
    theme.apply();
    let scheme = WidgetScheme::new(fltk_theme::SchemeType::Fluent);
    scheme.apply();

    let ui = mainview::UserInterface::make_window();
    ui.win.center_screen();

    let mut frame = ui.frame_viewer;

    // Option3: Use fltk's shared image to load the image
    let img = fltk::image::SharedImage::load("/Users/allen/Downloads/InFunIcon.png").unwrap();
    frame.set_image(Some(img));

    app.run().unwrap();
}
```

Here is the result
![截屏2023-04-11 09 56 00](https://user-images.githubusercontent.com/18550/231035588-44e6966c-b537-4736-b04b-980c708e0131.png)

**Comment by MoAlyousef** [comment]
Do other png images work? How about jpg images?

**Comment by AllenDang** [comment]
@MoAlyousef Other png images and jpg images still don't work.

**Comment by MoAlyousef** [comment]
I haven’t checked whether the fltk-theme crate might be causing such an issue. I’ll investigate tomorrow. 

If you pin to previous version of fltk and fltk-theme does the issue resolve?

**Comment by AllenDang** [comment]
@MoAlyousef I pinned to fltk-rs 1.3 and fltk-theme 0.4, issue remains.
Here is my cargo.toml
```toml
[package]
name = "img_inspector"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fl2rust-macro = "0.5.12"
fltk = "1.3"
fltk-theme = "0.4"
image = { version = "0.24.6", features = [
  "gif",
  "jpeg",
  "ico",
  "png",
  "pnm",
  "tga",
  "tiff",
  "webp",
  "bmp",
  "hdr",
  "dxt",
  "dds",
  "farbfeld",
  "jpeg_rayon",
  "openexr",
  "qoi",
  "webp",
  "webp-encoder",
] }
memmap2 = "0.5.10"
```

**Comment by MoAlyousef** [comment]
I'm not sure what the issue is. I can't reproduce with macos 12.6 and fltk 1.4 and fltk-theme 0.7

**Comment by MoAlyousef** [comment]
Maybe you can also post the content of the mainview.fl file?

**Comment by MoAlyousef** [comment]
I can’t test right now, but what if you remove the `labeltype NO_LABEL`?
