### ISSUE TITLE
Compilation error after manipulation with GNU compilers

### ISSUE THREAD

**Issue by lizzard88** [fltk-rs/fltk-rs#1385]
Windows 8.1
Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\Sergey\.rustup
stable-x86_64-pc-windows-msvc (default)
rustc 1.68.2 (9eb3afe9e 2023-03-27)

I've the project that was normally compiled before my experiment with GNU compilers.

Now trying to recompile project, but there is folllowing problem, I can not settle:

PS D:\1-temp\rust\osqiloc> cargo r
   Compiling autocfg v1.1.0
   Compiling cfg-if v1.0.0
   Compiling version_check v0.9.4
   Compiling typenum v1.15.0
   Compiling generic-array v0.14.6
   Compiling winapi v0.3.9
   Compiling proc-macro2 v1.0.47
   Compiling quote v1.0.21
   Compiling unicode-ident v1.0.5
   Compiling scopeguard v1.1.0
   Compiling syn v1.0.105
   Compiling num-traits v0.2.15
   Compiling crossbeam-utils v0.8.14
   Compiling semver-parser v0.7.0
   Compiling semver v0.9.0
   Compiling num-integer v0.1.45
   Compiling libc v0.2.137
   Compiling rustc_version v0.2.3
   Compiling memoffset v0.7.1
   Compiling crossbeam-epoch v0.9.13
   Compiling getrandom v0.2.8
   Compiling cpufeatures v0.2.5
   Compiling crossbeam-channel v0.5.6
   Compiling lock_api v0.4.9
   Compiling windows_x86_64_msvc v0.42.0
   Compiling num_cpus v1.14.0
   Compiling winapi-build v0.1.1
   Compiling kernel32-sys v0.2.2
   Compiling crypto-common v0.1.6
   Compiling block-buffer v0.10.3
   Compiling num-iter v0.1.43
   Compiling rayon-core v1.10.1
   Compiling memchr v2.5.0
   Compiling adler v1.0.2
   Compiling maybe-uninit v2.0.0
   Compiling cc v1.0.77
   Compiling crc32fast v1.3.2
   Compiling block-padding v0.2.1
   Compiling cmake v0.1.50
   Compiling winapi-util v0.1.5
   Compiling miniz_oxide v0.6.2
   Compiling digest v0.10.6
   Compiling crossbeam-deque v0.8.2
   Compiling num-bigint v0.4.3
   Compiling ahash v0.7.6
   Compiling futures-core v0.3.25
   Compiling tinyvec_macros v0.1.0
   Compiling opaque-debug v0.3.0
   Compiling winapi v0.2.8
   Compiling tinyvec v1.6.0
   Compiling sha2 v0.10.6
   Compiling fltk-sys v1.3.22
   Compiling same-file v1.0.6
   Compiling block-buffer v0.9.0
   Compiling pin-project-internal v1.0.12
   Compiling parking_lot_core v0.6.2
   Compiling cipher v0.3.0
   Compiling digest v0.9.0
   Compiling num-rational v0.4.1
   Compiling smallvec v1.10.0
   Compiling byteorder v1.4.3
   Compiling serde_derive v1.0.148
   Compiling either v1.8.0
   Compiling once_cell v1.17.1
   Compiling bitflags v1.3.2
   Compiling rayon v1.6.0
   Compiling thread-id v2.0.0
   Compiling pin-project v1.0.12
   Compiling flate2 v1.0.25
   Compiling walkdir v2.3.2
   Compiling smallvec v0.6.14
The following warnings were emitted during compilation:

warning: Could not find invokable ninja!

error: failed to run custom build command for `fltk-sys v1.3.22`

Caused by:
  process didn't exit successfully: `D:\1-temp\rust\osqiloc\target\debug\build\fltk-sys-3f692b066f67ecee\build-script-ma
in` (exit code: 101)
  --- stdout
  cargo:rerun-if-changed=build/android.rs
  cargo:rerun-if-changed=build/bundled.rs
  cargo:rerun-if-changed=build/link.rs
  cargo:rerun-if-changed=build/main.rs
  cargo:rerun-if-changed=build/source.rs
  cargo:rerun-if-changed=build/utils.rs
  cargo:rerun-if-env-changed=CC
  cargo:rerun-if-env-changed=CXX
  cargo:rerun-if-env-changed=CFLTK_TOOLCHAIN
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=CFLTK_WAYLAND_ONLY
  cargo:rerun-if-env-changed=CFLTK_GENERATE_BUNDLE_DIR
  cargo:rerun-if-changed=cfltk/CMakeLists.txt
  cargo:rerun-if-changed=cfltk/include/cfl.h
  cargo:rerun-if-changed=cfltk/include/cfl_widget.h
  cargo:rerun-if-changed=cfltk/include/cfl_group.h
  cargo:rerun-if-changed=cfltk/include/cfl_input.h
  cargo:rerun-if-changed=cfltk/include/cfl_window.h
  cargo:rerun-if-changed=cfltk/include/cfl_button.h
  cargo:rerun-if-changed=cfltk/include/cfl_box.h
  cargo:rerun-if-changed=cfltk/include/cfl_menu.h
  cargo:rerun-if-changed=cfltk/include/cfl_dialog.h
  cargo:rerun-if-changed=cfltk/include/cfl_valuator.h
  cargo:rerun-if-changed=cfltk/include/cfl_browser.h
  cargo:rerun-if-changed=cfltk/include/cfl_misc.h
  cargo:rerun-if-changed=cfltk/include/cfl_text.h
  cargo:rerun-if-changed=cfltk/include/cfl_image.h
  cargo:rerun-if-changed=cfltk/include/cfl_draw.h
  cargo:rerun-if-changed=cfltk/include/cfl_table.h
  cargo:rerun-if-changed=cfltk/include/cfl_surface.h
  cargo:rerun-if-changed=cfltk/include/cfl_printer.h
  cargo:rerun-if-changed=cfltk/include/cfl_utils.h
  cargo:rerun-if-changed=cfltk/include/cfl_macros.h
  cargo:rerun-if-changed=cfltk/include/cfl_lock.h
  cargo:rerun-if-changed=cfltk/include/cfl_widget.hpp
  cargo:rerun-if-changed=cfltk/src/cfl_lock.cpp
  cargo:rerun-if-changed=cfltk/src/cfl_new.cpp
  cargo:rerun-if-changed=cfltk/src/cfl.cpp
  cargo:rerun-if-changed=cfltk/src/cfl_widget.cpp
  cargo:rerun-if-changed=cfltk/src/cfl_group.cpp
  cargo:rerun-if-changed=cfltk/src/cfl_window.cpp
  cargo:rerun-if-changed=cfltk/src/cfl_button.cpp
  cargo:rerun-if-changed=cfltk/src/cfl_box.cpp
  cargo:rerun-if-changed=cfltk/src/cfl_menu.cpp
  cargo:rerun-if-changed=cfltk/src/cfl_dialog.cpp
  cargo:rerun-if-changed=cfltk/src/cfl_valuator.cpp
  cargo:rerun-if-changed=cfltk/src/cfl_browser.cpp
  cargo:rerun-if-changed=cfltk/src/cfl_misc.cpp
  cargo:rerun-if-changed=cfltk/src/cfl_text.cpp
  cargo:rerun-if-changed=cfltk/src/cfl_image.cpp
  cargo:rerun-if-changed=cfltk/src/cfl_input.cpp
  cargo:rerun-if-changed=cfltk/src/cfl_draw.cpp
  cargo:rerun-if-changed=cfltk/src/cfl_table.cpp
  cargo:rerun-if-changed=cfltk/src/cfl_tree.cpp
  cargo:rerun-if-changed=cfltk/src/cfl_surface.cpp
  cargo:rerun-if-changed=cfltk/src/cfl_printer.cpp
  cargo:rerun-if-changed=cfltk/src/cfl_font.cpp
  cargo:rerun-if-changed=cfltk/src/cfl_utils.cpp
  cargo:rerun-if-changed=cfltk/src/cfl_nswindow.m
  cargo:rerun-if-changed=cfltk/fltk.patch
  cargo:warning=Could not find invokable ninja!
  CMAKE_TOOLCHAIN_FILE_x86_64-pc-windows-msvc = None
  CMAKE_TOOLCHAIN_FILE_x86_64_pc_windows_msvc = None
  HOST_CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_GENERATOR_x86_64-pc-windows-msvc = None
  CMAKE_GENERATOR_x86_64_pc_windows_msvc = None
  HOST_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  CMAKE_PREFIX_PATH_x86_64-pc-windows-msvc = None
  CMAKE_PREFIX_PATH_x86_64_pc_windows_msvc = None
  HOST_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_x86_64-pc-windows-msvc = None
  CMAKE_x86_64_pc_windows_msvc = None
  HOST_CMAKE = None
  CMAKE = None
  running: "cmake" "C:\\Users\\Sergey\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\fltk-sys-1.3.22\\cfltk" "-G"
"Visual Studio 17 2022" "-Thost=x64" "-Ax64" "-DOPTION_USE_SYSTEM_LIBPNG=OFF" "-DOPTION_USE_SYSTEM_LIBJPEG=OFF" "-DOPTIO
N_USE_SYSTEM_ZLIB=OFF" "-DCFLTK_LINK_IMAGES=ON" "-DOpenGL_GL_PREFERENCE=GLVND" "-DOPTION_USE_GL=OFF" "-DCFLTK_USE_OPENGL
=OFF" "-DOPTION_USE_WAYLAND=OFF" "-DCFLTK_SINGLE_THREADED=OFF" "-DCMAKE_EXPORT_COMPILE_COMMANDS=ON" "-DCFLTK_CARGO_BUILD
=ON" "-DFLTK_BUILD_EXAMPLES=OFF" "-DFLTK_BUILD_TEST=OFF" "-DFLTK_BUILD_FLUID=OFF" "-DOPTION_LARGE_FILE=ON" "-DOPTION_USE
_THREADS=ON" "-DOPTION_BUILD_HTML_DOCUMENTATION=OFF" "-DOPTION_BUILD_PDF_DOCUMENTATION=OFF" "-DCMAKE_INSTALL_PREFIX=D:\\
1-temp\\rust\\osqiloc\\target\\debug\\build\\fltk-sys-ea2bcccc5de0dcf9\\out" "-DCMAKE_C_FLAGS= -nologo -MD -Brepro" "-DC
MAKE_C_FLAGS_RELEASE= -nologo -MD -Brepro" "-DCMAKE_CXX_FLAGS= -nologo -MD -Brepro" "-DCMAKE_CXX_FLAGS_RELEASE= -nologo
-MD -Brepro" "-DCMAKE_ASM_FLAGS= -nologo -MD -Brepro" "-DCMAKE_ASM_FLAGS_RELEASE= -nologo -MD -Brepro" "-DCMAKE_BUILD_TY
PE=Release"

  --- stderr
  error: patch failed: src/Fl_win32.cxx:610
  error: src/Fl_win32.cxx: patch does not apply
  CMake Error: Could not create named generator Visual Studio 17 2022

  Generators
  * Visual Studio 16 2019        = Generates Visual Studio 2019 project files.
                                   Use -A option to specify architecture.
    Visual Studio 15 2017 [arch] = Generates Visual Studio 2017 project files.
                                   Optional [arch] can be "Win64" or "ARM".
    Visual Studio 14 2015 [arch] = Generates Visual Studio 2015 project files.
                                   Optional [arch] can be "Win64" or "ARM".
    Visual Studio 12 2013 [arch] = Generates Visual Studio 2013 project files.
                                   Optional [arch] can be "Win64" or "ARM".
    Visual Studio 11 2012 [arch] = Generates Visual Studio 2012 project files.
                                   Optional [arch] can be "Win64" or "ARM".
    Visual Studio 10 2010 [arch] = Generates Visual Studio 2010 project files.
                                   Optional [arch] can be "Win64" or "IA64".
    Visual Studio 9 2008 [arch]  = Generates Visual Studio 2008 project files.
                                   Optional [arch] can be "Win64" or "IA64".
    Borland Makefiles            = Generates Borland makefiles.
    NMake Makefiles              = Generates NMake makefiles.
    NMake Makefiles JOM          = Generates JOM makefiles.
    MSYS Makefiles               = Generates MSYS makefiles.
    MinGW Makefiles              = Generates a make file for use with
                                   mingw32-make.
    Green Hills MULTI            = Generates Green Hills MULTI files
                                   (experimental, work-in-progress).
    Unix Makefiles               = Generates standard UNIX makefiles.
    Ninja                        = Generates build.ninja files.
    Ninja Multi-Config           = Generates build-<Config>.ninja files.
    Watcom WMake                 = Generates Watcom WMake makefiles.
    CodeBlocks - MinGW Makefiles = Generates CodeBlocks project files.
    CodeBlocks - NMake Makefiles = Generates CodeBlocks project files.
    CodeBlocks - NMake Makefiles JOM
                                 = Generates CodeBlocks project files.
    CodeBlocks - Ninja           = Generates CodeBlocks project files.
    CodeBlocks - Unix Makefiles  = Generates CodeBlocks project files.
    CodeLite - MinGW Makefiles   = Generates CodeLite project files.
    CodeLite - NMake Makefiles   = Generates CodeLite project files.
    CodeLite - Ninja             = Generates CodeLite project files.
    CodeLite - Unix Makefiles    = Generates CodeLite project files.
    Eclipse CDT4 - NMake Makefiles
                                 = Generates Eclipse CDT 4.0 project files.
    Eclipse CDT4 - MinGW Makefiles
                                 = Generates Eclipse CDT 4.0 project files.
    Eclipse CDT4 - Ninja         = Generates Eclipse CDT 4.0 project files.
    Eclipse CDT4 - Unix Makefiles= Generates Eclipse CDT 4.0 project files.
    Kate - MinGW Makefiles       = Generates Kate project files.
    Kate - NMake Makefiles       = Generates Kate project files.
    Kate - Ninja                 = Generates Kate project files.
    Kate - Unix Makefiles        = Generates Kate project files.
    Sublime Text 2 - MinGW Makefiles
                                 = Generates Sublime Text 2 project files.
    Sublime Text 2 - NMake Makefiles
                                 = Generates Sublime Text 2 project files.
    Sublime Text 2 - Ninja       = Generates Sublime Text 2 project files.
    Sublime Text 2 - Unix Makefiles
                                 = Generates Sublime Text 2 project files.

  thread 'main' panicked at '
  command did not execute successfully, got: exit code: 1

  build script failed, must exit now', C:\Users\Sergey\.cargo\registry\src\github.com-1ecc6299db9ec823\cmake-0.1.50\src\
lib.rs:1098:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

I will be appreciated very much for the some clue to settle this problem

I

**Comment by MoAlyousef** [comment]
What’s in your Cargo.toml?
Do you enable the use-ninja feature while not having the ninja executable installed?
Can you run `cargo clean && cargo build -vv` and post the entire output?

**Comment by MoAlyousef** [comment]
All the CMake visual studio generators are fickle unfortunately. Ninja provides a uniform build for msvc, so if found it’s called in fltk-rs’s build script. If not found, the build will depend on whatever cmake chooses to target!

**Comment by lizzard88** [comment]
Thank you very much for the answer!

Is it possible that presence of Ninja influence on import of vcpkg library openblas?
Near a week trying to introduce openblas into project. It seems openblas requires CMake visual studio generator.
What could be the way to implement fltk and openblas at the same time?

**Comment by lizzard88** [comment]
Thank you very much!!
May I get advice from you in future if I will not be able to set some problems with vcpkg manupulation and compilers to import a library into project?

**Comment by lizzard88** [comment]
Thank you very much!  Your help is very valuable!
You are doint great job for all of us.
