### ISSUE TITLE
hope to support x86 platform

### ISSUE THREAD

**Issue by wwstory** [fltk-rs/fltk-rs#1401]
**Is your feature request related to a problem? Please describe.**
can't build for x86 (eg. --target=i686-pc-windows-gnu).
because it need to download `lib_x86-windows-gnu.tar.gz` from release page, but it is not exsit.
if you can, i want to compile libfltk.a when build my project, not downloading it.
thank you

**Comment by MoAlyousef** [comment]
Ensure you have CMake and a C++ compiler, and it will build from source.

**Comment by wwstory** [comment]
sorry, it work after remove bundled feature. you are right.

> Ensure you have CMake and a C++ compiler, and it will build from source.
