### ISSUE TITLE
[BUG] Tooltip::enter_area unsound behavior

### ISSUE THREAD

**Issue by vstojkovic** [fltk-rs/fltk-rs#1402]
According to the FLTK documentation, the string passed to the `Fl_Tooltip::enter_area()` must be a pointer to static data, because it's not copied. Actually using `fltk::misc::Tooltip::enter_area` in Rust code confirms this, because the tooltip that is displayed contains garbage text. This is because the implementation uses a `CString` that is dropped immediately after the call to `Fl_Tooltip::enter_area()`.

## Desktop info
 - OS: Windows 10 x64
 - Version 1.4.2

**Comment by MoAlyousef** [comment]
Thank you for reporting this.
I've updated the function with a call to into_raw. Can you test that it works on your side as well?

**Comment by dheijl** [comment]
Isn't that raw Cstring leaked now, as there is no corresponding from_raw()?

**Comment by MoAlyousef** [comment]
Yes unfortunately. In several of the api's, fltk expects a long-lived static string, with no way to get back the string. These methods/functions are marked with a `&'static str` requirement on the Rust side.
I'll probably mark the enter_area method to also require a static str, even though it's a breaking change, but in a sense, the previous code didn't work correctly either way.

**Comment by vstojkovic** [comment]
I've tested it and it works, but the problem with the solution is that it leaks memory. The way `Fl_Tooltip::enter_area()` is meant to be used is by calling it every time the cursor enters the screen region that contains the widget (or the widget part) for which we want to display the tooltip.

Here's [an example in C++](https://github.com/gammasoft71/Examples_FLTK/blob/d98528cee08be6f7d56aaade55fc5d50f59ee140/src/Components/Tooltip/Tooltip.cpp#L17-L30).

The way I intend to use it in Rust is similar:
```
table.handle(move |this, evt| {
    match evt {
        Event::Move => if some_elided_condition() {
            let (x, y, w, h) = some_elided_logic();
            Tooltip::enter_area(this, x - this.x(), y - this.y(), w, h, "My tooltip");
        }
        _ => (),
    }
});
```

Every time the tooltip is displayed, the call will leak the tooltip text all over again.

If I may suggest an alternate solution, maybe the type of the `tip` argument could be changed to `&'static CStr`, with an explanation in the documentation about why it's like that? It's not pretty, but it avoids leaking memory continually.

**Comment by MoAlyousef** [comment]
I've gone with your suggestion in the latest push.

**Comment by vstojkovic** [comment]
Works like a charm. Thank you!
