### ISSUE TITLE
[BUG] lose focus when set_border(false)

### ISSUE THREAD

**Issue by lopo12123** [fltk-rs/fltk-rs#1419]
## Describe the bug

Hi, I don't know if this is intentional or not, but I'm seeing the following behavior.
When the window is `set_border(false)` it will lose focus, and it seems that it cannot be focused by `make_current`.
If this is the correct behavior, I would like to know how to give focus to a window without a border.

## To Reproduce
``` rust
// The following code is basically just the simplest demo provided by fltk-rs
fn main() {
        let app = app::App::default();
        let mut wind = Window::new(640, 360, 1280, 720, "Hello from rust");

        // Run the test twice, once with the line commented out (normal) and once with the line left (lost focus)
        // wind.set_border(false);

        wind.end();
        wind.show();
        app.run().unwrap();
    }
```

When typing `cargo run` and pressing Enter, do nothing (mouse and keyboard do not move), and press the esc key when the window appears.

## Expected behavior
window is closed (this should be the default behavior of fltk-rs)

## Desktop info
windows 11

**Comment by MoAlyousef** [comment]
Hello
This was previously discussed here as well:
https://github.com/fltk-rs/fltk-rs/discussions/1033
The essence is that borderless windows are considered tooltips and popups by FLTK. If you need platform specific things you would need to call into platform apis like in the linked discussion.
