### ISSUE TITLE
[BUG] A very strange and hard to reproduce bug about 'fltk::app::Screen::num_at'

### ISSUE THREAD

**Issue by lopo12123** [fltk-rs/fltk-rs#1422]
Hello, I'm here to ask a question again, I've searched for some keywords (screen/number/screen num etc) but can't seem to find relevant discussions.

I am currently working on a small tool for screenshots, but I found that sometimes (very rarely) the position of the mouse click does not match the actual drawn area, and then I found this strange situation.

The following is the scene where I found this problem. I don’t know if you can reproduce it, because the abnormal points seem to be relatively small

---

I have three monitors arranged as follows
![image](https://github.com/fltk-rs/fltk-rs/assets/59609929/3acc08a6-cf99-4ba1-9f24-fcceb78e1411)
- screen1: 1920x1080 (150%)
- screen2: 2560x1440 (100%) primary
- screen3: 1920x1080 (100%)

``` rust
// I use the following code to get the `xywh` of the screen list:
for count in 0..fltk::app::screen_count() {
    println!("{count}: {:?}", fltk::app::screen_xywh(count));
}

// and get:
// 0: (424, 960, 1280, 720)    => screen1
// 1: (0, 0, 2560, 1440)       => screen2
// 2: (2560, 352, 1920, 1080)  => screen3
```

When I used `fltk::app::Screen::num_at`, I found it very strange. I used the following points to test, and found that some were normal and some were not.

```rust
// All points are on the screen with screen_num=1
let points = vec![
    (0, 0),
    (0, 1439),
    (2559, 0),
    (2559, 1439),
    (1450, 933),
    (1357, 1099),  // x
    (1357, 331),
    (1323, 1241),  // x
    (23, 234),
    (23, 1099),
];

for point in points {
    println!("point: {point:?} => screen_num: {}", fltk::app::screen_num(point.0, point.1));
}
```

![image](https://github.com/fltk-rs/fltk-rs/assets/59609929/18f65638-7db6-4203-9b04-7a45204871b6)

---

I don't know why some points get screen_num = 0 but most of them are correct. These points are all in the bounding box (0, 0, 2560, 1440), so it should be 1.

**Comment by MoAlyousef** [comment]
I don't have a multi-screen setup, but I've created a repro of your code here in C++:
https://github.com/MoAlyousef/screen_rep

Can you git clone it and run the build instructions in the README.

If you get the same error, can you report it to https://github.com/fltk/fltk

**Comment by MoAlyousef** [comment]
Hi
I wanted to check in on this issue, Were you able to reproduce using the repro code?

**Comment by lopo12123** [comment]
> Hi I wanted to check in on this issue, Were you able to reproduce using the repro code?

Sorry, last week I was a little busy at work and rushed to the product launch and almost forgot about it, but luckily you reminded me!

I don't know much about c++ (even cmake is installed according to online tutorials), I think the third item here should be to execute `main.exe` in the `Debug` directory on the left.

The output of the program is shown in the figure, it seems that this is a problem with fltk rather than fltk-rs. In this way, should I copy the content of this issue to the fltk project?

![image](https://github.com/fltk-rs/fltk-rs/assets/59609929/82331b0f-078d-4694-b838-73849e50de9a)

If you have any further testing needs, you can contact me at any time, sorry for forgetting this before. /(ㄒoㄒ)/~~

**Comment by lopo12123** [comment]
> > Hi I wanted to check in on this issue, Were you able to reproduce using the repro code?
> 
> Sorry, last week I was a little busy at work and rushed to the product launch and almost forgot about it, but luckily you reminded me!
> 
> I don't know much about c++ (even cmake is installed according to online tutorials), I think the third item here should be to execute `main.exe` in the `Debug` directory on the left.
> 
> The output of the program is shown in the figure, it seems that this is a problem with fltk rather than fltk-rs. In this way, should I copy the content of this issue to the fltk project?
> 
> ![image](https://user-images.githubusercontent.com/59609929/251020126-82331b0f-078d-4694-b838-73849e50de9a.png)
> 
> If you have any further testing needs, you can contact me at any time, sorry for forgetting this before. /(ㄒoㄒ)/~~

I noticed that it forgot to use the `count` here, and it got all the parameters of the same screen (but this has no effect on the current discussion issue)
![image](https://github.com/fltk-rs/fltk-rs/assets/59609929/d270bd18-a612-4747-a079-668a480f71a4)

**Comment by MoAlyousef** [comment]
Yeah it would be better to open an issue in the FLTK repo with the C++ repro code in hand, also explaining your setup. The devs there will probably ask you more questions on your setup or your system to understand where the issue lies.
