### ISSUE TITLE
[BUG] set_scaling_algorithm(RgbScaling::Nearest) is ignored in RgbImage::Scale

### ISSUE THREAD

**Issue by Shelim** [fltk-rs/fltk-rs#1425]
## Describe the bug
I need to upscale png image inside drawing routines with nearest neighboor algorithm (developing a simple pixel-art based game). Unfortunately the `RgbImage::Scale` uses Blinear filtering. Calling `RgbImage::set_scaling_algorithm(RgbScaling::Nearest)` prior had no effect

## To Reproduce
MVP

Use 'example.png' image with pixel art clearly smaller than screen resolution.

![example](https://github.com/fltk-rs/fltk-rs/assets/4707644/0f2a1055-a6d2-4460-9eec-af382c32295c)

````rust
use fltk::{
    enums::Mode,
    image::{RgbImage, RgbScaling},
    prelude::*,
    *,
};

fn main() {
    let a = app::App::default();
    a.set_visual(Mode::Rgb8).unwrap();
    RgbImage::set_scaling_algorithm(RgbScaling::Nearest);
    let mut win = window::Window::default().with_size(640, 480);
    win.fullscreen(true);
    win.end();
    win.show();

    let mut image = image::PngImage::load("example.png")
        .unwrap()
        .to_rgb_image()
        .unwrap();

    win.draw(move |w| {
        use draw::*;
        image.scale(w.width(), w.height(), false, true);
        image.draw(0, 0, w.width(), w.height())
    });

    a.run().unwrap();
}
````

## Expected behavior
Example.png should be drawn in the Window background using nearest interpolation

## Screenshots
From maximized application at 1920 x 1080 resolution:

(One can clearly see blinear artifacts below)

![obraz](https://github.com/fltk-rs/fltk-rs/assets/4707644/06570fda-6563-47fa-9b84-11771d862128)

## Desktop info
 - OS: Windows 10x64
 - Version: 1.4.3

## Additional info
Not applicable

## Build failures
Not applicable

**Comment by MoAlyousef** [comment]
Hi
Thanks for the report.
Trying first on Linux, it seems to work correctly, however when I tried on windows, it seems setting the scaling algorithm changes nothing. 
I think it's probably an issue in FLTK itself. 
I'll create a C++ repro and report it upstream.

**Comment by MoAlyousef** [comment]
I've added a copy_sized method in the master branch, this appears to force the use of the algorithm.
It can be used like:
```rust
use fltk::{
    enums::Mode,
    image::{RgbImage, RgbScaling},
    prelude::*,
    *,
};

fn main() {
    let a = app::App::default();
    a.set_visual(Mode::Rgb8).unwrap();
    RgbImage::set_scaling_algorithm(RgbScaling::Bilinear);
    let mut win = window::Window::default().with_size(640, 480);
    win.end();
    win.show();
    win.fullscreen(true);

    let image = image::PngImage::load("example.png").unwrap();

    win.draw(move |w| {
        use draw::*;
        image.copy_sized(w.w(), w.h()).draw(0, 0, w.w(), w.h())
    });

    a.run().unwrap();
}
```
To use the master branch:
```toml
[dependencies]
fltk = { git = "https://github.com/fltk-rs/fltk-rs" }
```

**Comment by Shelim** [comment]
Thank you, the new method `copy_sized` did the trick
