### ISSUE TITLE
[BUG] dbus.h build failure on Arch Linux

### ISSUE THREAD

**Issue by nohsheef** [fltk-rs/fltk-rs#1427]
## Describe the bug
Build fails, trying to include `<dbus/dbus.h>`, perhaps missing a `-I` somewhere.

```
...ibdecor/src/cursor-settings.c:33:10: fatal error: dbus/dbus.h: No such file or directory
     33 | #include <dbus/dbus.h>
        |          ^~~~~~~~~~~~~
  compilation terminated.
  [299/332] Building CXX object fltk/src/CMakeFiles/fltk.dir/Fl_x.cxx.o
  ninja: build stopped: subcommand failed.
```

```
$ pacman -Ql dbus|grep dbus.h
dbus /usr/include/dbus-1.0/dbus/dbus.h
```

https://github.com/fltk/fltk/commit/6fbc7ad86eadeb1b5405e322553bff4b7aeb0775 `./autogen.sh --enable-wayland --disable-x11` builds and runs:

```
$ ldd fltk/examples/tabs-simple|grep dbu
	libdbus-1.so.3 => /usr/lib/libdbus-1.so.3 (0x00007f0b01f22000)
```

## To Reproduce
`cargo build` an fltk-rs hello world demo on Arch Linux.

## Expected behavior
Build succeeds.

## Desktop info
 - OS: Arch Linux
 
## Additional info
fltk-rs 1.4.7
cmake 3.26.4
gcc 13.1.1
dbus 1.14.8

**Comment by MoAlyousef** [comment]
I have the same dbus header path on my system:
![image](https://github.com/fltk-rs/fltk-rs/assets/37966791/35730099-516a-48a8-842c-69998be40c15)

The build fails in the libdecor subdirectory of FLTK, which fltk-rs doesn't touch.

You seem to be able to build fltk using autotools, are you also able to build it with CMake (also enabling wayland)?

**Comment by MoAlyousef** [comment]
I’ll try to spin up a VM with arch linux. What’s in your Cargo.toml?

**Comment by MoAlyousef** [comment]
Tried in a docker container running arch:
![image](https://github.com/fltk-rs/fltk-rs/assets/37966791/69651d1b-b9b0-48f1-a14f-835d3f4f5c72)

However looking at the FLTK CMakeLists.txt, I think I see something that could cause issues in adding the dbus header paths to FLTK's libdecor.

**Comment by nohsheef** [comment]
Regular Arch. The only difference in my Cargo.toml is that I use `features = ["use-ninja", "use-wayland"]`.

**Comment by nohsheef** [comment]
What could possibly be different :thinking: in your Arch installation that makes it succeed? I'll do more tests later and compare building the examples in fltk-rs.

**Comment by nohsheef** [comment]
Same error if I clone fltk-rs, check out 1.4.7, and run `cargo build --example hello_button --features=use-ninja,use-wayland`.

**Comment by nohsheef** [comment]
Same error with d42e6dda11dcbb6a326769d072e06785f1dd51c7

**Comment by MoAlyousef** [comment]
If you can try the following:
```
cd fltk-sys/cfltk/fltk/src
```

Open the CMakeLists.txt file.
In line 514:
move the `include_directories(${DBUS_INCLUDE_DIRS})` to be after the next line.

So instead of:
```cmake
include_directories(${DBUS_INCLUDE_DIRS})
pkg_check_modules(DBUS dbus-1)
```
It should be:
```cmake
pkg_check_modules(DBUS dbus-1)
include_directories(${DBUS_INCLUDE_DIRS})
```

Then cd back to fltk-rs and rerun the build?

**Comment by nohsheef** [comment]
Yep, include after pkg_check builds and makes sense.

**Comment by nohsheef** [comment]
Fixed upstream.
