### ISSUE TITLE
[BUG] Runtime increase when recreating pack

### ISSUE THREAD

**Issue by abau** [fltk-rs/fltk-rs#1438]
Hi, I'm using fltk-1.4.8 and I noticed a strange runtime-behavior when particular widgets in my app are recreated very often - e.g., on mouse movements. In the following program, a horizontal pack containing some frames is recreated inside fltk's main-loop and the duration it takes for recreating these widgets increases dramatically:

```rust
use fltk::{ app::{self}, frame::Frame, group::{Pack, PackType}, prelude::*, window::Window };

fn main() {
    let app = app::App::default();
    let mut wind = Window::new(100, 100, 400, 300, "Hello from rust");

    let mut pack = Pack::new(0, 0, 400, 100, None);
    pack.set_type(PackType::Horizontal);
    pack.end();

    wind.end();
    wind.show();

    while app.wait() {
        let start = std::time::Instant::now();

        pack.clear();
        pack.begin();

        for i in 0..10 {
            let label = i.to_string();

            Frame::new(0, 0, 10, 100, None).with_label(&label);
        }

        pack.end();

        eprintln!("{}ms ({}us)", start.elapsed().as_millis(), start.elapsed().as_micros());
    }
}
```

When running on my machine, the re-creation of the pack initially takes some microseconds and after about a minute it already takes several milliseconds:
```
$ time cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/pack-bug`
0ms (30us)
0ms (27us)
0ms (106us)
0ms (25us)

...

6ms (6400us)
7ms (7693us)
6ms (6428us)
6ms (6382us)
9ms (9117us)
6ms (6373us)
7ms (7424us)
6ms (6785us)
^C

real    1m7,549s
user    1m3,671s
sys     0m0,859s
```

Same for release builds. The expected behavior would be that the runtime for recreating these widgets is more or less constant.

Interestingly, I couldn't observe any runtime increase when recreating other widgets like `Tree`.

**Comment by MoAlyousef** [comment]
Hmm what OS are you running on?

I don’t have an explanation for it yet. Will need to investigate further.

**Comment by abau** [comment]
I use Linux.

**Comment by MoAlyousef** [comment]
Running things on my system (wsl), I notice no memory increase. However it appears this code causes a busy loop since it clocks at 100% cpu. I assume it might be the cause of perf degradation, maybe cache misses, or maybe FLTK actually doing something to throttle things down.
The pack::clear might also be a heavy operation (widget deletion) which contributes to things. 
At first I thought it was the locking done on the cfltk side, but when I built the example with `--features=single-threaded`, even though the performance improves, it still clocks at 100% and degrades slowly with time.

**Comment by abau** [comment]
Since this has been closed, while the problem persists, I just want to make sure: this issue will not get fixed and is assumed to be expected behavior?

**Comment by MoAlyousef** [comment]
I believe it’s expected behavior as mentioned in my previous comment. If you have a suggestion to circumvent the cpu throttling, I can reopen the issue. My suggestion is to avoid busy looping at 100% cpu.
