### ISSUE TITLE
[BUG]Unable to click the lower part of the button

### ISSUE THREAD

**Issue by c61292558** [fltk-rs/fltk-rs#1439]
## Describe the bug
“I don’t know why I can’t click on the bottom half of the second button. The clicks are ineffective.”

## To Reproduce
Please provide a minimal reproducible examples and the steps to reproduce the behavior.
```
use fltk::{prelude::*, *,group::Flex};

fn main() {
    let a = app::App::default().with_scheme(app::Scheme::Oxy);
    let mut win = window::Window::default().with_size(400, 300);
	win.make_resizable(true);
    let mut flex = Flex::new(0, 0, 650, 100, "这是一个Flex");
    flex.set_type(group::FlexType::Column);
    let expanding = button::Button::new(190,190,100,100,"Expanding");
    let mut normal = button::Button::new(100,100,100,100,"Click on the bottom half");
    flex.set_size(&expanding, 30);
	flex.set_size(&mut normal, 200);
    flex.end();

    win.end();
    win.show();
    a.run().unwrap();
}
```
## Expected behavior
**He should be clicked on as usual.**

## Screenshots
![image](https://github.com/fltk-rs/fltk-rs/assets/11317413/4a5417af-2853-4791-b8f3-e44d6bc4621b)

## Desktop info
 - OS: [e.g. Linux deepin x64]
 - Version 23beta
-------------------------------------------------------------------------------------------------------------------------------------------------------
## Build failures
If you're having build difficulties, please check:
- The required dependencies for your platform, mentioned in the [README](https://github.com/fltk-rs/fltk-rs#dependencies).
- The [FAQ](https://github.com/fltk-rs/fltk-rs/blob/master/FAQ.md). 
- That you have a working CMake and C++11 compiler. At least CMake should be in your PATH. 
- That your Rust's target arch is similar to your C/C++ target arch. 
- The [Setup chapter](https://fltk-rs.github.io/fltk-book/Setup.html). 

Otherwise you can open a github discussion [here](https://github.com/fltk-rs/fltk-rs/discussions) describing your difficulties, along with the output of:
- `cargo install fltk-check-env && fltk-check-env`
- `cargo build -vv`

Please only open a bug report if the repo/crate used to build and currently fails. The github-actions CI already checks for the 3 major desktop platforms. Also include the outputs of:
 - `cargo build -vv`
 - `rustup toolchain list`
 - CMake error and log files

Also remember if you're git cloning the fltk-rs repo, to run `git submodule update --init --recursive` since this repo uses git submodules.

**Comment by MoAlyousef** [comment]
The normal button extends beyond the limit of the Flex, so it isn't clickable, even though it's visible:

The flex's height is 100, the expanding button's size is 30, and the normal button is 200. So only 70 of the normal button is clickable and the rest is outside the bounds of the Flex.

Group widgets normally don't clip children which are out of bounds unless set_clip_children(true).
