### ISSUE TITLE
[BUG]The Leave event is triggered inexplicably.

### ISSUE THREAD

**Issue by c61292558** [fltk-rs/fltk-rs#1440]
## Describe the bug
**Why does the Leave event get triggered when I move my mouse very fast? I put it on a button. Is that correct?**
Especially when I leave the window.

## To Reproduce
Please provide a minimal reproducible examples and the steps to reproduce the behavior.
```
use fltk::{
    app,
    button::*,
    enums::Event,
    prelude::{GroupExt, MenuExt, WidgetBase, WidgetExt, WindowExt},
    window::Window,
};

fn main() {
    let app = app::App::default().with_scheme(app::Scheme::Oxy);
    app::background(221, 221, 221);
    app::set_visible_focus(false);
    let mut wind = Window::new(500, 100, 600, 600, "My Leave")
        .with_label("Event")
        .center_screen();
    let mut btn = Button::new(50, 50, 100, 50, "leave");
    btn.handle(|b, ev| match ev {
        Event::Leave => {
            println!("leave event!");
            true
        }
        _ => false,
    });
    wind.end();
    wind.show();
	app.run().unwrap();
}
```

## Expected behavior
**The Leave event is only triggered when I leave the button.**

## Screenshots

![录屏_选择区域_20230724202522](https://github.com/fltk-rs/fltk-rs/assets/11317413/1c2b74d9-a8ce-4a94-9d57-2e2f14d93b33)

## Desktop info
 - OS: [linux deepin 23 x64]
 - Version [e.g. V23 BETA ]
-  Kernel: 6.4.0-xanmod1   
## Additional info
fltk-rs="1.4.7"

## Build failures
If you're having build difficulties, please check:
- The required dependencies for your platform, mentioned in the [README](https://github.com/fltk-rs/fltk-rs#dependencies).
- The [FAQ](https://github.com/fltk-rs/fltk-rs/blob/master/FAQ.md). 
- That you have a working CMake and C++17 compiler. At least CMake should be in your PATH. 
- That your Rust's target arch is similar to your C/C++ target arch. 
- The [Setup chapter](https://fltk-rs.github.io/fltk-book/Setup.html). 

Otherwise you can open a github discussion [here](https://github.com/fltk-rs/fltk-rs/discussions) describing your difficulties, along with the output of:
- `cargo install fltk-check-env && fltk-check-env`
- `cargo build -vv`

Please only open a bug report if the repo/crate used to build and currently fails. The github-actions CI already checks for the 3 major desktop platforms. Also include the outputs of:
 - `cargo build -vv`
 - `rustup toolchain list`
 - CMake error and log files

Also remember if you're git cloning the fltk-rs repo, to run `git submodule update --init --recursive` since this repo uses git submodules.

**Comment by MoAlyousef** [comment]
Isn’t this the same issue you’ve asked about here:

https://github.com/fltk-rs/fltk-rs/discussions/1434

**Comment by c61292558** [comment]
Oh, sorry, I seem to have forgotten. 
But how to solve this problem at this stage?

**Comment by MoAlyousef** [comment]
You could handle the leave event for the window, this should prevent propagation of the event to children.

**Comment by MoAlyousef** [comment]
it seems FLTK propagates the window's leave event to all child widgets. It's probably to reset state or something

**Comment by c61292558** [comment]
I just tried adding the code for the window’s leave event, and as soon as I leave the window, two leave events are triggered (including the button’s and the window’s).
```
wind.handle(|w, ev| match ev {
        Event::Leave => {
            println!("window leave event!");
            true
        }
        _ => false,
    });
    ```

**Comment by MoAlyousef** [comment]
You could probably perform a check like:
```rust
use fltk::{
    app,
    button::*,
    enums::Event,
    prelude::{GroupExt, MenuExt, WidgetBase, WidgetExt, WindowExt},
    window::Window,
};

fn main() {
    let app = app::App::default().with_scheme(app::Scheme::Oxy);
    app::background(221, 221, 221);
    app::set_visible_focus(false);
    let mut wind = Window::new(500, 100, 600, 600, "My Leave")
        .with_label("Event")
        .center_screen();
    let mut btn = Button::new(50, 50, 100, 50, "leave");
    btn.handle(|b, ev| match ev {
        Event::Leave => {
            if !app::event_inside_widget(&b.parent().unwrap()) {
                println!("leave event!"); 
            }
            true
        }
        _ => false,
    });
    wind.end();
    wind.show();
	app.run().unwrap();
}
```

**Comment by c61292558** [comment]
The effect is still the same.

**Comment by MoAlyousef** [comment]
Even after removal of the window handle code?

**Comment by c61292558** [comment]
yes,I used your code directly and it's still the same.
![录屏_选择区域_20230725005807](https://github.com/fltk-rs/fltk-rs/assets/11317413/2b2ac50c-4ee9-4150-b2bf-3ec9bf38fa77)

**Comment by MoAlyousef** [comment]
Can you try:
```rust
use fltk::{
    app,
    button::*,
    enums::Event,
    prelude::{GroupExt, MenuExt, WidgetBase, WidgetExt, WindowExt},
    window::Window,
};

fn main() {
    let app = app::App::default().with_scheme(app::Scheme::Oxy);
    app::background(221, 221, 221);
    app::set_visible_focus(false);
    let mut wind = Window::new(500, 100, 600, 600, "My Leave")
        .with_label("Event")
        .center_screen();
    let mut btn = Button::new(50, 50, 100, 50, "leave");
    btn.handle(|b, ev| match ev {
        Event::Leave => {
            if !app::belowmouse::<Window>().is_none() {
                println!("leave event!"); 
            }
            true
        }
        _ => false,
    });
    wind.end();
    wind.show();
	app.run().unwrap();
}
```

**Comment by c61292558** [comment]
Great！Successful！
But I don’t understand why there is an exclamation mark in the code(**`if !app::belowmouse::<Window>().is_none() {`**), isn’t that the opposite? When there is no window below me, the is_none() function returns true, and the exclamation mark takes the opposite value and becomes false. Logically, the println function should not be executed afterwards, right? Why?

**Comment by MoAlyousef** [comment]
It's checking whether the window is below the button or not `app::belowmouse::<Window>().is_some()`. For the button, this will return true, while for the window it will return false.

**Comment by c61292558** [comment]
the window is below the button or not？


I thought it was all about checking whether the mouse is under it. But why is the doc written like this: 
“Gets the widget that is below the mouse cursor. This returns an Option which can be specified in the function call”

**Comment by MoAlyousef** [comment]
It is, but outside the window the option is None

**Comment by c61292558** [comment]
“outside the window the option is None”
what's the meaning?

**Comment by MoAlyousef** [comment]
app::belowmouse() outside the window returns None.

**Comment by c61292558** [comment]
“I understand, thank you for your patient answer.”
