### ISSUE TITLE
[BUG] A column isn't displaying data correctly

### ISSUE THREAD

**Issue by rjzak** [fltk-rs/fltk-rs#1448]
## Describe the bug
A column with an email address only shows the address before the `@`

## To Reproduce
Code: https://github.com/malwaredb/malwaredb-rs/blob/4e346eddc5e894c737b54d2fb5f7a025306b788b/src/cli/admingui/mod.rs#L50

## Expected behavior
Adding an email address to a column should show the email address

## Screenshots
See below

## Desktop info
 - OS: macOS 13.5, Debian 12
 - Version [e.g. 1.4.2] 1.4
 - Display server on linux (wayland or x11) X11

## Additional info
* Printing the table data shows the data that was entered into the table, but the data isn't rendered on the GUI.
* Table is created with [fltk-table](https://github.com/fltk-rs/fltk-table), but this doesn't feel like an `fltk-table` issue.

![image](https://github.com/fltk-rs/fltk-rs/assets/1133882/05b40401-5baf-481e-a93d-83ac3f1c3525)

**Comment by MoAlyousef** [comment]
FLTK treats the `@` character as some form of modifier which is used by some widgets to apply styles and other properties. So you would need to escape it with another `@`. 
```rust

utable.set_cell_value(i as i32, j, &user.email.replace("@","@@")),

```

**Comment by rjzak** [comment]
Thank you! This is my first time using Fltk.
