### ISSUE TITLE
[BUG] Memory leak when setting a Table::draw_cell callback

### ISSUE THREAD

**Issue by hwjsnc** [fltk-rs/fltk-rs#1452]
## Describe the bug
`fltk-rs` leaks memory when setting a custom `fltk::table::Table::draw_cell` callback. In some cases performance is noticeably degraded.

## To Reproduce

```
use std::vec::Vec;

use fltk::prelude::GroupExt;
use fltk::prelude::TableExt;
use fltk::prelude::WidgetExt;

fn main() {
    // the problem is most apparent for large tables
    const ROWS: usize = 1_000_000;
    const COLS: usize = 20;

    let data: Vec<Vec<String>> = (0..ROWS)
        .map(|row| (0..COLS).map(|col| format!("cell {row} {col}")).collect())
        .collect();

    let mut win = fltk::window::Window::default()
        .with_size(1280, 720)
        .with_label("test");

    let mut table = fltk::table::Table::default().size_of_parent();
    table.set_rows(ROWS.try_into().unwrap());
    table.set_cols(COLS.try_into().unwrap());

    table.draw_cell(move |table, ctx, row, col, x, y, w, h| match ctx {
        fltk::table::TableContext::Cell => {
            let Some(row) = data.get(usize::try_from(row).unwrap()) else { return };
            let Some(cell) = row.get(usize::try_from(col).unwrap()) else { return };
            fltk::draw::set_draw_color(fltk::enums::Color::BackGround);
            fltk::draw::draw_rectf(x, y, w, h);
            fltk::draw::set_draw_color(fltk::enums::Color::ForeGround);
            fltk::draw::draw_text2(cell.as_str(), x, y, w, h, fltk::enums::Align::Center);
        }
        _ => {}
    });

    win.make_resizable(true);
    win.end();
    win.show();

    while fltk::app::wait() {
        // nothing
    }
}
```

Scroll a few times all the way up and down. Scrolling is smooth the first few times but becomes increasingly laggy. `Heaptrack` detects leaks via `Fl::watch_widget_pointer`.

## Expected behavior

No memory leaks, no performance problems.

## Screenshots

none

## Desktop info

 - OS: arch linux amd64
 - rolling release
 - Display server: x11

## Additional info

The `draw_cell` impl via `impl_table_ext!` calls `$name::from_widget_ptr`, which in turn calls `fltk_sys::fl::Fl_Widget_Tracker_new` (which calls `Fl::watch_widget_pointer` on the C++ side). I suspect that a corresponding `fltk_sys::fl::Fl_Widget_Tracker_delete` is missing somewhere.

(As a sidenote, the `delete` impl via `impl_table_ext!` might also be missing a `fltk_sys::fl::Fl_Widget_Tracker_delete` but adding it does not seem to eliminate the leak.)

**Comment by MoAlyousef** [comment]
Thanks for the report and the repro.
I tried cleaning up the widget tracker code. At some point the deletion disappeared!
Can you try with the git repo?

**Comment by hwjsnc** [comment]
The problem appears to be gone. Thanks for the quick fix!
