### ISSUE TITLE
Expose Fl::add_check()

### ISSUE THREAD

**Issue by vstojkovic** [fltk-rs/fltk-rs#1453]
**Is your feature request related to a problem? Please describe.**
Currently, I process the results sent from worker threads in the main event loop of the UI thread, along the lines of:
```rust
fn run(&self) {
  while app::wait() {
    while self.run_loop_iteration() {
      app::check();
    }
  }
}

fn run_loop_iteration(&self) -> bool {
  if let Some(update) = self.next_worker_update() {
    self.handle_update(update);
  }
  self.has_pending_worker_updates()
}
```

This approach works fine until I have to show a modal window. Ideally, I would like to simply show a modal window and then wait for it to close. Unfortunately, if I do that, then `run_loop_iteration` won't get called.

**Describe the solution you'd like**
Having `Fl::add_check()` exposed in Rust as `app::add_check()` (like `app::add_idle()`) would allow me to install the worker thread processing logic in the check callback and simply wait for any modal dialog to finish without further complications.

**Describe alternatives you've considered**
The alternatives right now are to:

1. pass the reference to my main app struct deep into the bowels of my code, just so I can call `run_loop_iteration` from there
2. have a global accessor for my main app struct so any bit of code can call `run_loop_iteration` when needed
3. refactor the code in complicated ways so that showing a modal dialog will make the execution bubble up all the way to the main loop with a continuation function to be called when the dialog is hidden

These alternatives would work, but I would rather avoid complicating my code in these ways.

**Comment by MoAlyousef** [comment]
I've added app::add_check, has_check, and remove_check to the master branch if you would like to try them out before I cut a release. The api is like that of add_idle3

**Comment by vstojkovic** [comment]
Just wanted to thank you for this. I had to stop working on my project for a bit, but I came back, updated the `fltk-rs` dependency, changed my code to use `add_check`, and it all works like a charm. Thanks again!
