### ISSUE TITLE
Add api for Fl_Preferences and friends

### ISSUE THREAD

**Issue by diegoefe** [fltk-rs/fltk-rs#1457]
I would like to save/restore window positions and sizes and other state variables.

Adding calls to FL_Preferences and related would solve this need.

Of course it can be implemented saving and loading files in json. yaml, .ini or any other format but FLTK already has this functionality in [Fl_Preferences](https://www.fltk.org/doc-1.3/classFl__Preferences.html)

**Comment by diegoefe** [comment]
Excellent! Thanks!

**Comment by MoAlyousef** [comment]
I've added most relevant methods to fltk-rs. I can add more if needed. These are in the app::prefs module:
```rust
use fltk::app::prefs::{Preferences, Root};

fn main() {
    let mut prefs = Preferences::new(Root::USER_L, "myfltk.org", "tempapp").unwrap();
    let mut opts = Preferences::new_group(&mut prefs, "Options").unwrap();
    opts.set_int("winsize", 400).unwrap();
    let size = opts.get_int("winsize", 800).unwrap();
    opts.set_str("wintitle", "Hello").unwrap();
    let title = opts.get_str("wintitle", "myapp").unwrap();
    println!("{}", size);
    println!("{}", title);
    println!("{:?}", opts.name());
    println!("{:?}", prefs.filename());
}
```

I couldn't get the set* and get* methods to be generic unfortunately. Also the return type of the get methods is `Result<sometype, sometype>` where both variants are the same type, this is inline with the FLTK api where getters take a defaultValue and return it on error. I don't see the use of a default value in Rust since these return a Result, so I might change the api to not accept a defaultValue at all. Users needing a default value can do:
```rust
let winsize = if let Ok(sz) = opts.get_int("winsize") {
    sz
} else {
     300
};
```
What do you think?

**Comment by MoAlyousef** [comment]
I removed the default value in getters:
```rust
use fltk::app::prefs::{Preferences, Root};

fn main() {
    let mut prefs = Preferences::new(Root::USER_L, "myfltk.org", "tempapp").unwrap();
    let mut opts = Preferences::new_group(&mut prefs, "Options").unwrap();
    opts.set_int("winsize", 400).unwrap();
    let size = opts.get_int("winsize").unwrap_or(300);
    opts.set_str("wintitle", "Hello").unwrap();
    let title = opts.get_str("wintitle").unwrap_or("My Window".to_string());
    println!("{}", size);
    println!("{}", title);
    println!("{:?}", opts.name());
    println!("{:?}", prefs.filename());
}
```

**Comment by diegoefe** [comment]
I agree that is inelegant to return the default value in place of the "error" (if I understood you correctly) but the alternative (returning an Option) forces you to use global constant variables, magic numbers or functions to avoid the duplication if you count on the default values.
Does this makes sense?
In any case, both alternatives are useful but I prefer the first

**Comment by diegoefe** [comment]
It works just fine! Thank you!
