### ISSUE TITLE
Add wrapper for Fl_Choice widget (not for menu)

### ISSUE THREAD

**Issue by diegoefe** [fltk-rs/fltk-rs#1461]
I need the simpler "select" widget that does not allow edition (like Fl_Input_Choice)
The solution would be to wrap Fl_Choice
I guess it may be under misc module

**Comment by MoAlyousef** [comment]
Fl_Choice is already wrapped in menu::Choice

**Comment by diegoefe** [comment]
Sorry, the location (menu) was misleading to me. I'm closing it
