### ISSUE TITLE
Controls nested inside groups that are inside a scroll group randomly lose the ability to receive events when you scroll.

### ISSUE THREAD

**Issue by akhudek** [fltk-rs/fltk-rs#1471]
When you have groups nested in groups inside a scroll group, scroll causes seemingly random controls within the groups to stop responding. With this example code the problem shows for me with fltk v1.4.11 or greater, though with my main application I'm still seeing it with v1.4.10. Going back to v1.4.9 appears to fix the problem.

There may be a more minimal example than this, but the dynamic nature of clearing and adding controls with flex groups mirrors my main application code.

## To Reproduce

If you run the following code and hit the add button a bunch of times until the scroll bar expands, then scroll down a bit, some of the buttons become unpressable. 

```rust
use fltk::{
    app,
    button::Button,
    enums::{Color, FrameType},
    group::{Flex, Scroll},
    prelude::*,
    window::Window,
};

fn main() {
    let app = app::App::default();
    let mut wind = Window::new(100, 100, 400, 300, "Hello from rust");
    wind.make_resizable(true);
    let mut flex = Flex::default_fill().column();
    let mut scroll = Scroll::default().with_size(100, 300);
    scroll.set_frame(FrameType::FlatBox);
    scroll.set_color(Color::Green);

    scroll.end();

    let mut i = 0;

    let mut button = Button::default().with_label("add");
    flex.set_size(&button, 50);
    button.set_callback(move |_| {
        i += 1;
        scroll.clear();
        scroll.begin();
        for i in 0..i {
            let g = fltk::group::Row::default()
                .with_size(100, 50)
                .with_pos(0, 50 * i);
            let mut b = Button::default()
                .with_size(100, 50)
                .with_label(&format!("A {}", i));
            b.set_callback(move |_| {
                println!(" {} clicked", i);
            });
            g.end();
        }
        scroll.end();
        scroll.redraw();
    });

    flex.end();

    wind.end();
    wind.show();
    app.run().unwrap();
}
```

## Expected behavior

I would expect that all the controls would work normally regardless of scrolling.

 - OS: Mac OS Ventura
 - Version 13.6

**Comment by MoAlyousef** [comment]
I was able to reproduce in C++, so I've reported the issue here:
https://github.com/fltk/fltk/issues/811

**Comment by MoAlyousef** [comment]
The issue should be fixed in FLTK and fltk-rs (master), and should appear in the next release.

You can try it out using:

```toml
[dependencies]
fltk = { git = "https://github.com/fltk-rs/fltk-rs" }
```

**Comment by akhudek** [comment]
Awesome, thanks! You (and the fltk team) are the best. :D
