### ISSUE TITLE
building fltk 1.4.17 fails with the enable-glwindow feature

### ISSUE THREAD

**Issue by Meisaka** [fltk-rs/fltk-rs#1474]
I recently added fltk to one of my project's Cargo.toml file.
I added version 1.4.17 without any features set, and it built fine, but when I added the "enable-glwindow" feature, running `cargo build` would now fail to build fltk.
`fltk = { version = "1.4.17", features = ["enable-glwindow"]}`
I got 188 errors that look like:
```
error[E0599]: no method named `widget` found for raw pointer `*mut fltk_sys::window::Fl_Gl_Window` in the current scope
    --> $HOME\.cargo\registry\src\github.com-1ecc6299db9ec823\fltk-1.4.17\src\window.rs:1005:67
     |
1005 |             unsafe { Fl_Gl_Window_make_overlay_current(self.inner.widget() as _) }
     |                                                                   ^^^^^^ method not found in `*mut fltk_sys::window::Fl_Gl_Window`
     |
     = note: try using `<*const T>::as_ref()` to get a reference to the type behind the pointer: https://doc.rust-lang.org/std/primitive.pointer.html#method.as_ref
     = note: using `<*const T>::as_ref()` on a pointer which is unaligned or points to invalid or uninitialized memory is undefined behavior
```
I read through the code at
https://github.com/fltk-rs/fltk-rs/blame/48c279d65c4fc25252f34a33ba0ad4b3653187d9/fltk/src/window.rs#L876C34-L876C35
and the commit https://github.com/fltk-rs/fltk-rs/commit/13aa8b60915809a86e4a267d776bb3ef5862124f
I tried changing:
```
pub struct GlWidgetWindow {
    inner: *mut Fl_Gl_Window,
    tracker: crate::widget::WidgetTracker,
    is_derived: bool,
}
```
into
```
pub struct GlWidgetWindow {
    inner: crate::widget::WidgetTracker,
    is_derived: bool,
}
```
This seems to have fixed building fltk for me, although I am unsure if this is entirely correct and functional.

**Comment by MoAlyousef** [comment]
Thank yo for the report and the suggested fix.
I've applied it in master, and will be releasing a patch version 1.4.18 this evening.
