### ISSUE TITLE
[BUG] Event::KeyDown does not recognize arrow keys as Keys

### ISSUE THREAD

**Issue by shelovesmox** [fltk-rs/fltk-rs#1476]
## Describe the bug
Arrow keys do not invoke the KeyDown event

## To Reproduce
1. Create app with a window
2. set up an event that that tracks Key::Down
3. press the arrow keys

## Expected behavior
KeyDown should recognize arrow keys

## Desktop info
Ubuntu 22.04
Wayland Linux

# Additional info

**Comment by MoAlyousef** [comment]
Can you post a repro. I can't test on a wayland system at the moment, but on kubuntu with x11, this prints the which arrow key was pressed:
```rust
use fltk::{
    prelude::*, enums::*, *
};

fn main() {
    let app = app::App::default();
    let mut wind = window::Window::new(100, 100, 400, 300, None);
    wind.end();
    wind.show();
    wind.handle(|_, ev| match ev {
        Event::KeyDown => {
            println!("{:?}", app::event_key());
            true
        },
        _ => false,
    });
    app.run().unwrap();
}
```

**Comment by MoAlyousef** [comment]
I tried the code on wayland, and it also detects arrow keys.
