### ISSUE TITLE
[BUG] NoBox with Tile leads to improper redrawing

### ISSUE THREAD

**Issue by Aargonian** [fltk-rs/fltk-rs#1477]
## Describe the bug
I attempted to create a very simple app with two resizable panes using Tile. If I understood the FLTK documentation correctly, the example uses DownBox for the frame type for the underlying frames to make the "dividers". For my own app I wanted to get rid of these visible dividers for a more modern look, instead relying on the background color of the tile to cleanly separate them. However, when using NoBox for the FrameType, I run into redraw issues (seemingly) where the frames don't redraw themselves correctly. Instead they smear, as though they are just repainting over the old image without clearing first. This does not appear to happen when using DownBox on both frames. 

If I set only one of the two frames to up/downbox, that frame redraws correctly, while the other frame does not. In addition to the previous issues, the second pane doesn't seem to get the correct background color if it is set to NoBox.

## To Reproduce
```rust
use fltk::{app, frame, group, prelude::*, window};
use fltk::enums::{Color, FrameType};

fn main() {
    let app = app::App::default();
    let mut window = window::Window::default().with_size(600, 300);
    window.set_frame(FrameType::NoBox);
    window.make_resizable(true);

    let mut tile = group::Tile::default_fill();

    // First panel
    let mut frame1 = frame::Frame::new(0, 0, 300, 300, "First");
    frame1.set_frame(FrameType::NoBox);
    frame1.set_color(Color::from_rgb(0x33, 0x33, 0x33)); // First panel color

    // Second panel
    let mut frame2 = frame::Frame::new(300, 0, 300, 300, "Second");
    frame2.set_frame(FrameType::NoBox);
    frame2.set_color(Color::from_rgb(0x55, 0x55, 0x55)); // Second panel color

    tile.end();

    window.end();
    window.show();

    app.run().unwrap();
}
```

## Expected behavior
I expected to be able to resize the panes without redraw issues.

### First Pane: NoBox, Second Pane: UpBox
![Screen Capture Nov 26, 2023 at 2 22 23 AM](https://github.com/fltk-rs/fltk-rs/assets/8229879/049b950e-c669-44c9-b5a1-5f0062b20aea)

### First Pane: UpBox, Second Pane: NoBox
![Screen Capture Nov 26, 2023 at 2 22 57 AM](https://github.com/fltk-rs/fltk-rs/assets/8229879/b79cf36a-c8f0-4aed-9c0e-0e815bb0514f)

### Both Panes: NoBox
![Screen Capture Nov 26, 2023 at 2 23 15 AM](https://github.com/fltk-rs/fltk-rs/assets/8229879/c8189ce6-03fa-4647-bf8d-d2214ed18fd8)

## Desktop info
 - OS: macOS Sonoma (14.1.1)
 - Version 1.4.18

## Additional info
I'm completely new to FLTK, so I may have just misunderstood some documentation here. If so, my apologies!

**Comment by MoAlyousef** [comment]
Hi
Thanks for the report. This is a known issue in FLTK, see [here](https://github.com/fltk/fltk/issues/263#issuecomment-886187122).

I guess you would have to work around this behavior.  Does using FlatBox instead of NoBox not fix the issue for you?
