### ISSUE TITLE
[BUG] Latest Git version no longer builds; "symbol multiply defined" linker errors

### ISSUE THREAD

**Issue by Prof9** [fltk-rs/fltk-rs#1479]
## Build failures
I just updated from `fltk-rs` 1.4.17 (last published version) to latest version on Git to try out the new `Fl_Terminal` bindings. After updating, my project no longer builds and outputs a giant linker error.

The full error log is a bit too long to include inline, so I've uploaded it here: [log.txt](https://github.com/fltk-rs/fltk-rs/files/13536689/log.txt)

Most of them are "symbol multiply defined" errors, e.g.
```
libfltk_sys-8f369e305b7983d8.rlib(cfl_group.obj) : error LNK2005: Fl_Tabs_children already defined in libfltk_sys-c1e017b57d9711f6.rlib(cfl_group.obj)
```

## To Reproduce
* Update `fltk-rs` version in `Cargo.toml`: `fltk = { version = "^1.4", git = "https://github.com/fltk-rs/fltk-rs" }`
* `cargo update`
* `cargo clean`
* `cargo build`

## Desktop info
 - OS: Windows 11 x64
 - Version: 7e37ab164862d35819d3263e3e1f848e2233ec7a

**Comment by MoAlyousef** [comment]
Hi
Thanks for the report. If you’re using another fltk-* crate (like fltk-theme etc), you would get duplicate symbols if you point one of them to the git repo. 

Can you try reverting your change and adding to your Cargo.toml:
```toml
[patch.crates-io]
fltk = { git = "https://github.com/fltk-rs/fltk-rs" }
```
cargo update then cargo build. 
In all cases I’ll be releasing a new version tomorrow with the Terminal widger.
