### ISSUE TITLE
[BUG] examples/custom_choice.rs crash on macOS

### ISSUE THREAD

**Issue by kzhui125** [fltk-rs/fltk-rs#1484]
## Describe the bug
click the button will crash

## Screenshots

<img width="400" alt="image" src="https://github.com/fltk-rs/fltk-rs/assets/11925432/cfa96620-b85f-45cc-a746-ebbd941ca77d">

## Desktop info
 - OS: macOS 14.1.2

**Comment by MoAlyousef** [comment]
So I tried on Linux and it seems this is macos specific. So the added check reflects that now.

**Comment by kzhui125** [comment]
How can I build from source to test latest commit, I get build error on macOS.

```rs
cargo run --package fltk --example custom_choice
```

<img width="251" alt="image" src="https://github.com/fltk-rs/fltk-rs/assets/11925432/cff865c4-d53a-4e36-b097-1b304c485992">



```
CMake Error: The source directory ".../fltk-rs/fltk-sys/cfltk" does not appear to contain CMakeLists.txt.
  Specify --help for usage, or press the help button on the CMake GUI
```

```
cmake --version
cmake version 3.28.0
 
CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

Thanks,

**Comment by kzhui125** [comment]
it doesn't crash now, thanks,
