### ISSUE TITLE
Relax the 'static lifetime bound on `Widget::new`'s `title` paramater

### ISSUE THREAD

**Issue by bolshoytoster** [fltk-rs/fltk-rs#1485]
**Is your feature request related to a problem? Please describe.**
The `Widget::new` function currently requires that the `title` parameter can be converted to `Option<&'static str>` (requiring that it lives for the whole lifetime of the program), when it is only converted to a `CString`, which clones it.

The `WidgetExt::set_label` function, which does a similar thing takes a `&str`.

This is annoying when creating a widget with a dynamic title.

**Describe the solution you'd like**
The 'static lifetime bound can be relaxed to a generic lifetime, allowing for widgets to be made with titles created at runtime.

**Describe alternatives you've considered**
Creating the widget with the title an `None` and then using `WidgetExt::set_label` instead.

**Additional context**
I was able to do this and there didn't seem to be any problems by replacing `T: Into<Option<&'static str>>` with `'a, T: Into<Option<&'a str>>` in `src/prelude.rs`:
https://github.com/fltk-rs/fltk-rs/blob/035b3e14715cfff6a1849139673de34d16e9c087/fltk/src/prelude.rs#L475

And in `src/macros/widget.rs`:
https://github.com/fltk-rs/fltk-rs/blob/035b3e14715cfff6a1849139673de34d16e9c087/fltk/src/macros/widget.rs#L819

**Comment by MoAlyousef** [comment]
Done in master. The reasoning for the static lifetime is that FLTK expects a long-lived string for the constructor. But I get that this causes some ergonomic issues.
