### ISSUE TITLE
[BUG]mismatched types in aarch64-unknown-linux-gnu builds

### ISSUE THREAD

**Issue by cstkingkey** [fltk-rs/fltk-rs#1490]
aarch64-unknown-linux-gnu  builds

error[E0308]: mismatched types
    --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/fltk-1.4.19/src/group.rs:1463:71
     |
1463 |             unsafe { Fl_Terminal_print_char(self.inner.widget() as _, c as i8) }
     |                      ----------------------                           ^^^^^^^ expected `u8`, found `i8`
     |                      |
     |                      arguments to this function are incorrect
     |
note: function defined here

**Comment by dmm** [comment]
I just encountered this build error too. The latest git version builds fine though:

`fltk = { version = "^1.4", git = "https://github.com/fltk-rs/fltk-rs" }`

**Comment by cstkingkey** [comment]
duplicate of #1486
