### ISSUE TITLE
[BUG] group::Tabs contents not visible

### ISSUE THREAD

**Issue by undisbeliever** [fltk-rs/fltk-rs#1491]
## Describe the bug
The `group::Tabs` tabs are too tall and the content is not visible with fltk-rs-1.4.20

## To Reproduce
Run the `closable_tab` example with fltk-rs-1.4.20
`cargo run --example=closable_tab`

## Screenshots
![Screenshot_20231217_134601](https://github.com/fltk-rs/fltk-rs/assets/65687/a7119722-6885-4d44-bf7a-8207810d2332)

## Desktop info
 - OS: ArchLinux (rolling release)
 - Version: fltk-rs-1.4.20
 - Window Manager: KDE Plasma 5.27.10, wayland

## Additional info
The `tabs` example shows the widget contents, however if you increase the height of the window, the height of the tabs increase.  In this cropped screenshot the `tabs` example window height is >1500px.

![Screenshot_20231217_135458](https://github.com/fltk-rs/fltk-rs/assets/65687/b8b3f25b-9cc8-40f6-8971-9e2338c20463)

**Comment by MoAlyousef** [comment]
Hello

Thanks for the report.
I was able to reproduce the issue, and have applied a fix in the overriden resize() method, which affected Tab::auto_layout().
Can you try with the current master?
Thank you

**Comment by undisbeliever** [comment]
Thanks for the fix.
The tabs in my app work correctly with fltk-rs commit 6f5b261d643f265b806cbfdc383ac787233e8135

![Screenshot_20231217_222501](https://github.com/fltk-rs/fltk-rs/assets/65687/7dfe21c3-2002-412b-a1a4-87649a2a12c1)
