### ISSUE TITLE
[BUG] widget set_image_scaled() repeatedly causes heap corruption

### ISSUE THREAD

**Issue by skalimoi** [fltk-rs/fltk-rs#1492]
## Describe the bug
Setting a SharedImage as a widget's image multiple times crashes the program with a `(exit code: 0xc0000374, STATUS_HEAP_CORRUPTION)` error.

## To Reproduce
![imagen](https://github.com/fltk-rs/fltk-rs/assets/53193415/9432fef0-9420-4f61-ba79-259a5d3bbbfb)
This code checks whether a variable has changed or not; when it's `true`, other parts of the program generate an image that is then loaded as a SharedImage and set as the image of the widget every time.

## Expected behavior
My program is a noise generator with a preview box that updates whenever any parameter has been changed by the user, so I would expect my code to replace the image when required, since there is no method to remove the image of a widget.

## Screenshots

https://github.com/fltk-rs/fltk-rs/assets/53193415/812391d0-8109-4b67-8b9f-336ed951a6d1

![imagen](https://github.com/fltk-rs/fltk-rs/assets/53193415/38bb9c92-7408-499b-b7e4-d67d47c8b868)
![imagen](https://github.com/fltk-rs/fltk-rs/assets/53193415/fff7c0de-e0e9-4ae2-9e12-7ecc2566fec0)

## Desktop info
 - OS: Windows 11 x64

## Additional info
Full project repo is available here: https://github.com/skalimoi/OpenBTMapGen in case you want to try it by yourself.
Just clone the repo and run 

Thanks

**Comment by MoAlyousef** [comment]
Thank you for the report. 
I’ll investigate it this evening.

**Comment by MoAlyousef** [comment]
Can you try with the current master branch:

```rust
[dependencies]
fltk = { git = "https://github.com/fltk-rs/fltk-rs" }
```

It turns out SharedImage already uses refcounting for memory management.

**Comment by skalimoi** [comment]
The problem seems to be fixed, thank you very much 😀
