### ISSUE TITLE
[BUG] Segfault when changing Window background colour

### ISSUE THREAD

**Issue by 6e6f61** [fltk-rs/fltk-rs#1499]
## Describe the bug
Changing the background of a Window in a particular order causes a segmentation fault.

## To Reproduce

```rust
fn main() {
    let app = app::App::default();

    let mut wind = window::Window::new(100, 100, 100, 100, "Test");
    wind.set_color(Color::TransparentBg);
    wind.set_color(Color::from_rgba_tuple((0, 0, 0, 0)));
    
    wind.end();
    wind.show();

    app.run().unwrap();
}
```

I couldn't get a segfault to occur with any other combination of colours, only these two.

## Desktop info
Fedora 39 (X11)

**Comment by jgriffitts** [comment]
I think this is a good fix. TransparentBg is a wonky special case that breaks the rules of fltk color encoding, and this was a consequence. I have looked for other similar cases but haven't found anything.

I think converting TransparentBg to RGB is undefined behavior, and maybe should be documented as such. I wouldn't want to do a panic over this, and the proper Rust idiom would be to redefine the to_rgb() method to give Result<Color>, which would be a breaking change. The current implementation will just silently give you white. I could argue for making it black instead, but won't change anything unless someone comes up with a good strategy.
