### ISSUE TITLE
[BUG] Terminal::selection_text() never returns None

### ISSUE THREAD

**Issue by jgriffitts** [fltk-rs/fltk-rs#1502]
## Describe the bug
`selection_text()` never returns None, because Fl_Terminal_selection_text() never returns a null pointer. In case that there is no selection, Fl_Terminal_selection_text() returns Some("")

## To Reproduce
Execute `dbg!(term.selection_text());` when there is no selection, and examine the result. (This would be very easy to fix and if wanted, I will include it in my PR in progress for Terminal.

## Expected behavior
`dbg!(term.selection_text());` should show None when there is no selection.

## Desktop info
 - OS: [e.g. Windows 10 x64, macOS 10.15, Ubuntu 18.04 x64]
 - Version [e.g. 1.4.2]
 - Display server on linux (wayland or x11)

**Comment by MoAlyousef** [comment]
Interesting. Maybe the return type should be changed to `String` in that case instead of `Option<String>`?

**Comment by jgriffitts** [comment]
I am happy to make the fix. Either:

1. Make selection_text() return None if there is no selection
or 
2. Change the return type to `String`

Both of these solutions look easy, and I can make an argument for doing it either way. Any preferences?

**Comment by MoAlyousef** [comment]
I would prefer changing the return type to String. 
Thank you

**Comment by MoAlyousef** [comment]
Just a heads up, I've applied the change to the return type.
