### ISSUE TITLE
[BUG] Program crashes on start on linux on raspberry pi: [xcb] Unknown sequence number while processing queue

### ISSUE THREAD

**Issue by skalimoi** [fltk-rs/fltk-rs#1507]
## Describe the bug
Upon building and starting the program on Debian aarch64, the following error happens:
```
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
audio_server: xcb_io.c:259: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
```

## To Reproduce
Clone [this repo](https://github.com/skalimoi/OpenBTMapGen) and run on Linux.

## Desktop info
 - OS: Debian Bookworm aarch64 on Raspberry Pi.
 - Display server: X11

## Additional info
All dependencies are up to date and OS is freshly installed

Thank you

**Comment by MoAlyousef** [comment]
Hi
I built your program on my local machine and it runs without issue.
I'm wondering if it's a raspberry pi issue. Searching online I found several similar reports. 
Can you try using the `single-threaded` feature of fltk-rs.
You might also try adding to the beginning of main():
```
    extern "C" {
        pub fn XInitThreads() -> i32;
    }
    unsafe { XInitThreads(); }
```

**Comment by skalimoi** [comment]
Yes, sorry about that - I haven't had my Pi machine since last time I posted. I'm going to update you this weekend and see if your suggestions work. 🙇‍♂️

**Comment by MoAlyousef** [comment]
Hello
Just checking again on this.

**Comment by shashankx86** [comment]
Hello
Just checking again on this.
@skalimoi
