### ISSUE TITLE
[BUG] Color::from_rgbi should not map RGB values to indexes

### ISSUE THREAD

**Issue by vstojkovic** [fltk-rs/fltk-rs#1510]
## Describe the bug
In commit 9cad5704e41ec69380ab289b9317bfa20dd8a1c8, logic was added to `Color::from_rgbi` to map given RGB values to palette indexes. These RGB values map to those indexes only when working with the default palette. The new logic breaks the any code that relies on `app::set_color` and `Color::from_rgb` to change the color theme.

## To Reproduce
The following code:
```
fltk::app::set_color(0, Color::from_rgb(0xff, 0xff, 0xff));
```
becomes the equivalent of
```
fltk::app::set_color(0, Color::by_index(255));
```

## Expected behavior
`Color::from_rgb` should produce a color with the specified RGB combination. `Color::from_rgbi` should produce either a color with the specified RGB combination or with the specified index. The logic for mapping RGB values to palette indexes should be left to crate users. Alternately, a helper function could be offered that iterates through all 256 colors in the palette, calls `fltk_sys::fl::Fl_cmap` for each index, and returns the corresponding index if the RGB values match.

**Comment by MoAlyousef** [comment]
Thank you for the report.
I'll try to look closely at this tomorrow.

**Comment by vstojkovic** [comment]
The removal of the mapping logic solves this issue. The check solves #1511, but if some other user has code that relies on the assumption that `Color::from_rgbi(0).to_rgb() == (0, 0, 0)` this change will break it. Let's hope that's not the case :)

Thank you for working on this!
