### ISSUE TITLE
Support `raw-window-handle` 0.6

### ISSUE THREAD

**Issue by mkrasnitski** [fltk-rs/fltk-rs#1512]
### Is your feature request related to a problem? Please describe.
raw-window-handle 0.6 was released in October 2023, and other crates in the ecosystem have been adding support for it. For example crates like `winit` and `tao`, but also middleware such as `wgpu`, which released version 0.19 last week and bumped its supported version of rwh to 0.6. This release deprecates the `HasRawWindowHandle` and `HasRawDisplayHandle` traits in favor of safe versions named `Has{Window,Display}Handle`. However, `fltk` doesn't support these and so cannot be used with the newest version of `wgpu`.

### Describe the solution you'd like
Implementations of `Has{Window,Display}Handle` for `SingleWindow`, `DoubleWindow`, and any other types which already implement the unsafe versions from rwh 0.5. Potentially gated behind a `rwh06` feature as other crates (i.e. `winit`, `tao`) have done.

### Describe alternatives you've considered
Simply bumping the version of rwh to 0.6 would likely break things for users and would need a feature rename. Probably not worth it.

**Comment by MoAlyousef** [comment]
I have added the rwh06 feature to master. I'll be releasing a new version soon.

**Comment by MoAlyousef** [comment]
This is now released in 1.4.24. I’ve only tried on X11 and wayland and they work. On windows and macos, it builds without errors, but I haven’t tried it yet. Anyways I assume it works, since on windows it requires the hwnd and on macos it requires the NSView, whereas it used to require the NSWindow and NSView.

**Comment by mkrasnitski** [comment]
By the way, the 1.4.24 release doesn't appear in the list of GitHub releases. Just FYI.

**Comment by MoAlyousef** [comment]
Thank you for the heads up
