### ISSUE TITLE
get_selection and row_selected dont agree in TableRow

### ISSUE THREAD

**Issue by pm100** [fltk-rs/fltk-rs#1514]
ftlk-rs 1.4.24
windows 11

With TableRow set to single select mode 

If I move the selection with the mouse they agree. But If I move with the keyboard they do not

What I mean is If I used 'row_selected' to choose whether or not to highlight the row during draw_cell then the highlight does not move with key up/down

But If i do

               // let sel = t.row_selected(row); // doesnt work for keyboard
               let (rt,ct,rb,cb) = t.get_selection();
               let sel = rt == row;

its ok.

**Comment by MoAlyousef** [comment]
Can you share a minimal repro which shows the issue?

**Comment by MoAlyousef** [comment]
From the FLTK docs, it seems that to change the row_selected selection it needs a click:
https://www.fltk.org/doc-1.4/classFl__Table__Row.html#aff19cae2fe81ef59f47d2970f2275df5

i.e. row_selected() just gets a stored selection (_rowselect) from the last click or from the setter select_row(), whereas get_selection() queries the table.

**Comment by pm100** [comment]
Well thats a dumb design - but not fltk-rs's fault tho. 

Also , just for the record, if you move the selection using the keyboard, redraw is only triggered for the column that has the kb focus, so you have to call redraw in the keyboard event handler to get all columns drawn correctly

FYI. I am trying to build a ListView widget

**Comment by pm100** [comment]
@MoAlyousef  - just read the c++ code of table_row, can confirm that it maintains its own independent idea of which row(s) are selected. No relationship to what the underlying table thinks is selected
