### ISSUE TITLE
I dont see how to call FL_tile::position

### ISSUE THREAD

**Issue by pm100** [fltk-rs/fltk-rs#1516]
https://www.fltk.org/doc-1.3/classFl__Tile.html#ab7be60fce15a559b8012e59e38032d54

Its not in fltk-rs, nor is it in cfltk (I tried adding it to fltk-rs but the cfltk call isnt there)

I want to programmatically move the border between tile children. It seems that is the correct method to do it.

I could possibly implement it by lifting the code from the original c++ and redoing it in rust but I am not sure that all the data I need is available

**Comment by pm100** [comment]
OK. I worked out how to do it in pure rust. Gee that tile widget really needs to have a spilt pane widget build on top of it to make all this simpler

Still interested in why you chose not too implement it.

**Comment by MoAlyousef** [comment]
I sometimes miss some methods when writing the bindings. It seems useful to add Fl_Tile::position.

**Comment by MoAlyousef** [comment]
It appears Fl_Tile::position is deprecated, so I've added Fl_Tile::move_intersection which supposedly does the same thing.
