### ISSUE TITLE
sysmenu floats on top of other windows on ubuntu 22

### ISSUE THREAD

**Issue by pm100** [fltk-rs/fltk-rs#1517]
screen cap show it

![sysmen](https://github.com/fltk-rs/fltk-rs/assets/489231/2223d172-e769-49a0-9e69-ce96d2dbdff5)

code is here https://github.com/pm100/fltk_desk

**Comment by pm100** [comment]
on windows the menu popup disappears once focus switches to another window, so its impossible to see if th same issue exists

**Comment by MoAlyousef** [comment]
I'll have to check this on my linux machine tomorrow since menu popups appear to work correctly on WSLg. Can you share more info regarding your desktop environment. I assume Ubuntu 22 runs wayland by default, so since you don't enable the use-wayland feature, then it must be using xwayland.

**Comment by pm100** [comment]
XDG_SESSION_TYPE=wayland
XDG_CURRENT_DESKTOP=ubuntu:GNOME

Its a windows 11 system running Windows Hyper-V Hypervisor using their standard ubuntu setup. I only use it for testing. 

I use WSL too, but only in console mode, I guess I really should look into getting the gui bits set up.

**Comment by pm100** [comment]
rebuilt using use-wayland , makes no difference

I wonder if its to do with this - https://www.fltk.org/doc-1.3/classFl__Menu__Window.html#details

"By default the window is drawn in the hardware overlay planes if they are available so that the menu don't force the rest of the window to redraw."

**Comment by MoAlyousef** [comment]
I asked in fltk-general and it seems to be indeed be an issue with xwayland:
https://groups.google.com/g/fltkgeneral/c/hEoiB93usnM

**Comment by pm100** [comment]
its not ignored. I turned the feature on and it wouldnt link, I had to grab all the libraries you mention here

> use-wayland: Uses FLTK's wayland hybrid backend (runs on wayland when present, and on X11 when not present). Requires libwayland-dev, wayland-protocols, libdbus-1-dev, libxkbcommon-dev, libgtk-3-dev (optional, for the GTK-style titlebar), in addition to the X11 development packages. Sample [CI]

**Comment by MoAlyousef** [comment]
True; It causes the app to link wayland libs. However the bundled FLTK libs aren’t built for wayland. 
To benefit from the flag, you’ll have to remove the fltk-bundled flag so that FLTK can be built from source. 
The plan is to make the bundled libs hybrid at some point since this has become the default for FLTK as well.

**Comment by MoAlyousef** [comment]
It seems other X11 apps exhibit the same behavior when run on wayland, see the comment [here](https://github.com/fltk/fltk/issues/907#issuecomment-1945548987).

You can try to remove the fltk-bundled flag, and use use-wayland which should build FLTK with native wayland support.
You can also remove the feature flags, and require users to pass them how they see fit:
```
cargo build --features=fltk/fltk-bundled
# or
cargo build --features=fltk/use-wayland
```
