### ISSUE TITLE
fl_contrast_mode is not exposed

### ISSUE THREAD

**Issue by pm100** [fltk-rs/fltk-rs#1519]
https://www.fltk.org/doc-1.4/group__fl__attributes.html#ga97d26b73ccb60281ea6ae9ab94f4e9df
as far as I can see this API is not available in fltk-rs - its new in 1.4

**Comment by MoAlyousef** [comment]
I've added the api a few days ago and just got around to testing it. You can test it by trying the master branch of fltk-rs:
```rust
[dependencies]
fltk = "^1.4"

[patch.crates-io]
fltk = { git = "https://github.com/fltk-rs/fltk-rs" }
```

**Comment by pm100** [comment]
I can confirm this works - ty
![image](https://github.com/fltk-rs/fltk-rs/assets/489231/7683fbce-d41d-4e17-a99e-931ab1236f27)
