### ISSUE TITLE
FL_Tile::size_range is not exposed

### ISSUE THREAD

**Issue by pm100** [fltk-rs/fltk-rs#1523]
I would PR it myself but I dont understand how to add things to cfltk - which I think is needed

**Comment by pm100** [comment]
BTW - this is a pair of amazing project (cfltk and fltk-rs),  :-) A lot of work

**Comment by MoAlyousef** [comment]
Thank you for your kind words :)

**Comment by MoAlyousef** [comment]
I have added Tile::size_range_by_index and Tile::size_range_by_child in the current master branch.

**Comment by pm100** [comment]
ty - I confirm that these work

**Comment by pm100** [comment]
I think tile_range_by_widget is broken. It ends up calling by_index without getting the index (I only tested by_index before)

**Comment by MoAlyousef** [comment]
Thank you for testing. I’ve pushed a fix in the latest commit. Can you test it again?

**Comment by pm100** [comment]
can confirm that  this now works

**Comment by MoAlyousef** [comment]
I have also rename Tile::size_range_by_widget to Tile::size_range_by_child
