### ISSUE TITLE
Use with window viberancy

### ISSUE THREAD

**Issue by NoelJacob** [fltk-rs/fltk-rs#1531]
**Is your feature request related to a problem? Please describe.**
Is it possible to enable window vibrancy for background without OpenGL? 
[window-viberancy](https://github.com/tauri-apps/window-vibrancy) applies transparency on just the window bar on windows OS. Strangely the mica effect crashes the app. 
But, is it possible to get that transparency for the whole background?

**Describe the solution you'd like**
window-viberancy effect for the whole window background without OpenGL.

**Describe alternatives you've considered**
GLWindow and try this - https://groups.google.com/g/fltkgeneral/c/TFuVF2ItaEM

**Comment by MoAlyousef** [comment]
The issue seems related to this discussion here:
https://github.com/fltk-rs/fltk-rs/discussions/1324

For opacity, it should work for the whole window, and for vibrancy, it excludes the decorations. 
One thing you can try is to disable the decorations/border, create your own and that way it would benefit from the vibrancy effects. 
The api itself is non-documented as far as I understand, and certain effects might not be available on all platforms.

**Comment by NoelJacob** [comment]
It is actually documented - 
Use [dwmapi setwindowattribute](https://learn.microsoft.com/en-us/windows/win32/api/dwmapi/nf-dwmapi-dwmsetwindowattribute)  to set [DWMWA_SYSTEMBACKDROP_TYPE](https://learn.microsoft.com/en-us/windows/win32/api/dwmapi/ne-dwmapi-dwmwindowattribute) and [DWMSBT_MAINWINDOW](https://learn.microsoft.com/en-us/windows/win32/api/dwmapi/ne-dwmapi-dwm_systembackdrop_type). 
I probably should've showed it int window-viberancy issues.

**Comment by MoAlyousef** [comment]
Can you try the following progam:
```rust
use fltk::{prelude::*, *};

#[repr(C)]
struct Policy {
    state: u32,
    flags: u32,
    gradient: u32,
    anim: u32,
}

#[repr(C)]
struct Data {
    attrib: u32,
    pv_data: *mut (),
    cb_data: usize,
}

extern "system" {
    fn SetWindowCompositionAttribute(hwnd: *mut (), pwcad: *const Data) -> i32;
}

fn main() {
    let a = app::App::default();
    let mut w = window::Window::default().with_size(400, 300);
    w.end();
    w.show();

    let mut policy = Policy {
        state: 4, // acrylic
        flags: 0,
        gradient: 0x3b3b3b3b,
        anim: 0,
    };

    let mut data = Data {
        attrib: 0x13,
        pv_data: &mut policy as *mut _ as _,
        cb_data: std::mem::size_of_val(&policy),
    };
    
    unsafe { SetWindowCompositionAttribute(w.raw_handle() as _, &mut data as *mut _ as _); }

    a.run().unwrap();
}
```

**Comment by MoAlyousef** [comment]
That's the functions documentation, the passed data is undocumented:
https://learn.microsoft.com/en-us/windows/win32/dwm/windowcompositionattrib

The same system updated to windows11 and I get the appearance in your screenshot, whereas when I was using windows 10, I had the previous appearance. So it's not something related to FLTK. Some info can be found here in relation to the attributes:
https://gist.github.com/xv/43bd4c944202a593ac8ec6daa299b471

**Comment by NoelJacob** [comment]
With tabbed window, I've got minor success.
<img src="https://i.ibb.co/fYs10vB/Screenshot-10.png" alt="Screenshot-10" border="0">
But not having mica is killing me.
FYI: I use latest Windows.

**Comment by MoAlyousef** [comment]
The code for window transparency is defined in cfltk here:
https://github.com/MoAlyousef/cfltk/blob/27514b94e06c2133453059529aa4b663d40c8cdb/src/cfl_window.cpp#L56

I’m not sure if it affects the vibrancy code but I think it shouldn’t.

**Comment by NoelJacob** [comment]
<img src="https://i.ibb.co/X8d2xK5/Screenshot-11.png" alt="Screenshot-11" border="0">

```rust
use fltk::{prelude::*, *};

fn main() {
    let a = app::App::default();
    let mut w = window::Window::default().with_size(400, 300);
    w.set_opacity(0.0);
    w.end();
    w.show();
    
    a.run().unwrap();
}
```
Opacity 0 should make it completely transparent, right?

**Comment by MoAlyousef** [comment]
set_opacity requires the window’s handle which you won’t get until after the window is shown. 
Can you place it after the show call.

**Comment by NoelJacob** [comment]
> This seems like an issue in fltk, make sure you can create a fully transparent window using fltk then add the window-vibrancy effect.

https://github.com/tauri-apps/window-vibrancy/issues/128#issuecomment-2019284709 This is what the window-vibrancy team said. I also think that vibrancy is being applied but a color is being applied over it. Can you show an example with vibrancy window on windows and and opaque button over it?

**Comment by MoAlyousef** [comment]
I don’t believe so. The default background color is applied, then the vibrancy effect takes place. You can change the background color by either changing the window’s color or by setting app::set_background_color(). 
I don’t think you can create an opaque button on top of a transparent or vibrant window, because FLTK uses drawing routines on top of the window. It doesn’t use subwindows for its widgets.
