### ISSUE TITLE
Can you make Feature flags to select the FLTK version?

### ISSUE THREAD

**Issue by theavege** [fltk-rs/fltk-rs#1538]
**Is your feature request related to a problem? Please describe.**
I want to use the version presented in the repository of the Linux or FreeBSD distribution (for example 1.3.8) with possible limitations in capabilities.

**Describe the solution you'd like**
[dependencies]
fltk = { version = "^1.4", features = ["1.3.8"] }

**Comment by MoAlyousef** [comment]
Supporting this is possible but it would require a substantial amount of work. Made more difficult by each distro/os building FLTK with a different set of default features or being stuck at a certain version of FLTK.

**Comment by theavege** [comment]
Thank you.
