### ISSUE TITLE
[BUG] The set_image method for button don't center the image

### ISSUE THREAD

**Issue by sylm21** [fltk-rs/fltk-rs#1549]
## Describe the bug
When I assign an image via the set_image method, it does not properly center the image within the button. It's the same proble when i read a png image file.

Is it an error or a mistake on my part?

Thanks in advance

## To Reproduce
use fltk::{app, button::Button, frame::Frame, prelude::*, window::Window};
use fltk::enums::Align;
use fltk::image::Pixmap;

static OPEN_XPM: [&str; 42] = [
    "25 25 16 1",
    "     c #766E67", ".    c #817C78", "+    c #B18563", "@    c #E97E25",
    "#    c #D28445", "$    c #9D9791", "%    c #F4882A", "a    c #F1963B",
    "*    c #AFAAA3", "=    c #F4AB6E", "-    c #C8C5C1", ";    c #F2C092",
    "x    c #F7CCA4", ",    c #DEDDDA", "'    c #F3DECD", ")    c None",
    ")))))))))))))))))))))))))",
    ")))))))-..........)))))))",
    "))))))).)))))))),,*))))))",
    "))))))).)))))))),,)*)))))",
    "))))))).)))))))),-))*))))",
    "))))))).)),-,))),*--,*)))",
    "),$$$$$ ))))))))-*  $$*))",
    ")*))))).)),,,,,,--$$*-.))",
    ")*)x===+)),,,,,,,--*-,.))",
    ")*))))).),,,-,,,,,--,,.))",
    ")*))))).),,,,-*$$$$$** -)",
    ")*)),.. $$$$$*x'''''''=*)",
    ")*),+''''''''';;;;====#-)",
    ")$)-====xxxxxxx;;;;;;;+,)",
    ")$)*====;;;;;;;;;;;;;=+))",
    ")$)+====;=======aaaaaa.))",
    ")$,#===#=aaaaaaaaaaaa#.))",
    ")$-#a%%@aaaaaaaaaaaaa+.))",
    ")$+@%@%@aaaaaaaaaaaaa*.))",
    ")$#%%%%%%%%%%%%%%%%%a.*))",
    ").#@@@@@@aaaaaaaaaaa#-)))",
    ")-.                 $-,))",
    ")),,,,,,,,,,,,,,,,,,,,)))",
    ")))))))))))))))))))))))))",
    ")))))))))))))))))))))))))"
];

fn main() {
    let app = app::App::default();
    let mut wind = Window::default().with_size(400, 300);
    let mut frame = Frame::default().with_size(200, 100).center_of(&wind);
    let mut but = Button::new(160, 210, 29, 29, "");
    let open_pixmap = Pixmap::new(&OPEN_XPM).unwrap();
    //let mut img_new_proj = image::PngImage::load(&std::path::Path::new("images/icons/page.png")).unwrap();
    //img_new_proj.scale(32,32,true,true);
    wind.end();
    wind.show();

    but.set_callback(move |_| frame.set_label("Hello world"));
    //but.set_align(Align::Center);
    but.set_image(Some(open_pixmap));
    app.run().unwrap();
}

## Screenshots
![Capture d’écran 2024-05-13 171651](https://github.com/fltk-rs/fltk-rs/assets/8123018/c5996a95-fa3c-47c7-8622-560ee283a8a0)

**Comment by MoAlyousef** [comment]
You can either change `Button::new(160, 210, 29, 29, "")` to `Button::new(160, 210, 29, 29, None)`, or set the button's alignment to `Align::ImageBackdrop`.

**Comment by sylm21** [comment]
Thank you very much, with your answer it's obvious. But I hadn't managed to find any examples of this problem. I apologize for the inconvenience.

**Comment by MoAlyousef** [comment]
You're most welcome. No inconvenience at all :)
