### ISSUE TITLE
[BUG]error: process didn't exit successfully: `target\debug\fltk_test.exe` (exit code: 0xc0000139, STATUS_ENTRYPOINT_NOT_FOUND)

### ISSUE THREAD

**Issue by han1548772930** [fltk-rs/fltk-rs#1552]
rustc: rustc 1.78.0 (9b00956e5 2024-04-29)  
default: x86_64-pc-windows-msvc (default)
window:Windows 11 23H2 22631.3593

error: process didn't exit successfully: `target\debug\fltk_test.exe` (exit code: 0xc0000139, STATUS_ENTRYPOINT_NOT_FOUND)
[screenshot.zip](https://github.com/fltk-rs/fltk-rs/files/15426977/screenshot.zip)

**Comment by MoAlyousef** [comment]
More context to the issue would be helpful. I get the impression from your last issue that your application works correctly. When does this error appear?

**Comment by han1548772930** [comment]
> More context to the issue would be helpful. I get the impression from your last issue that your application works correctly. When does this error appear?

When I introduce other libraries, such as `win-screenshot`

**Comment by MoAlyousef** [comment]
I’m sorry this is not enough info. Please post a minimal reproducible example with instructions on how to reproduce the issue.

**Comment by MoAlyousef** [comment]
If you click on the executable in the target folder, you would get "GetWindowSubclass" could not be located.
This seems to arise from native-windows-gui crate that you're using. Apps built with it seem to require a windows manifest for them to use certain functionalities:
https://github.com/gabdube/native-windows-gui/issues/241
https://github.com/gabdube/native-windows-gui/issues/251
https://github.com/gabdube/native-windows-gui/issues/282
https://github.com/microsoft/windows-rs/issues/1294
https://github.com/gfx-rs/wgpu/issues/3884

**Comment by han1548772930** [comment]
Okay, thank you for taking the time to sort out the content and reply to me. It is very helpful to me.

**Comment by han1548772930** [comment]
#251
I found the fix here
