### ISSUE TITLE
Browser deselect

### ISSUE THREAD

**Issue by junetried** [fltk-rs/fltk-rs#1562]
I couldn't find any way to deselect items of a browser. The best I could find on Google for an example of deselecting browser items was [this Google Groups discussion](https://groups.google.com/g/fltkgeneral/c/t0ghSYI0jlg) which makes it seem to me that I can select item 0 to deselect items, but [this is impossible](https://github.com/fltk-rs/fltk-rs/blob/74597ea347513eb1f267bd6414384999c8b385a8/fltk/src/macros/browser.rs#L61).

I'm not sure if the solution is just to change the line I linked, I'm sure there's more to it than that. I did try changing it anyway, but couldn't get fltk to build, so that's when I just decided to open an issue. If I've missed some other way to deselect an item, I would love to be corrected.

**Comment by MoAlyousef** [comment]
FLTK provides a `Fl_Browser::select(int line, int val = 1)` method. Where the default argument of val is 1 which means select. Passing 0 would deselect. This wasn't exposed in fltk-rs.
I've now added `BrowserExt::deselect(line: i32)` which should deselect the line that's passed to the method.

**Comment by MoAlyousef** [comment]
Hi
Version 1.4.32 was released with the deselect method, as such I'll be closing this issue now.
