### ISSUE TITLE
[BUG] Font::load_font is basically useless

### ISSUE THREAD

**Issue by caesay** [fltk-rs/fltk-rs#1572]
## Describe the bug
At the moment, `Font::load_font` currently returns a String (the font family name). Normally this would be fine, because there's also a `Font::from_name(String)` method. However, since `Font::load_font` does not add the font to the `static FONTS`, it will always return Helvetica.

## To Reproduce
let font_family = Font::load_font("C:\some\path.ttf")?;
let font = Font::from_name(font_family); 
// step through this ^ function and note that from_name returns helvetica instead of the loaded font
// because it is not present in the FONTS map

## Expected behavior
Either `Font::load_font` should add loaded fonts to the `FONTS` static, or it should return a `Font` object instead of a `String` so it can directly be used in widgets.

**Comment by MoAlyousef** [comment]
That is difficult to change, since it's how FLTK works.
The Font enum is fixed, FLTK allows loading a font and replacing one of the enum values to that font.
Similarly with colors:
```rust
app::set_color(Color::Red, 255, 255, 255);
```
Now if you use Color::Red, it will be white since we pass (255, 255, 255).

Back to fonts, FLTK does allow getting the loaded font's name using `app::get_font`:
```rust
    let myfont = Font::load_font("/usr/share/fonts/truetype/noto/NotoMono-Regular.ttf").unwrap();
    Font::set_font(Font::Helvetica, &myfont);
    println!("{}", app::get_font(Font::Helvetica));
```
Which would print `Noto Mono`.

**Comment by caesay** [comment]
I understand the pattern now. I did end up resorting to app.load_font instead, however, as it did not require me to replace a font. How might one go about using a Variable font? It seems I'm expected to load a font of the desired weight (eg. `NotoMono-Regular.ttf`), but Variable fonts contain information about how to render their glyphs at different sizes so there is no specific file to load. Would there be a way to specify this when setting the font in a widget, or in a custom draw routine?

**Comment by MoAlyousef** [comment]
I don't think FLTK supports variable fonts.
You can use a custom draw routine to rasterize text (using an external crate that supports variable font shaping), and use the resulting image as the widget's label.
