### ISSUE TITLE
Window::set_on_top improvements

### ISSUE THREAD

**Issue by caesay** [fltk-rs/fltk-rs#1573]
The current code for Window::set_on_top is as follows:

```rust
    pub fn set_on_top(&self) {
        #[cfg(target_os = "macos")]
        {
            extern "C" {
                pub fn cfltk_setOnTop(handle: *mut raw::c_void);
            }
            assert!(self.border());
            unsafe {
                cfltk_setOnTop(self.raw_handle());
            }
        }
    }
```

The `assert!(self.border());` is unnecessary. I tested by calling `cfltk_setOnTop` directly on a window which has a border, and the window correctly stays on top of others and also has a border present. 

Also, it would be nice if there was implementations for Linux/Windows. 

I try to put a PR together for this in the next couple of days.

**Comment by MoAlyousef** [comment]
A PR would be nice. 
If you can check with a window that has no border I would be grateful. I remember it didn’t work with borderless windows on macos.
