### ISSUE TITLE
[BUG] Unable to build on Intel x86_64 macOS with bundled libraries feature

### ISSUE THREAD

**Issue by Postrediori** [fltk-rs/fltk-rs#1578]
## Build failures

Build on Intel macOS with fltk-bundled fails because there are no `*.o` files for this architecture in the fltk_sys library:

```
  = note: ld: warning: directory not found for option '-L/Users/user/projects/UiTest/target/debug/build/fltk-sys-61bda0b966b391a4/out/build'
          ld: warning: directory not found for option '-L/Users/user/projects/UiTest/target/debug/build/fltk-sys-61bda0b966b391a4/out/build/Release'
          ld: warning: directory not found for option '-L/Users/user/projects/UiTest/target/debug/build/fltk-sys-61bda0b966b391a4/out/lib64'
          ld: warning: directory not found for option '-L/Users/user/projects/UiTest/target/debug/build/fltk-sys-61bda0b966b391a4/out/lib/Release'
          ld: warning: directory not found for option '-L/Users/user/projects/UiTest/target/debug/build/fltk-sys-61bda0b966b391a4/out/lib64/Release'
          ld: in /Users/user/projects/UiTest/target/debug/deps/libfltk_sys-2fd411ae420fcd0d.rlib(cfl_image.cpp.o), archive member 'cfl_image.cpp.o' with length 36112 is not mach-o or llvm bitcode for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
          

error: could not compile `ui_test` (bin "ui_test") due to 1 previous error
```

Build log with `cargo build -vv`: [build.log.zip](https://github.com/user-attachments/files/16716322/build.log.zip)

Screenshot: ![Screenshot 2024-08-22 at 21 22 05](https://github.com/user-attachments/assets/a833c2ec-06ff-4a5b-8fc1-0c3f15633893)

It seems that library file `libfltk_sys-2fd411ae420fcd0d.rlib` has only `.o` files for arm64 macOS. For example unpacking this file with `ar`:

```
mkdir test && cd test
ar -x /Users/user/projects/UiTest/target/debug/deps/libfltk_sys-2fd411ae420fcd0d.rlib
for f in $( ls *.o ); do file $f; done
```

shows the following:

```
Fl.cxx.o: Mach-O 64-bit object arm64
Fl_Adjuster.cxx.o: Mach-O 64-bit object arm64
Fl_Anim_GIF_Image.cxx.o: Mach-O 64-bit object arm64
Fl_BMP_Image.cxx.o: Mach-O 64-bit object arm64
Fl_Bitmap.cxx.o: Mach-O 64-bit object arm64
Fl_Box.cxx.o: Mach-O 64-bit object arm64
Fl_Browser.cxx.o: Mach-O 64-bit object arm64
Fl_Browser_.cxx.o: Mach-O 64-bit object arm64
...
```

As far as I tested in versions 1.4.9 and before the file `libfltk_sys-<>.rlib` had proper x86_64 libraries:

```
Fl.cxx.o: Mach-O 64-bit object x86_64
Fl_Adjuster.cxx.o: Mach-O 64-bit object x86_64
Fl_Anim_GIF_Image.cxx.o: Mach-O 64-bit object x86_64
Fl_BMP_Image.cxx.o: Mach-O 64-bit object x86_64
Fl_Bitmap.cxx.o: Mach-O 64-bit object x86_64
Fl_Box.cxx.o: Mach-O 64-bit object x86_64
Fl_Browser.cxx.o: Mach-O 64-bit object x86_64
Fl_Browser_.cxx.o: Mach-O 64-bit object x86_64
Fl_Browser_load.cxx.o: Mach-O 64-bit object x86_64
...
```

## To Reproduce

Build minimal project: [UiTest.zip](https://github.com/user-attachments/files/16716294/UiTest.zip)

Add library with fltk-bundled feature to Cargo.toml:

```toml
[dependencies]
fltk = { version = "1", features = ["fltk-bundled"] }
```

Use the minimal sample from the documentation:

```rust
use fltk::{app, prelude::*, window::Window};

fn main() {
    let app = app::App::default();
    let mut wind = Window::new(100, 100, 400, 300, "Hello from rust");
    wind.end();
    wind.show();
    app.run().unwrap();
}
```

## Desktop info

Checked on the following systems:

Setup 1
 - OS: macOS 11.7.10 x86_64
 - Xcode 13.2.1, clang 13.0.0
 - rustc 1.80.1

Setup 2
 - OS: macOS 10.15.7 x86_64
 - Xcode 12.4, clang 12.0.0
 - rustc 1.80.1

**Comment by MoAlyousef** [comment]
Thanks for the detailed report. It seems github’s macos-latest runner (which is used to provide bundles) now defaults to aarch64:
https://github.com/actions/runner-images/issues/9741

I’ll downgrade to macos-13 and provide a new bundle hopefully by tomorrow.

**Comment by MoAlyousef** [comment]
I've uploaded an updated bundle. Can you try it out?
You might have to `cargo clean` first.

**Comment by Postrediori** [comment]
Yes, now it builds normally:
![Screenshot 2024-08-23 at 12 50 51](https://github.com/user-attachments/assets/34c25db4-0d33-4a6b-84bd-e945c131c78c)

Thanks!
