### ISSUE TITLE
[BUG] Clear or delete widget pauses application execution

### ISSUE THREAD

**Issue by kjlaw89** [fltk-rs/fltk-rs#1580]
## Describe the bug
Clearing a container (i.e. a flex widget) and attempting to draw new widgets inside of it pauses application execution until an external event (like keyboard or mouse movement) occurs.

## To Reproduce
Here's a minimal application to reproduce using only the fltk library:

```rust
use fltk::{app, enums::Color, frame::Frame, group::Flex, prelude::*, window::Window};
use std::{cell::RefCell, rc::Rc};

fn main() {
    let app = app::App::default();
    let count = Rc::new(RefCell::new(0));
    let mut wind = Window::default().with_size(240, 260).with_label("Counter");
    wind.set_color(Color::White);

    let mut flex = Flex::default_fill().column();
    Frame::default().with_label(&count.borrow().to_string());
    flex.end();
    wind.end();
    wind.show();

    // Clear the flex container and redraw the counter widget every second
    app::add_timeout3(1.0, move |handle| {
        *count.borrow_mut() += 1;

        flex.clear();
        flex.begin();
        Frame::default().with_label(&count.borrow().to_string());
        flex.end();
        flex.redraw();
        app::repeat_timeout3(1.0, handle);
    });

    app.run().unwrap();
}
```

## Expected behavior
Using flex.clear(), or removing the existing counter widget and deleting it, then redrawing a new widget would immediately draw instead of pausing execution. This works in fltk 1.4.18 but compiling in general is broken from 1.4.19 to 1.4.30, so I'm not sure where it was actually broken.

## Desktop info
 - OS: Windows 11, Ubuntu 20.04 Armv7
 - Version: 1.4.30+ (1.4.19-1.4.29 won't compile)
 - Display server on linux (wayland or x11): X11

**Comment by MoAlyousef** [comment]
The add_timeout function effectively schedules something on a different thread.
FLTK has a limitation when calling draw from different threads than the UI thread, and requires a manual call to `app::awake`:
```rust
    app::add_timeout3(1.0, move |handle| {
        app::awake(); // <-- here
        *count.borrow_mut() += 1;
        flex.clear();
        flex.begin();
        Frame::default().with_label(&count.borrow().to_string());
        flex.end();
        flex.redraw();
        app::repeat_timeout3(1.0, handle);
    });
```

**Comment by kjlaw89** [comment]
Ahh, that makes sense. That seems to have fixed my issue, thanks! Might not hurt to call that out in the documentation for those functions. At least it'll come up in searches now, so it's called out somewhere 😄.
