### ISSUE TITLE
Rounding Corners of a Widget

### ISSUE THREAD

**Issue by khaki-git** [fltk-rs/fltk-rs#1583]
Hello, I'm new to rust and came from Python. Back over at Python, we had `customtkinter`, a fork of `tkinter` which provided high quality user interfaces in ~seconds~ a very short period of time.

One of the main reasons why it was so good is because the widgets had ***rounded corners***, which looks modern.

Thank you.

**Comment by MoAlyousef** [comment]
Hello
Sorry for the late reply.

FLTK offers certain schemes which are built into the library:
`base, gtk+, plastic, gleam, oxy`.

You can also find additional schemes and themes here:
https://github.com/fltk-rs/fltk-theme

If you would like to use a flat scheme with rounded corners, it might be as simple as defining your own scheme:
```rust
use fltk::{prelude::*, enums::*, *};

fn main() {
    let app = app::App::default();
    // global theming
    app::background(55, 55, 55); // background color. 
	// For input/output and text widgets, use app::background2
	app::background2(0, 0, 0);
    app::foreground(255, 255, 255); // labels
    app::set_font_size(16);
    app::set_frame_type2(FrameType::UpBox, FrameType::RFlatBox);
    app::set_frame_type2(FrameType::DownBox, FrameType::RFlatBox);
    app::set_visible_focus(false);

    // regular widget code
    let mut win = window::Window::default().with_size(400, 300);
    let mut flex = group::Flex::default_fill().column();
	flex.set_margins(100, 60, 100, 60);
	flex.set_pad(10);
    let mut btn1 = button::Button::default().with_label("Increment");
	btn1.set_color(Color::Red.darker());
	btn1.set_selection_color(Color::Red.darker().darker());
	let mut out = output::Output::default();
	out.set_value("0");
	let mut btn2 = button::Button::default().with_label("Decrement");
	btn2.set_color(Color::Red.darker());
	btn2.set_selection_color(Color::Red.darker().darker());
    flex.end();
    win.end();
    win.show();

    app.run().unwrap();
}
```
![image](https://github.com/user-attachments/assets/54dd8c81-5d83-4db1-9d64-68e896586b23)

**Comment by khaki-git** [comment]
Thx alot!
