### ISSUE TITLE
Add API to access URI functions from Rust

### ISSUE THREAD

**Issue by diegoefe** [fltk-rs/fltk-rs#1587]
I would like to be able to use a couple of functions included in C++ library:
- void fl_decode_uri (char *uri)
- int fl_open_uri(const char *uri, char *msg, int msglen)

There are other functions in the **File names and URI utility functions** module (please look [here](https://fltk.gitlab.io/fltk/group__filenames.html) or [here](https://www.fltk.org/doc-1.3/group__filenames.html)) and I assume they where not included because Rust already has that functionality natively, but this two are very handy.

Thanks in advance!

**Comment by MoAlyousef** [comment]
I've added these 2 under utils as open_uri and decode_uri.

**Comment by diegoefe** [comment]
Awesome, thanks!

**Comment by diegoefe** [comment]
Please take a look the return value of fltk::utils::open_uri() the return value is wrongly checked
According to FLTK documentation the functions succeeds when the return value is 1.
In the current code (revision da0f4fc7e0279a9e3e69f8a7ffa1e3ccc80d459a) the check is:
```rust
...
        let ret = Fl_open_uri(s.as_ptr(), v.as_mut_ptr() as _, 255);
        if ret != 0 {
            Err(FltkError::Unknown(String::from_utf8(v)?))
        } else {
            Ok(())
        }
...
```
[Here](https://github.com/fltk-rs/fltk-rs/blob/da0f4fc7e0279a9e3e69f8a7ffa1e3ccc80d459a/fltk/src/utils/mod.rs#L122)'s the link to fltk-ui code
[Here](https://fltk.gitlab.io/fltk/group__filenames.html#gaa703a16e265f609bedbaf0930dbcd0d7)'s the FLTK documentation

**Comment by MoAlyousef** [comment]
I've pushed a fix if you can try it after a `cargo update`.

**Comment by diegoefe** [comment]
Thanks, it works
