### ISSUE TITLE
Syntax Highlighting?

### ISSUE THREAD

**Issue by khaki-git** [fltk-rs/fltk-rs#1591]
Hello, I'd like to make an IDE/Code Editor in FLTK-RS, but (I think) there is no support for highlighting specific segments in a Text Box.

Can you add support for highlighting certain parts of text in a Text Box?

**Comment by MoAlyousef** [comment]
Hello
It's possible using TextEditor and TextDisplay.
https://github.com/fltk-rs/fltk-rs/blob/master/fltk/examples/format_text.rs

I have a minimal editor here which uses fltk-rs and treesitter for syntax highlighting:
https://github.com/MoAlyousef/red
