### ISSUE TITLE
[BUG] Cannot find a way to clear/recalc/redraw a Flex layout.

### ISSUE THREAD

**Issue by AllenDang** [fltk-rs/fltk-rs#1607]
## Describe the bug
After add child or clear all children of a flex layout, I want to refresh the flex layout, but I cannot find a way to do it.

## To Reproduce
Here is the minimal repo project
[flex_clear_test.zip](https://github.com/user-attachments/files/17730191/flex_clear_test.zip)

1. cargo run
2. click "add" button multiple times, you will notice the flex layout is not completely refreshed.
3. click "clear" button, the refresh still doesn't happen.

## Expected behavior
Flex layout could be refreshed correctly.

## Screenshots
![demo](https://github.com/user-attachments/assets/32910cb7-c7b9-4600-b9f7-39e8969c2071)

## Desktop info
 - OS: macOS 15
 - Version: 1.4.35

**Comment by MoAlyousef** [comment]
Thanks for the report.
You can set the flex_container's FrameType to FlatBox. Then you wouldn't need to call recalc or set_damage. Clearing the Flex would still require a call to redraw:
```rust
use fltk::{
    app::{channel, App, Scheme},
    button::Button,
    group::Flex,
    prelude::{WidgetBase, GroupExt, WidgetExt, WindowExt},
    window::*,
    enums::*,
};

#[derive(Clone)]
enum Message {
    Add,
    Clear,
}

fn main() {
    let app = App::default().with_scheme(Scheme::Gtk);

    let (s, r) = channel::<Message>();

    let mut win = Window::default().with_size(400, 400);
    let mut col = Flex::default_fill().column();
    let row = Flex::default().row();
    let mut btn_add = Button::default().with_label("Add");
    let mut btn_clear = Button::default().with_label("Clear");
    row.end();
    col.fixed(&row, 30);
    let mut flex_container = Flex::default().column();
    flex_container.set_frame(FrameType::FlatBox);
    flex_container.end();
    col.end();
    win.end();
    win.show();

    btn_add.emit(s.clone(), Message::Add);
    btn_clear.emit(s.clone(), Message::Clear);


    while app.wait() {
        if let Some(msg) = r.recv() {
            match msg {
                Message::Add => {
                    let btn = Button::default().with_label("New Button");
                    flex_container.add(&btn);
                }
                Message::Clear => {
                    flex_container.clear();
                    flex_container.redraw();
                }
            }
        }
    }

    app.run().unwrap();
}
```

**Comment by AllenDang** [comment]
@MoAlyousef Thanks, is setting the flex_container's FrameType to FlatBox the only work around now? Is this a bug? or it is designed this way?

**Comment by MoAlyousef** [comment]
Another workaround is to redraw the flex_container's parent. Flex widgets (like most Group widgets) by default have a NoBox FrameType (so not a bug), that means modifying the drawing of the Flex, can lead to drawing artifacts in the parent.

**Comment by AllenDang** [comment]
@MoAlyousef Got it.
