### ISSUE TITLE
Migrating to 1.0

### ISSUE THREAD

**Issue by MoAlyousef** [fltk-rs/fltk-rs#612]
Version 1.0.0 has been released. You can change the version to "1" in your Cargo.toml, and you might have to run `cargo update` in your project root.

There are several "minor" breaking changes, however, the bigger ones might require some guidance which will hopefully be added in this issue.
1- The first of the bigger changes is the import defaults. The prelude and enums modules were imported implicitly when importing `fltk::*` or any other module within the crate. They now require explicit imports:
```rust
use fltk::*;
```
Becomes
```rust
use fltk::{prelude::*, enums::*, *}; // depending on what's needed
```
Granular imports should just add
```rust
use fltk::{enums::*, prelude::*};  // depending on what's needed
```
This should fix most breaks in the build.

2- FLTK expects widget constructors to pass a static (long lived) string, meaning FLTK will not delete it. So the crate now also expects a `&'static str` with the ::new() method. If you were using string literals you're ok. Otherwise for dynamic strings (which should be deleted), use the with_label constructor or set_label:
```rust
let but1 = button::Button::new(0, 0, 80, 40, "Click me!");
let x = some_val();
let but2 = button::Button::new(0, 0, 80, 40, &format!("{}", x));
```
becomes
```rust
let but1 = button::Button::new(0, 0, 80, 40, "Click me!");
let x = some_val();
let but2 = button::Button::new(0, 0, 80, 40, None).with_label(&format!("{}", x));
```

3- Callback-taking methods had overloads which took a `&mut self` and were indicated with a `2` in their signatures. Now these overloads have become the default:
```rust
but1.set_callback(|| println!("Works"));
but2.set_callback2(|b| b.set_label("Works"));
```
becomes
```rust
but1.set_callback(|_| println!("Works"));
but2.set_callback(|b| b.set_label("Works"));
```

The same applies to handle2, draw2 and draw_cell2:
```rust
but1.handle(|ev| { /* logic */ });
but2.handle2(|b, ev| { /* logic */ });
```
becomes
```rust
but1.handle(|_, ev| { /* logic */ });
but2.handle(|b, ev| { /* logic */ });
```

**Comment by dheijl** [comment]
Makes the imports a lot cleaner, and I also the callback/callback2 merge!!
