### ISSUE TITLE
Issue with custom event handling

### ISSUE THREAD

**Issue by wyhinton** [fltk-rs/fltk-rs#660]
Hello!

I was working on implementing one of the [examples](https://github.com/fltk-rs/fltk-rs/discussions/618) you so kindly provided over on the discussions pages and think I may have come across a bug. When using ```app::handle_main(MyEvent::BUTTON_CLICKED)``` I can't seem to correctly compare a custom enum code (like ```BUTTON_CLICKED```) to the event captured in ```win.handle(wind, ev)```.  If ```BUTTON_CLICKED = 40```, debugging confirms as much, however debugging ```ev == 40 ``` returns ```false```. Using different values for MyEvent::BUTTON_CLICKED didn't seem to correct this. Maybe I'm just missing something obvious here.

Platform: Windows 10
```lang-rust
//fltk = "1.0.8"
use fltk::{prelude::*, *, enums::*};
use std::rc::Rc;
use std::cell::RefCell;

pub struct MyEvent;

impl MyEvent {
    const BUTTON_CLICKED: i32 = 40; // values below 30 are reserved
}

pub struct MyButton {
    but: button::Button,
}

impl MyButton {
    pub fn new() -> Self {
        let mut but = button::Button::new(160, 200, 80, 40, "Inc");
        but.set_callback(|_| {
            dbg!("doing but cb");
            let _ = app::handle_main(MyEvent::BUTTON_CLICKED);
        });
        MyButton{
            but: but1
        }
    }
}
pub struct MyWindow {
    win: window::Window,
}

impl MyWindow {
    pub fn new() -> Self {
        let mut win = window::Window::default().with_size(400, 300);
        let but = MyButton::new();
        win.show();
        win.end();
        // win.handle(move|_,ev|{
        //     dbg!(ev as i32);
        //     dbg!(ev as i32 == 40);
        //     dbg!(ev as i32 == MyEvent::BUTTON_CLICKED);
        //     //ev as i32 = 40
        //     //ev as i32 == 40 == false
        //     //ev as i32 == MyEvent::BUTTON_CLICKED == false
        //     true
        // });
        win.handle(move |_, ev| if ev as i32 == MyEvent::BUTTON_CLICKED {
            dbg!("button clicked");
            true
        } else {
            false
        });
        MyWindow{
            win: win
        }
    }
}

fn main() {
    let app = app::App::default();
    let _win = MyWindow::new();
    app.run().unwrap();
}

```

**Comment by dheijl** [comment]
It seems like I stumbled on the same problem some months ago, worked around it and forgot to file an issue:

```rust
        wind.handle(move |_, _ev| {
            //eprintln!("{:?}", app::event());
            let ev = app::event();
            match ev {
                Event::Close => {
                    app.quit();
                    std::process::exit(0);
                }
                _ => false,
            }
        });
```

**Comment by MoAlyousef** [comment]
Hmm I'm not sure if it's a platform issue, I'll look closer into it.
But uncommenting 
```rust
        win.handle(move|_,ev|{
             dbg!(ev as i32);
             dbg!(ev as i32 == 40);
             dbg!(ev as i32 == MyEvent::BUTTON_CLICKED);
             true
         });
```
I do get the expected values:
[fltk\examples\temp.rs:38] ev as i32 = 40
[fltk\examples\temp.rs:39] ev as i32 == 40 = true
[fltk\examples\temp.rs:40] ev as i32 == MyEvent::BUTTON_CLICKED = true

Do notice though that the event values in the closure change quickly even based on simple mouse movements, so you would quickly get a new event which returns false.

Also not all events are stored in FLTK's event queue which can be queried by the app::event() call, (like mouse movements), meanwhile the handle call passes in all events including mouse movements. 
Also some default events can be triggered before others:
```rust
        wind.handle(move |_, ev| {
            match ev {
                Event::Hide => {
                    println!("invoked before Event::Close and closes the window, so the Close handler isn't called");
                    app::quit();
                    std::process::exit(0);
                }
                _ => false,
            }
        });
```

**Comment by dheijl** [comment]
You're right: the Hide event was the cause for me. I missed that at the time and came to the wrong conclusion.

**Comment by wyhinton** [comment]
@MoAlyousef you didn't find this to an OS specific issue?

**Comment by MoAlyousef** [comment]
Not really. On Windows and Linux (WSL) I get the expected output.
