### ISSUE TITLE
Please see my app and if possible add this in examples.. 

### ISSUE THREAD

**Issue by santokalayil** [fltk-rs/fltk-rs#661]
This project is only in the beginning state. But this will help others to have some idea regarding how console window is hidden, how app_icon is set and how window icon is set etc. it is a login model one...

please add my app and the code if possible in the  examples. Also if possible please add this in explaining the concepts in your youtube videos. Please go through my code and suggest me some corrections if there is. Please know that I have ignored the warning for the time being.. My app is only in the beginning stage only. I also need to know how new login window is closed and trigger a new window of real data content. 
https://github.com/santokalayil/AppDev_rust_fltk

![image](https://user-images.githubusercontent.com/49450970/117538101-2caf6180-b022-11eb-8033-4c65364f4573.png)

**Comment by MoAlyousef** [comment]
Hi
Thanks for the contribution. I can add it to the fltk-rs/demos repo or add a link in the Project Showcase linking to your repo. Adding the example to the examples directory requires that it be standalone and with no external dependencies. I'll fork it and make changes which reflect the 1.0 version of the crate.

**Comment by santokalayil** [comment]
Hi, Does "with no external dependencies" mean that I cannot have any external dependencies other than fltk or I should combine the modules inside my project to create a single main.rs file?

**Comment by santokalayil** [comment]
I have made few changes as well after merging your pull request. I am planning to add firebase support also for login and other data..
Please help me to write code that can open a new window closing this login window after sucessful login.

**Comment by santokalayil** [comment]
Then, please add a link in the Project Showcase linking to my repo. Also please give me instructions if anything more to be needed as a showcase project.

**Comment by santokalayil** [comment]
Please know I am further developing this app to include more features.

**Comment by MoAlyousef** [comment]
Sure will do.

**Comment by santokalayil** [comment]
Thank you very much
