### ISSUE TITLE
[BUG] bad link in the documentation

### ISSUE THREAD

**Issue by jpggithub** [fltk-rs/fltk-rs#677]
The bug is on the documentation https://docs.rs/fltk/1.0.12/fltk/
The link given in "For the remainder of the code, check the full example here." is bad (https://github.com/fltk-rs/fltk-rs/blob/master/examples/counter2.rs).

It should be https://github.com/fltk-rs/fltk-rs/blob/master/fltk/examples/counter2.rs (note the /fltk/ before /examples/counter2.rs)

**Comment by MoAlyousef** [comment]
Thank you. I've fixed it now in master and should reflect in the next release 1.0.13.
