### ISSUE TITLE
Why this error while compiling app?

### ISSUE THREAD

**Issue by santokalayil** [fltk-rs/fltk-rs#702]
![image](https://user-images.githubusercontent.com/49450970/120071033-f1490580-c0aa-11eb-8a6d-b8018856c6f4.png)
![image](https://user-images.githubusercontent.com/49450970/120071047-045bd580-c0ab-11eb-9827-fffab4e8bfcf.png)

**Comment by MoAlyousef** [comment]
Please provide enough info. The project used to build then it didn't? What changed in your project? Did you try to `cargo clean` then rebuild?

**Comment by santokalayil** [comment]
thank you it worked..
