### ISSUE TITLE
question: clear widgets from a  group

### ISSUE THREAD

**Issue by 20iahazban** [fltk-rs/fltk-rs#703]
when I'm using unsafe_clear() method on a Scroll ironically everything is okay.
when I'm using clear() my app crashes
could someone explain to me what is the difference? :D

**Comment by venand** [comment]
Hi
What’s the crash message?

**Comment by MoAlyousef** [comment]
Hi
What’s the crash message?

**Comment by 20iahazban** [comment]
hi, nothing on the console... it just stops working

**Comment by MoAlyousef** [comment]
I’ll try to reproduce. In essence, unsafe_clear calls fltk’s clear which isn’t thread safe. GroupExt::clear calls delete on each widget and sets the internal pointer to null. 

Just a guess, if you’re on Windows and using substsystem=windows it could be crashing from an assert trying to use a deleted widget. Do you have a minimal reproducible example I can try?

**Comment by 20iahazban** [comment]
Thank you very much for the answer. I'm on windows but Im not using the subsystem stuff. I will create a minimal example tomorrow morning.

**Comment by 20iahazban** [comment]
[main.zip](https://github.com/fltk-rs/fltk-rs/files/6574344/main.zip)
now i have an error message : (exit code: 0xc0000374, STATUS_HEAP_CORRUPTION)

i know i use unsafe so... its kinda my fault, but i went with raw pointers because for now i would like to focus on the UI part only

**Comment by MoAlyousef** [comment]
Hmm it seems FLTK's Scroll widget is special in that it already has 2 children (a horizontal and vertical scrolls), which GroupExt::clear doesn't account for!
I'll see what can be done to fix this.

**Comment by MoAlyousef** [comment]
This should be fixed in master. I'll publish a new version this evening.
