### ISSUE TITLE
[BUG]Custom Event Not Handled in release build of app

### ISSUE THREAD

**Issue by wyhinton** [fltk-rs/fltk-rs#704]
Hello, and thank you for all the wonderful work going on with this project! One issue I keep running into is the inability to successfully capture a custom event. See this example (taken from the discussion board):

```rust
//fltk = "^1.0"
//OS: Win10

use fltk::{prelude::*, *};
use std::rc::Rc;
use std::cell::RefCell;

pub struct MyEvent;

impl MyEvent {
    const BUTTON_CLICKED: i32 = 40; // values below 30 are reserved
    const FRAME_CHANGED: i32 = 41;
}

pub struct MyButton {
    but: button::Button,
}

impl MyButton {
    pub fn new() -> Self {
        let mut but = button::Button::new(160, 200, 80, 40, "Inc");
        but.set_callback(|_| {
            let _ = app::handle_main(MyEvent::BUTTON_CLICKED);
        });
        Self { but }
    }
}

pub struct MyFrame {
    frame: frame::Frame,
    counter: Rc<RefCell<i32>>,
}

impl MyFrame {
    pub fn new() -> Self {
        let mut frame = frame::Frame::default().size_of_parent().with_label("0");
        let counter = Rc::from(RefCell::from(0));
        let c = counter.clone();
        frame.handle(move |f, ev| if ev as i32 == MyEvent::BUTTON_CLICKED {
            *c.borrow_mut() += 1;
            f.set_label(&format!("{}", c.borrow()));
            let _ = app::handle_main(MyEvent::FRAME_CHANGED);
            true
        } else {
            false
        });
        Self { frame, counter }
    }
    pub fn count(&self) -> i32 {
        *self.counter.borrow()
    }
}

pub struct MyWindow {
    win: window::Window,
}

impl MyWindow {
    pub fn new() -> Self {
        let mut win = window::Window::default().with_size(400, 300);
        let frame = MyFrame::new();
        let but = MyButton::new();
        win.show();
        win.end();
        win.handle(move |_, ev| if ev as i32 == MyEvent::FRAME_CHANGED {
            println!("Frame changed to value {}", frame.count());
            true
        } else {
            false
        });
        Self { win }
    }
}

fn main() {
    let app = app::App::default();
    let _win = MyWindow::new();
    app.run().unwrap();
}
```
The value of ```counter``` does not change, and I can't see that ```BUTTON_CLICKED``` is captured anywhere. I know we discussed this issue in issue [#660](https://github.com/fltk-rs/fltk-rs/issues/660), but I'm still not understanding why this example isn't working. Any thoughts?

**Comment by MoAlyousef** [comment]
Hi 
Thank you.

It's strange, the example runs correctly for me with both msvc and gnu toolchains. Is the example above not incrementing the counter, is nothing being printed on the command line? or is it regarding another application with multiple windows. `app::handle_main` basically sends events to the main window, for dispatching events across windows, `app::handle(i32, window)` can be used.
Also anything special with your environment?

**Comment by wyhinton** [comment]
It is neither incrementing the counter, or printing on the command line. No this issue regards only the above code. 
Nothing special about my env as far as I can tell. I can test on OSX soon. 


```
//.toml
[package]
name = "template"
version = "0.1.0"
authors = ["wyhinton <wyhinton189@gmail.com>"]
edition = "2018"
description = "my application"


[dependencies]
fltk = "^1.0"
```

Device:
```
Processor: AMD Ryzen 7 2700 8-core
Ram: 32Gb
System type: 64-bit operating system, x64-based processor
```
Widows Info:
```
Edition: Windows 10 Pro
Version: 2004
OS build: 19041.329
Exeperience: Windows Feature Experience Pack 120.2202.130.0
```
Are their any other logs of system info you'd like? I'm stumped.

**Comment by eadf** [comment]
I'll save you some time.. the example works on MacOS M1

**Comment by wyhinton** [comment]
Aha! I'd been using ```cargo run --release```, but building with ```cargo run``` works. Weird. I imagine this is still a bug. Thanks @eadf for the suggestion.

**Comment by eadf** [comment]
Good that you got it running.. but yeah. `--release` should not make the code behave any differently, just faster.

Just checked, running the code on MacOs with `--release` gives the same error.

**Comment by eadf** [comment]
```
      ...
      but.set_callback(|_| {
            let e = app::handle_main(MyEvent::BUTTON_CLICKED);
            dbg!(e);
        });
       ...
```
Results in `Ok(false)` i.e event *not* handled when `--release` is used. `Ok(false)` w/o `--release`

**Comment by Ar37-rs** [comment]
eadf @ yup, casting non-primitive type to primitive type is  a problem. must use into(), unless primitive to primitive.

**Comment by wyhinton** [comment]
On thoughts on why ```--release``` causes this issue? As @eadf mentioned, shouldn't ```--release``` just optimize our app? Is this a quirk of the rust compiler, or something to do with FLTK?

**Comment by MoAlyousef** [comment]
hmm I didn't expect that, since Event has a repr i32 and things work fine in debug mode. Nice catch tho @eadf. I've added an impl `From<i32>` for Event which would make things a bit more ergonomic:

`if ev == MyEvent::FRAME_CHANGED.into()`

**Comment by eadf** [comment]
@wyhinton My guess is that the assignment `let e:i32 = ev as i32` is optimized away when `--release` is used, instead the compiler is referring directly to the source: `ev`. 
I have no clue about why `ev as i32 == MyEvent::BUTTON_CLICKED` doesn't work however. 

@Ar37-rs If casting a non-primitive type to primitive type is a known problem, one could wonder why clippy doesn't warn about this...

**Comment by Ar37-rs** [comment]
@MoAlyousef awesome thank you, "if ev.bits() == MyEvent::FRAME_CHANGED {...}" working fine now.
@eadf i don't know, but now clippy  recognizes casting "ev as i32" as an error rustc(E0605).
