### ISSUE TITLE
Bindings for Additional FL Event Handling Functions

### ISSUE THREAD

**Issue by wyhinton** [fltk-rs/fltk-rs#720]
Hello again, 

I was wondering if some of the following FL [event handling functions](https://www.fltk.org/doc-1.4/group__fl__events.html#gad87427a41cb546d97236c244abaff8bd) might be added into fltk-rs:

- FL::event_clipboard()
- Fl::event_clipboard_type()
- FL::event_dispatch() //<-- is this the same as fltk::app::add_handler?

**Comment by MoAlyousef** [comment]
Hello

Sure. I’m a bit busy these few days (moving to a new apartment, so it might take some time). 

As I understand it, add_handler handles unhandled events. event_dispatch adds a handler to intercept events before they reach widgets’ handlers, the event can then be forwarded (dispatched) via Fl::handle_(event, window);

**Comment by MoAlyousef** [comment]
I've added the following methods:
- app::event_clipboard() and event_clipboard_type() (can be handled in Event::Paste).
- app::handle_main_(event), handle_(event, window) and event_dispatch(fn(event, window) -> bool)

I still have a lot more testing to do to see if the implementation is safe and if everything is working correctly.

**Comment by MoAlyousef** [comment]
So handle_ was renamed to handle_raw, and both handle_raw and event_dispatch were marked unsafe. The reason is that plugging into FLTK's event dispatch expects a window pointer and there's no data carrying via `void *` which means we can't execute Rust code in C++ land. Also Fl::handle_ is supposed to be called from event_dispatch, making it unergonomic to require constructing a valid widget, so it just accepts the pointer from event_dispatch:
```rust
fn main() {
    use fltk::{prelude::*, *};
    const CHANGE_FRAME: i32 = 100;
    let app = app::App::default();
    let mut wind = window::Window::default().with_size(400, 300).with_label("Hello");
    let mut but = button::Button::default().with_size(80, 40);
    let mut frame = frame::Frame::default().with_size(400, 300);
    wind.end();
    wind.show();
    but.set_callback(move |_| {
        let _ = app::handle_main(CHANGE_FRAME).unwrap();
    });

    frame.handle(move |f, ev| {
        if ev == CHANGE_FRAME.into() {
            f.set_label("Hello world");
            true
        } else {
            false
        }
    });
    unsafe {
        app::event_dispatch(|ev, winptr| {
            if ev == CHANGE_FRAME.into() {
                false // ignore CHANGE_FRAME event
            } else {
                app::handle_raw(ev, winptr)
            }
        });
    }
    app.run().unwrap();
}
```
