### ISSUE TITLE
Help building on Windows

### ISSUE THREAD

**Issue by chn-cutelotus** [fltk-rs/fltk-rs#723]
Dear sir,
    I failed to build my project due to the following error:
------------------------------------
PS D:\coding\Rust\fltk-rs> cargo build
    Blocking waiting for file lock on build directory
   Compiling fltk-sys v1.0.17
   Compiling fltk v1.0.18
error: could not find native static library `cfltk`, perhaps an -L flag is missing?

error: aborting due to previous error

error: could not compile `fltk-sys`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
--------------------------
I'm using Windows 10 OS. Rust version is:
nightly-x86_64-pc-windows-msvc (default)
rustc 1.53.0-nightly (727d10156 2021-04-27)

Please help. Thanks in advance.

**Comment by MoAlyousef** [comment]
Can you try in your Cargo.toml:
```toml
[dependencies]
fltk = { version = "1", features = ["fltk-bundled"] }
```
