### ISSUE TITLE
Additional functions for GroupExt

### ISSUE THREAD

**Issue by wyhinton** [fltk-rs/fltk-rs#739]
Hello, 
Politely requesting bindings for these [```Fl_Group``` functions:](https://www.fltk.org/doc-1.3/classFl__Group.html#ad6b50dddf8f0914dc6a7b89ab3663930)
- ```Fl_Group::init_sizes()```
- ```Fl_Group::sizes()```

**Comment by MoAlyousef** [comment]
Hi
I've added init_sizes(). Sizes is deprecated for bounds, but it's protected, so I've added a Rust implementation which returns the bounds Vec of tuples (left, upper, right, bottom).

**Comment by wyhinton** [comment]
Thanks, sounds good. 

Sorry, but a couple more:

- ```Fl-Group::add_resizable()```
- ```FL-Group::resizable(Fl_Widget*o)``` <-- is this the same as the current ```fn resizable<W: WidgetExt>(&self, widget: &W)```?

**Comment by MoAlyousef** [comment]
Yeah resizable is the same, I ‘ll update the docs.
