### ISSUE TITLE
Missing MenuButton POPUP3 enum item

### ISSUE THREAD

**Issue by jcbritobr** [fltk-rs/fltk-rs#753]
Is missing some constructs for popup menus according fltk c++ api. In Fl_Menu_Button there is a POPUP3 item for use with menu.set_type(..).

Ex.
```c++
G_menu->type(Fl_Menu_Button::POPUP3); 
```

Something in Rust that behaves similar, but a lot strange:
```rust
menu.set_type(ButtonType::Radio);
```

**Comment by MoAlyousef** [comment]
I've added MenuButtonType, should be in the next version.

**Comment by jcbritobr** [comment]
I'm sorry if im geting a lot of features from ercos page. ^^ I could build a list based in examples.

**Comment by MoAlyousef** [comment]
Yeah the plan was to add most widgets and implement most common methods and traits/interfaces, then add things on a per need basis. Some things can't be mapped 1 to 1 with the C++ api, like overriding protected methods, or anything requiring subclassing. Maybe creating a list based on the examples would be easier to go through and determine the feasibility of wrapping.

**Comment by jcbritobr** [comment]
I create the module menu_button_type for a while until got the next release. I will try to implement the examples and missing features as modules, so you guys may got in this repository:
https://github.com/jcbritobr/erco-fltk-examples

```rust
use fltk::prelude::WidgetType;

#[repr(i32)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub enum MenuButtonType {
    Popup1 = 1,
    Popup2,
    Popup12,
    Popup3,
    Popup13,
    Popup23,
    Popup123,
}

impl WidgetType for MenuButtonType {
    fn to_i32(self) -> i32 {
        self as i32
    }

    fn from_i32(val: i32) -> Self {
        match val {
            1 => MenuButtonType::Popup1,
            2 => MenuButtonType::Popup2,
            3 => MenuButtonType::Popup12,
            4 => MenuButtonType::Popup3,
            5 => MenuButtonType::Popup13,
            6 => MenuButtonType::Popup23,
            7 => MenuButtonType::Popup123,
            _ => MenuButtonType::Popup3,
        }
    }
}
```
