### ISSUE TITLE
[BUG] [super low prio] Mouse wheel event coordinates for unselected windows are off (only macOs?)

### ISSUE THREAD

**Issue by eadf** [fltk-rs/fltk-rs#760]
## Describe the bug
Related to #600, mouse wheel events generates erronous coordinates for unselected windows.

## To Reproduce
Run this:
```rust
use fltk::{app,enums::{Color, Event},frame::Frame,prelude::{GroupExt, WidgetBase, WidgetExt},
    window::Window,enums::FrameType,};

fn main() {
    let app = app::App::default();
    let mut win = Window::default().with_size(210, 60);
    let mut frame = Frame::default().with_size(200, 50).center_of(&win);
    frame.set_frame(FrameType::EngravedBox);
    win.end();
    win.show();
    win.handle({
        let mut frame = frame.clone();
        move |_, ev| match ev {
            Event::MouseWheel => {
                frame.set_label(format!("{},{}", app::event_x(), app::event_y()).as_str());
                true
            }
            _ => false,
        }
    });
    app.run().unwrap();
}
```
Click another window, but hover over the fltk window and scroll the mouse wheel.

## Expected behavior
The coordinates to be correct relative to the (unselected) fltk window.

## Screenshots
![mouse_wheel_event](https://user-images.githubusercontent.com/655495/124353049-4e812b00-dc04-11eb-8ef6-2d0c063d8c99.png)

## Desktop info
 Bug appears on macOS 11.4 M1
 It works as expected on Linux (Manjaro 21.0.7)

## Additional info
fltk 1.0.21

**Comment by MoAlyousef** [comment]
Hi
Can you try with the current master?
Version 1.0.21 doesn't include @Albrecht-S 's fix, which should be available in the next release of fltk-rs.

**Comment by eadf** [comment]
Oh, sorry.. I thought 1.0.21 included that fix.
But never the less, the problem persists with:
```
[dependencies]
fltk = { git = 'https://github.com/fltk-rs/fltk-rs.git' }
```

**Comment by Albrecht-S** [comment]
Confirmed on macOS with native FLTK (C++). Linux and Windows (cross-compiled on Linux, using `wine`) works fine as well (not tested on bare Windows yet).

What I can see so far is that Windows (see above) and Linux send FL_MOVE events to the inactive window whereas macOS doesn't - hmm, well, the only thing I can say right now precisely is that the application doesn't "see" FL_MOVE events. However, it gets FL_MOUSEWHEEL events.

I'm looking into it, reopening fltk/fltk#210 ...

**Comment by Albrecht-S** [comment]
I'm confident that this issue is now fixed upstream (fltk/C++). Can you please test again?

See commit https://github.com/fltk/fltk/commit/aa955812f988a4c0ffa3a43e9a5ba7a20a0e1f92

**Comment by MoAlyousef** [comment]
Thanks @Albrecht-S 
I've just pulled the latest changes, but I can only test on macos hopefully tomorrow.

**Comment by MoAlyousef** [comment]
I just tested on a macbook air with a mouse and also via swiping on the trackpad, and the problem appears to be resolved. Thank you
