### ISSUE TITLE
[BUG] SvgFileSurface example from docs draws nothing

### ISSUE THREAD

**Issue by DBLouis** [fltk-rs/fltk-rs#763]
## Describe the bug
As the title says, minimal example here: DBLouis@cdd4762

## To Reproduce
Use my fork and apply this patch first to `cfltk` because there is a double free bug.

```diff
diff --git a/src/cfl_surface.cpp b/src/cfl_surface.cpp
index ed9a275..9c2b780 100644
--- a/src/cfl_surface.cpp
+++ b/src/cfl_surface.cpp
@@ -87,9 +87,7 @@ Fl_SVG_File_Surface *Fl_SVG_File_Surface_new(int width, int height, const char *
 }

 void Fl_SVG_File_Surface_delete(Fl_SVG_File_Surface *self) {
-    FILE *f = self->file();
     delete self;
-    fclose(f);
 }

 void Fl_SVG_File_Surface_origin(Fl_SVG_File_Surface *self, int x, int y) {
@@ -108,4 +106,4 @@ void Fl_SVG_File_Surface_draw(Fl_SVG_File_Surface *self, void *widget, int delta
 void Fl_SVG_File_Surface_draw_decorated_window(Fl_SVG_File_Surface *self, void *widget, int delta_x,
                                                int delta_y) {
     LOCK(self->draw_decorated_window((Fl_Window *)widget, delta_x, delta_y));
-}
\ No newline at end of file
+}
```

## Expected behavior
It should draw the SVG image onto the button

## Screenshots
![Screenshot_20210704_185545](https://user-images.githubusercontent.com/6025361/124391541-c1200280-dcf9-11eb-96fa-7f5fe12dfc7e.png)

## Desktop info
 - OS: Void Linux x64

**Comment by MoAlyousef** [comment]
Hi
Nice catch and thanks for the fix. I'll publish a new version tonight.

**Comment by DBLouis** [comment]
Just to be clear, this ticket is not only about the cfltk patch. Please try the example on my fork.

**Comment by MoAlyousef** [comment]
svg.draw() doesn’t draw on the widget, it draws the widget on the svg. Is that the issue with the example?

**Comment by DBLouis** [comment]
Interesting... why would anyone wants to do this?

With SvgImage it works but how do I set the color of the drawing?

**Comment by MoAlyousef** [comment]
Not sure really.

You can change the color of the widget you're drawing on using WidgetExt::set_color() (you might have to change the FrameType if the widget for example has no frame). If you need to change stroke colors of the svg itself, you'd have to modify the text of the svg itself (FLTK doesn't provide abstractions for that), then call SvgImage::from_data(string), or you can use a drawing library like plotters with an Svg backend.
