### ISSUE TITLE
Styling Scrollbar

### ISSUE THREAD

**Issue by rickkock** [fltk-rs/fltk-rs#766]
Hi,

Is it possible the when you get the scrollbar using the scrollbar() or hscrollbar() to add the set_slider_frame and slider_frame function as in valuator::Scrollbar?

Also is it possible to add the scollbar() and hscrollbar() function to an table, so it can be styled like the group layer?
 
Thanks.

**Comment by MoAlyousef** [comment]
Hi
It's possible but it has to go thru unsafe unfortunately. It's Rust's object safety rules since it's an erased type and might have a different provenance than fltk-rs:
```rust
    let mut scroll = table.scrollbar();
    scroll.set_selection_color(enums::Color::White);
    let mut scroll = unsafe { valuator::Scrollbar::from_widget_ptr(scroll.as_widget_ptr()) };
    scroll.set_slider_frame(enums::FrameType::FlatBox);
```

I've also added scrollbar getters to fltk-rs version 1.0.23. Which I'll publish in a few days.

**Comment by rickkock** [comment]
Allright, I will use it like this.

Thanks!
