### ISSUE TITLE
Is it possible to populate an input choice widget after compiling?

### ISSUE THREAD

**Issue by ryanhartmann1** [fltk-rs/fltk-rs#785]
I am relatively new to using this crate along with rust in general, but I am working on a program that will read a word from an input text widget which will point to a column in an SQL Server table. Then populate an input choice widget so the user can pick which row they want to select and pull information from there. Along with doing this, I want to add a scroll function to this input choice widget but I do not know if it possible or not. 
Currently I am using two separate UIs to solve this problem. This may be an issue with using an ODBC command due to it only being allowed to be run in a function that returns "Result<()>", which is causing me to create the input choice widget in the ODBC functions since the add command must be inside of them to receive that information. Does anybody have any ideas on how I can condense my code into one UI?

**Comment by eadf** [comment]
>This may be an issue with using an ODBC command due to it only being allowed to be run in a function that returns "Result<()>"

You can handle the `Result` 'manually' in a method that does not return `Result`, i.e you can't use `?`.
But Instead you can use `match` or `if let Ok(some function())`

**Comment by ryanhartmann1** [comment]
Yes that would work, but the value needs to be entered after the code has been run. The input choice is filled with the value that has been entered which is done after the code has been run then. Is there a way to work around this?

**Comment by MoAlyousef** [comment]
You can use InputChoice::add(choice) at runtime.

**Comment by ryanhartmann1** [comment]
My code is not adding any values to the input choice, but it is also giving me no errors. I am unable to share it in the current state that it is in due to it being against company policy.

**Comment by ryanhartmann1** [comment]
[main.txt](https://github.com/fltk-rs/fltk-rs/files/6832881/main.txt)

Here is an example of what I am trying to do.

**Comment by eadf** [comment]
Have you tried to follow the execution in a debugger/or printout? Are you sure that you are reaching the drop.add statement?
I'm not familiar with ODBC over rust or how fault tolerant it is, but "Truested_Connection=True" does not look right.

**Comment by ryanhartmann1** [comment]
Yes, I had a small detail that the compiler was not finding. It is not giving the error of: error[E0434]: can't capture dynamic environment in a fn item
Relating to drop.add statement

**Comment by eadf** [comment]
you are creating two `drop` variables, they are not the same instance

**Comment by ryanhartmann1** [comment]
That is what I deleted out of my program for it to return my error, I should have updated the file I shared.

**Comment by eadf** [comment]
needs some polish, but it adds to the dropdown:

```rust
use fltk::{window::*, frame::*, app::*, button::*, input::*,misc::*, prelude::*, text::*, enums::*};
use std::io::BufWriter;

fn main() {
    let app = App::default();
    let mut wind = Window::new(100, 100, 700, 500, "Hello, FLTK!");
    let mut frame = Frame::new(0, 0, 400, 200, "Boring label");
    let fromUser = Input::new(100, 210, 80, 40, "Row Select: ");
    let  mut but1 = Button::new(200, 210, 80, 40, "Populate InputChoice");
    let mut drop = InputChoice::new(400, 210, 80, 40, "List");

    wind.end();
    wind.show();

    but1.set_callback({
        let mut drop = drop.clone();
        move |_| cover(&mut drop,fromUser.value())
    });

    app.run().unwrap();

    fn cover (drop:&mut InputChoice, s: String){
        addTo(drop, s);
    }

    fn addTo (drop:&mut InputChoice, turn: String) -> Result<(),String> {
        let mut _buffer = String::new();
        _buffer = "Driver={SQL Server}; Server=ServerName; Database=DatabaseName; Truested_Connection=True".parse().unwrap();

        let sql_text = "SELECT ".to_owned() +&turn +" FROM Test ";
        //let mut drop = InputChoice::new(400, 210, 80, 40, "List");

        match stmt_exec_direct(&sql_text)? {
            Database::Data(mut cols) => {
                for i in cols.iter() {
                    println!("adding {}", i);
                    drop.add(i.as_str());
                }
                println!("");
            }
            Database::NoData(_) => println!("Query executed, no data returned"),
        }
        Ok(())
    }
}

enum Database{
    Data(Box<[String]>),
    NoData(String),
}

fn stmt_exec_direct(text: &str) -> Result<Database, String>{
    // 4 is a true random number
    Ok(Database::Data(Box::from(["4".to_string()])))
}
```

**Comment by ryanhartmann1** [comment]
I tinkered with it a little bit to use the odbc crate within the code that you gave which was a huge help! One more question, is there a way to add a scroll bar to the input choice widget?

**Comment by MoAlyousef** [comment]
> I tinkered with it a little bit to use the odbc crate within the code that you gave which was a huge help! One more question, is there a way to add a scroll bar to the input choice widget?

No I don’t think so. The choices can be scrolled through with a mouse wheel, but you can’t add a scrollbar to it. 
If you really need such functionality, you can create a custom widget which pops up a window with a scroll widget, a pack and add flat buttons for each choice. Something like the custom_popup example.
