### ISSUE TITLE
fl_filename_expand()

### ISSUE THREAD

**Issue by 1sra3l** [fltk-rs/fltk-rs#796]
Hi, I really would like to use this function, but as the Rust crate is ordered much differently in areas from the C++ API, I am unable to find it.  I am playing with some of your examples and modifying them to see how to "do it in Rust".
So far I really like your API, some changes `Frame/Box` are a bit hard to find, so I am wondering, does this function exist?
Thanks for your work on this!

**Comment by MoAlyousef** [comment]
Thank you.
It didn't exist, I've added it in master under `fltk::utils::filename_expand(path: &str) -> String`. Normally functionality outside of gui, should be handled by external crates. But I see the shellexpand crate is no longer maintained unfortunately.

**Comment by 1sra3l** [comment]
This is great will is be in 1.1.2 crate?  That was so fast!  I am playing with your VLC player, experimenting with making it more functional.

Two non-related-to-the-bug FLTK-rs questions
 * I have a friend who is working to make FLTK have an SDL backend, if this is not officially accepted into the FLTK mainline code, would it be hard to reuse your fltk-rs binding generation on a different git branch of FLTK code? (if you do some sort of automatic bindings)
 * If I have previous made C++ header files for Widgets, is there a way to use those in your implementation?

**Comment by eadf** [comment]
`std::fs::canonicalize()`?

**Comment by 1sra3l** [comment]
@eadf 
:smile:  oh yeah, I totally used that in another project... not sure why I was trying to use the FLTK thing.... hehehe

**Comment by MoAlyousef** [comment]
> `std::fs::canonicalize()`?

Not in front of my machine, does std::fs::canonicalize expand tildes?
On windows it also returns UNC paths, which is not what most people would expect: 
https://github.com/rust-lang/rust/issues/42869

**Comment by MoAlyousef** [comment]
> This is great will is be in 1.1.2 crate? That was so fast! I am playing with your VLC player, experimenting with making it more functional.
> 
> Two non-related-to-the-bug FLTK-rs questions
> 
> * I have a friend who is working to make FLTK have an SDL backend, if this is not officially accepted into the FLTK mainline code, would it be hard to reuse your fltk-rs binding generation on a different git branch of FLTK code? (if you do some sort of automatic bindings)
> * If I have previous made C++ header files for Widgets, is there a way to use those in your implementation?

1- It should. cfltk uses FLTK as a git submodule which can be changed to point to a different FLTK implementation. It does wrap the 1.4 api so some methods need to be available like Fl_Window::decorated_w etc. 
2- You would need to link it to cfltk, and wrap your widget classes with WIDGET_DECLARE and the other necessary macros which emulate inheritace, unless you want to implement them manually. Then any specific methods would need to be wrapped in a C api.

**Comment by eadf** [comment]
> Not in front of my machine, does std::fs::canonicalize expand tildes?

Nope, neither does dunce :/

**Comment by 1sra3l** [comment]
Oh wait canonicalize does not seem to work `Err(Os { code: 2, kind: NotFound, message: "No such file or directory" })` on the standard XDG dir `~/Videos` the fltk mechanisms did it, in a nice cross-platform way, so thanks @MoAlyousef  for adding that!
I used it to fix relative directories in my program, not the tilde :(

@MoAlyousef:
1. thanks I will look into it when my friend is finished
2. I think re-implementation is probably better, thank you.

**Comment by 1sra3l** [comment]
I will close this now that you fixed it!!
