### ISSUE TITLE
Bindings for box_border_radius_max() and Fl::box_shadow_width() + Fl::set_color()

### ISSUE THREAD

**Issue by wyhinton** [fltk-rs/fltk-rs#800]
Could bindings for ```Fl::box_border_radius_max (int R)```, ```Fl::box_shadow_width()```, and ```Fl::set_color()``` be added? According to [this thread from fltk.general,](https://groups.google.com/g/fltkgeneral/c/3A5VC_854ok/m/sDpJsmuLBAAJ) we can use ```Fl::set_color()``` to create themes. 

Thanks in advance!

**Comment by MoAlyousef** [comment]
The app module now has:
- set_color()
- frame_border_radius_max()
- set_frame_border_radius_max()
- frame_shadow_width()
- set_frame_shadow_width()
