### ISSUE TITLE
fltk::image::*::draw()

### ISSUE THREAD

**Issue by 1sra3l** [fltk-rs/fltk-rs#801]
The bindings are missing the draw function which allows the `cx, cy` corner coordinates for using a spritesheet to pick images out of.  I honestly tried very hard to look through the docs to see if I was missing it somewhere.  I did not find it in any of the image structs.
I would like to be able to use this, because I want to make a game, and being able to do a sprite sheet is a big step in that direction.
I considered using the `image` crate, but FLTK already has this functionality built in the C++ version.
the [C++ version is](https://www.fltk.org/doc-1.3/classFl__Image.html#a1837b71dc0ac4243397018822c5e5f3a):
`draw(screen_x, screen_y, image_frame_width, image_frame_height, image_frame_x, image_frame_y)`
Your bindings only have
`draw(screen_x, screen_y, image_width, image_height)`

Thanks again for all your efforts, FLTK has been a favorite of mine for years, so having Rust bindings (as well as your great fl2rust) makes many things easier and cleaner than the C++ code!  I really like your `widget.emit(signal, MySignal::Yeet)` way of handling callbacks, it is much nicer than the C++ callback method (2 functions needed to do one thing).

Keep up the great work!

**Comment by 1sra3l** [comment]
looking through the [FLTK code of Fl_Image.cxx] (https://github.com/fltk/fltk/blob/15f1b6b5c4783695769d3342b85b26b3e7bd29bd/src/Fl_Image.cxx#L643)  for the `draw(x,y,w,h,cx,cy)` function they use `fl_graphics_driver->draw_rgb(this, XP, YP, WP, HP, cx, cy);`  However in [your draw_rgb](https://docs.rs/fltk/1.1.2/src/fltk/draw.rs.html#770-783) you pick all the parameters for the end user, and do not call the same draw.  I keep trying to find ways to do it without needing a fix, but I do not think it will be possible.
I am still learning how your repo is oriented, do you pull from [cfltk](https://github.com/MoAlyousef/cfltk/blob/3f6ab214403be866493f905d0eb204001aece288/include/cfl_image.h#L10)?

**Comment by MoAlyousef** [comment]
I have added ImageExt::draw_ext which takes the offset.
fltk-rs doesn't expose graphics (or any) drivers for the time being.

**Comment by 1sra3l** [comment]
I was looking through your commit, so I could understand how you are doing it all behind the scenes :smile:   You are quite talented!  You are writing C bindings for FLTK and then using Rust to generate them, and as a relative beginner to this I really appreciate how you do a lot of nice work!  Thanks, it looks like it will work great when you push it to crates!  I will try to make a gif of the result for you.

**Comment by MoAlyousef** [comment]
Thank you. Yes the plan is to auto generate most of the bindings. If the Rust project were to bundle bindgen, that would shave off around 50k lines of code from the fltk-sys crate.

**Comment by 1sra3l** [comment]
Sorry for taking so long to get to this.  I got a working sketch program, and am in the midst of refactoring things into a real program. You surely understand when you get on that long thread, you have to stick with it until you get it "mostly" working enough to compile and do some of the former things, before you can concentrate on new functionality, like this new `draw()`

I cannot seem to use this to override a widget's `draw()`.  I may have just missed something minor, or should I be going about it differently?
Thanks for your hard work, and again sorry for being so slow to respond.
P.S. I **did** see this bug is **closed**, and I **did** see the **new function** in the updated docs/src, as well, just to be clear.
P.P.S.  I think FLTK and Rust are built for each other!  You can use FLUID to mockup a UI, and you can use `#[test]` to mockup new structs.  All FLTK functions are really well named.  You've kept names similar, except instances like `Frame`, since `Box` is taken.  I am really impressed with how the two play together.  I like it more than the C++ interface now, though that offers access to **everything**.  As a long time fan of FLTK, I appreciate the way you translated the API to be more rust like!  It is like reading drafts as someone translates a famous literary work into your own language!  You are very talented, I do hope you get paid to program in Rust somewhere, because you do great work!

**Comment by MoAlyousef** [comment]
Thank you :)
Depends on what widget you're trying to override its draw method, if you have a minimal reproducible example.
Most widgets' draw method in fltk-rs can't be completely overriden, except for Widget and Frame. The reason is because of Rust's lack of inheritance, all fltk-rs widgets basically call the parent's draw() method, in addition to the user provided one if any.

**Comment by 1sra3l** [comment]
How about a snippet?
```rs
let mut image = SharedImage::load(image_filename.as_str());
let mut img = image.unwrap().clone();
// Definitely tried lots of variations, this is just some random old code I found, not sure this one even compiled
// It was a comment in new code because of a snippet somewhere when refactoring initially.
ui.character_box.draw(move |cb| {
        let x:i32 = kreat.position.x as i32;
        let y:i32 = kreat.position.y as i32;
        let h:i32 = kreat.frame.h as i32;
        let w:i32 = kreat.frame.w as i32;
        let cx:i32 = kreat.frame.x as i32;
        let cy:i32 = kreat.frame.y as i32;
        Image::draw_ext(&mut img.into(),x,y,w,h,cx,cy)
    }
);
```

**Comment by MoAlyousef** [comment]
I've filled some blanks. So the call should be `img.draw_ext(/* args */);`
```rust
use fltk::{prelude::*, *};

struct Ui {
    character_box: frame::Frame,
}

impl Ui {
    pub fn new(x: i32, y: i32, w: i32, h: i32, title: &'static str) -> Self {
        let mut character_box = frame::Frame::new(x, y, w, h, title);
        character_box.set_frame(enums::FrameType::FlatBox);
        character_box.set_color(enums::Color::White);
        Self {
            character_box
        }
    }
}

fn main(){
    let app = app::App::default();
    let mut win = window::Window::new(200, 200, 500, 300, None);
    let mut ui = Ui::new(10, 10, 200, 200, "");
    let image = image::SharedImage::load("screenshots/calc2.jpg");
    let mut img = image.unwrap().clone();
    img.scale(200, 200, false, true);
    ui.character_box.draw(move |cb| {
        let x:i32 = cb.x();
        let y:i32 = cb.y();
        let h:i32 = cb.h();
        let w:i32 = cb.w();
        let cx:i32 = -50;
        let cy:i32 = -50;
        img.draw_ext(x,y,w,h,cx,cy);
    }
    );
    win.end();
    win.show();
    app.run().unwrap();
}
```
This code run from the fltk-rs repo produces this image:
![image](https://user-images.githubusercontent.com/37966791/127323389-c401eb35-639d-45aa-a05e-5d0f6319a05b.png)

**Comment by 1sra3l** [comment]
Can `cx, cy` be passed in through user data, or some other method?  I will make a little test for this and play with it some over the next few days!

**Comment by MoAlyousef** [comment]
Yes cx and cy can be passed to the closure from outside, or they can be calculated inside the closure if they depend on cb’s coordinates or size.

**Comment by 1sra3l** [comment]
@MoAlyousef Thanks again!  Enough testing produced the results I wanted!  FLTK is so fun, and rust is incredible (still enthralled with `enum`).  Being able to make a little video game will be a lot of fun!  I have some simple placeholder art work, but now that I can change my animation "cell" cx/cx I can make more complicated assets.  Thanks again!  I will eventually post a GIF here for you.  Do you want me to wait until I have something more substantial (i.e. code on github) to show as well?

**Comment by MoAlyousef** [comment]
Yeah sure. A gif would be nice. If eventually you’re comfortable with sharing the repo on the Projects Showcase, that would also be great.

**Comment by 1sra3l** [comment]
Yeah of course!  I just have a ways to go before I am ready to even upload it :D

**Comment by 1sra3l** [comment]
This is by no means complete, but this image showcases a tiled map and a character that is from a spritesheet.  Keep in mind this is placeholder art assets for the characters.  
![flrpg](https://user-images.githubusercontent.com/76438083/127775122-3165d002-20f0-4229-9cb5-d553ce4a4dcd.png)

I've got the tilemap tiles as transparent, where I can configure the background color in my configuration files via
```rs
/// I am using `tini` to read these
/// I've wrapped the function to check `[default]` automatically, and take a struct containing the ini details
let color:String = get_or_default("color", ini_details.clone());
let color = color.parse::<u8>().ok().unwrap_or(255);
widget.set_color(Color::by_index(color));
```
With the ini file having:
```ini
# the color the floor picks is the default color
[default]
color = 65
# all tiles are this size
w = 32
h = 32
# the wall has a specific color
[Wall 0]
color = 155
```
The `heart` item is also colored via `color = 1` in the item config file
I am pretty excited about my progress so far!  I have yet to get it up to the same functionality of my FLUID mockup version, but I am basically making a game engine that is mostly "programmed" through `ini` config files, and asset creation.
Here is the "map":
```ini
## the width of your playing board
w = 512
h = 512
## eight rows down a..h
map_rows = a, a2, b, c, d, e, f, g, b2, c2, d2, e2, f2, g2, i, i2
#tiles
tiles = o, v
tiles_file=assets/walls.ini
v = Wall 0
o = Floor 0
## the default map so you can make placeholders to try out new tile schemes and work on levels as you get to them
## eight columns across each row
a = v, v, v, v, v, v, v, v, v, v, v, v, v, v, v, v
a2 = v, v, v, v, v, v, v, v, v, v, v, v, v, v, v, v
b = v, v, o, o, o, o, o, o, o, o, o, o, o, o, v, v
c = v, v, o, o, o, o, o, o, o, o, o, o, o, o, v, v
d = v, v, o, o, o, o, o, o, o, o, o, o, o, o, v, v
e = v, v, o, o, o, o, o, o, o, o, o, o, o, o, v, v
f = v, v, o, o, o, o, o, o, o, o, o, o, o, o, v, v
g = v, v, o, o, o, o, o, o, o, o, o, o, o, o, v, v
b2 = v, v, o, o, o, o, o, o, o, o, o, o, o, o, v, v
c2 = v, v, o, o, o, o, o, o, o, o, o, o, o, o, v, v
d2 = v, v, o, o, o, o, o, o, o, o, o, o, o, o, v, v
e2 = v, v, o, o, o, o, o, o, o, o, o, o, o, o, v, v
f2 = v, v, o, o, o, o, o, o, o, o, o, o, o, o, v, v
g2 = v, v, o, o, o, o, o, o, o, o, o, o, o, o, v, v
i = v, v, v, v, v, v, v, v, v, v, v, v, v, v, v, v
i2 = v, v, v, v, v, v, v, v, v, v, v, v, v, v, v, v
```
Anyhow, once I really get this thing up and running (lots of mind-bending work to go), I will host it on github and have real art for the characters!  Then I'll hit you up here and let you know.

**Comment by MoAlyousef** [comment]
This looks great :)
Yeah sounds good.
