### ISSUE TITLE
Check if an Input is focused

### ISSUE THREAD

**Issue by mvasi90** [fltk-rs/fltk-rs#812]
Hi,

How to check if an Input has the focus without listening for events?

**Comment by MoAlyousef** [comment]
currently:
```rust
    if let Some(has_focus) = app::focus() {
        if inp.is_same(&has_focus) {
            println!("inp1 Has focus");
        }
    }
```
But I can add a has_focus() method in the next release.

**Comment by mvasi90** [comment]
> But I can add a has_focus() method in the next release.

That would be great.
But if there is already an alternative way to achieve it, adding an `add_focus()` method is not a high priority task. It may be for future releases, not necessarily the next one.

Again, thank you.
Great work!
