### ISSUE TITLE
Align::Wrap has no effect on Frames

### ISSUE THREAD

**Issue by mvasi90** [fltk-rs/fltk-rs#813]
Hi,

Maybe I'm doing it wrong, but I can't wrap the text to the width of the Widget.
Simple example:

```rust

fn update_gui(vpack: &mut Pack) {
    let status = Frame::default().with_size(400,50).with_align(Align::Wrap)
      .with_label("Example text:\nThis text should be wrapped because its size exceeds the Widget width.");
   let mut innerpack = Pack::default().with_size(400, 50);
   innerpack.add(&status);
   vpack.add(&innerpack);
}

```
Align::Wrap is not applicable to a Frame?

**Comment by MoAlyousef** [comment]
I’ll have to check when I’m front of my dev machine. Is it reproduced also when outside of a pack, and with other widgets as well?

**Comment by mvasi90** [comment]
Tested outside of a pack, with other widgets and also with a `TextBuffer`. Same result.

Reproduction:
```rust
use fltk::{
    app,
    enums::Align,
    prelude::*,
    text::{TextBuffer, TextDisplay},
    window::Window,
};

fn main() {
    let app = app::App::default();
    let mut w = Window::default()
        .with_size(400, 200)
        .center_screen();
    let mut txt = TextDisplay::default()
        .with_size(400, 200)
        .with_align(Align::Bottom);
    let mut buff = TextBuffer::default();
    buff.set_text("Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum");
    txt.set_buffer(Some(buff));
    w.end();
    w.show();
    app.run().unwrap();
}
```

**Comment by MoAlyousef** [comment]
I just tried the Align::Wrap on my machine and it works as intended. It doesn't resize the widget but more importantly doesn't allow the text to flow outside its bounds.
```rust
// without Align::Wrap
    let mut frame = Frame::new(160, 210, 80, 40, "A very very long label");
    frame.set_frame(FrameType::BorderBox);
```
![image](https://user-images.githubusercontent.com/37966791/127724673-88beff31-e8ce-472b-8773-7f2e17a39c2f.png)

```rust
// With Align::Wrap
    let mut frame = Frame::new(160, 210, 80, 40, "A very very long label").with_align(Align::Wrap);
    frame.set_frame(FrameType::BorderBox);
```
![image](https://user-images.githubusercontent.com/37966791/127724721-8a0b28ac-a777-405e-b78c-ce66a6704379.png)

To get the widget to resize according to the label length, you'll have to use measure_label:
```rust
    let mut frame = Frame::new(160, 210, 80, 40, "A very very long label");
    let (w, _h) = frame.measure_label();
    frame.set_size(w + 10, frame.h());
    frame.set_frame(FrameType::BorderBox);
```
![image](https://user-images.githubusercontent.com/37966791/127724773-5dc1770a-846c-4489-908e-cb964da302d9.png)

And as you've noticed, DisplayExt widgets like TextDisplay and TextEditor have their own wrap method since with_align and set_align work for labels (it will still work for the label of the DisplayExt widget, not for their text content).

**Comment by mvasi90** [comment]
I was expecting Align::Wrap mode to cut the text into multiple lines.
Okay. Solved. I will use `TextDisplay` with `wrap_mode()` instead of `Frame`.

Thank you.

**Comment by MoAlyousef** [comment]
By the way, you can change the FrameType of the TextDisplay and its color if you need for it to look like a Frame.

**Comment by mvasi90** [comment]
I don't understand why exists the `align()` method in FLTK if it doesn't work.
Text in `TextDisplay` can't be centered. It also doesn't work in `Input`.

I'm working with numbers and the `Input` should display the number at the right (finance).
On the other hand, the state in `Textdisplay` should be centered, otherwise it is unreadable.

I have already created the same application in GTK3 with gtk-rs and it works perfectly.
The problem is that GTK only works fine on Linux/Unix.

Also I tested orbtk. It's a chaos. The text exits the input widget (in wayland).
You finish typing, you lift your hands from the keyboard and the text continues to write itself. In slow motion.

fltk-rs is not perfect either. Cannot align text to center/right.
Although the appearance can be colored and changed schema and theme, it is still as beautiful as windows 95.

**Comment by MoAlyousef** [comment]
Yeah align is only for labels of widgets. If you need a right aligned input, you can try something like:
```rust
use fltk::{enums::*, prelude::*, *};
use std::ops::{Deref, DerefMut};

pub struct RtlInput {
    inp: input::Input,
}

impl RtlInput {
    pub fn new(x: i32, y: i32, w: i32, h: i32, label: &'static str) -> Self {
        let mut inp = input::Input::new(x, y, w, h, label).with_align(Align::Right);
        let mut frame = frame::Frame::new(x, y, w, h, None).with_align(Align::Inside | Align::Right);
        frame.set_frame(FrameType::DownBox);
        frame.set_color(Color::White);
        inp.set_trigger(CallbackTrigger::Changed);
        inp.set_callback(move |i| {
            frame.set_label(&i.value());
        });
        Self {
            inp
        }
    }
}

impl Deref for RtlInput {
    type Target = input::Input;

    fn deref(&self) -> &Self::Target {
        &self.inp
    }
}

impl DerefMut for RtlInput {
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.inp
    }
}

fn main() {
    let app = app::App::default();
    let mut win = window::Window::default().with_size(400, 300);
    let _inp = RtlInput::new(160, 190, 100, 40, ":Value");
    win.end();
    win.show();
    app.run().unwrap();
}
```
Not exactly perfect, but works!

**Comment by mvasi90** [comment]
It works. But the cursor appears in the middle of the `Input` box.
For now, even without being able to align to the right, `fltk-rs` is still better than all the alternatives.

Thank you!
