### ISSUE TITLE
[BUG?] enums::Event as bitfield

### ISSUE THREAD

**Issue by ThiNei2l** [fltk-rs/fltk-rs#820]
Hello,

I think there may be something wrong with the implementation of enums::Event.

I noticed that e.g.
```rust
println!("{:?}", Event::Enter);
println!("{:?}", Event::Leave);
println!("{:?}", Event::Drag);
```
yields
```
Push | Released | Enter
Leave
Push | Leave | Drag
```
where i would expect
```
Enter
Leave
Drag
```

Looking up the implementation
```rust
const Push = 1;
const Released = 2;
const Enter = 3;
const Leave = 4;
const Drag = 5;
```
the output can be explained by the intersection of the bit patterns.

I think it would be more natural to implement Event as a bitflags! containing a u32 and assign powers of two as values.

**Comment by MoAlyousef** [comment]
I would suggest using the fmt::Display for Events:
```rust
println!("{}", Event::Enter);
```
The values themselves come from FLTK, and without bitflags, some other code for app::handle() breaks due to non-equality between i32 and `casting from #[repr(i32)]`  only in release mode https://github.com/fltk-rs/fltk-rs/issues/704.
Unfortunately changing the implementation now to powers of two and performing conversions might break other users.

**Comment by ThiNei2l** [comment]
Well, it's not really about the formatting.

It's more that something like
```rust
  assert!(Event::Enter.contains(Event::Push));
  assert!(Event::Enter.intersects(Event::Push));
  assert!(Event::Enter & Event::Push == Event::Push);
  assert!(Event::Enter | Event::Push == Event::Enter);
  assert!(Event::Push | Event::Released == Event::Enter);
  assert!((Event::Enter | Event::Push) - Event::Push == Event::Released);
```
really seems like it could have unintended side effects.
But I don't have a good overview of how this type is used in fltk.
So if you say that this is no problem, I'll believe you.

But I think the then the above functions (and others like insert or remove) should have warning signs :smile:

**Comment by MoAlyousef** [comment]
😄
I can see how that becomes problematic in certain situations, like the ChromeOS recently publicized bug:
```rust
        if ev == Event::Push | Event::Released {
            println!("triggered"); // would trigger on Event::Enter
        }
// insead of
        if ev == Event::Push || ev == Event::Released {
            println!("triggered");
        }
```
The C++ side would also exhibit similar behavior since it's all a C style enum.

**Comment by ThiNei2l** [comment]
Ok, if Event is nowhere actually used as bit field, I guess it's no problem.
Just seemed like something people should be aware of.
Anyway, as always, thanks for the fast response.
