### ISSUE TITLE
How to add rich format text?

### ISSUE THREAD

**Issue by lotusstudio** [fltk-rs/fltk-rs#821]
Does input::Input or text::TextEditor support rich format text? Such as subscript, different color for each character, etc.

**Comment by MoAlyousef** [comment]
Rich text format, unfortunately no. Giving each character a different color/font/size, this can be done using a style buffer like in the terminal example:
https://github.com/fltk-rs/fltk-rs/blob/35cc1e195f9a2edf65b36ae53b4d360e5aadafc2/fltk/examples/terminal.rs#L91

**Comment by chn-cutelotus** [comment]
It's a bit hard for me.  Is Style buffer available for widget  text::TextEditor? Or only for text::SimpleTerminal?

**Comment by MoAlyousef** [comment]
It’s available for all widgets implementing DisplayExt, i.e TextDisplay, TextEditor and SimpleTerminal. 
I’ll post a simple example here when I’m back in front of my machine.

**Comment by MoAlyousef** [comment]
For example this code:
```rust
use fltk::{prelude::*, *};

fn main() {
    let entries: Vec<text::StyleTableEntry> = vec![
            // since it's the first, it's represented with A
            text::StyleTableEntry {
                color: enums::Color::Blue,
                font: enums::Font::Times,
                size: 17,
            },
            // B
            text::StyleTableEntry {
                color: enums::Color::Red,
                font: enums::Font::Courier,
                size: 16,
            },
        ];
    
    let mut style_buffer = text::TextBuffer::default();
    let mut buffer = text::TextBuffer::default();

    buffer.set_text("This is some random text");
    style_buffer.set_text("BBBB AA ABAB BAAAAB AABB");
    
    let a = app::App::default();
    let mut win = window::Window::default().with_size(400, 300);
    let mut disp = text::TextDisplay::new(5, 5, 390, 290, None);
    win.end();
    win.show();

    disp.set_buffer(buffer);
    disp.set_highlight_data(style_buffer, entries);
    
    a.run().unwrap();
}
```
gives this:
![Screen Shot 2021-08-01 at 14 40 25](https://user-images.githubusercontent.com/37966791/127769533-e8f315e9-232f-4741-b037-c2ffb6150765.jpg)

**Comment by lotusstudio** [comment]
Thanks a lot. It seems that subscripts can be implemented in this way. But how to add superscript?

**Comment by MoAlyousef** [comment]
That would be much harder and would require drawing into the display widget. But it's not provided out of the box by FLTK. I might provide some sort of demo of how this can be done at some point.
