### ISSUE TITLE
Example custom_popup causes 100% CPU usage

### ISSUE THREAD

**Issue by ThiNei2l** [fltk-rs/fltk-rs#822]
Hello,

I noticed that the example custom_popup causes 100% load.

## To Reproduce
Start the example, then right click the box.
As long as the menu is shown the program uses 100% CPU.
When the menu is closed CPU usage returns to normal.

## Screenshots
![Bildschirmfoto_2021-08-01_12-59-14](https://user-images.githubusercontent.com/76494498/127768391-b08092a1-aa52-45c6-8d9b-ed74a7121654.png)

## Desktop info
Arch Linux (5.13.6).

## Additional info
If I insert a `app::sleep(0.01);` into the loop starting on line 80 the CPU usage goes down under 1%.
So maybe the program is woken up too many times / `app::wait` ends too early?

**Comment by MoAlyousef** [comment]
Thanks for the report. I'll have to check when I get in front of my linux machine.

**Comment by ThiNei2l** [comment]
Yes, same as before. 100% as long as the popup is shown.

Sure. I don't have a lot of experience there, but I could try.
Just tell me what you would like to try.

**Comment by MoAlyousef** [comment]
I've created a repo with a minimal reproducible example
```
$ git clone https://github.com/moalyousef/fltk_mre
$ cd fltk_mre
$ cmake -B bin
$ cmake --build bin --parallel
$ ./bin/main
```
It should automatically shallow clone FLTK and should work.

**Comment by ThiNei2l** [comment]
The C++ version runs flawless.
Here the comparison:
This is the Rust version:
![Bildschirmfoto_2021-08-01_14-28-57](https://user-images.githubusercontent.com/76494498/127770912-16da2716-dba2-42cb-9d97-f1e29d3b6750.png)

And here C++:
![Bildschirmfoto_2021-08-01_14-30-12](https://user-images.githubusercontent.com/76494498/127770924-56203d45-3345-4287-b440-9bf184fec8f0.png)

**Comment by MoAlyousef** [comment]
I'll have to investigate further. Thanks for the info.

**Comment by MoAlyousef** [comment]
Sorry for getting back late. Yeah there were spurious awakes in the bindings which I have removed. Can you try building against the master branch:
```toml
[dependencies]
fltk = { git = "https://github.com/fltk-rs/fltk-rs" }
```

**Comment by ThiNei2l** [comment]
That's not late in my book :smile:
Anyway, that fixes the problem.
Many thanks!
