### ISSUE TITLE
[BUG] Leave event is propagated to the parent.

### ISSUE THREAD

**Issue by mvasi90** [fltk-rs/fltk-rs#839]
## Describe the bug
When the cursor leaves the `Pack` where the button is added, the `Leave` event is triggered.
That should not happen, because duplicate events are generated and it gives an unexpected behavior.

## To Reproduce
```rust
use fltk::{app::App, button::Button, enums::Event, frame::Frame, group::Pack, window::Window};
use fltk::prelude::*;

fn main() {
    let app = App::default();

    let mut w = Window::default()
        .with_size(400, 200)
        .with_label("Test events");

    let vpack = Pack::default().with_size(300, 100).center_of_parent();
    let mut btn = Button::new(10, 10, 100, 25, "Test button");
    Frame::new(10,10, 100, 50, "Frame");
    vpack.end();

    w.end();
    w.show();

    btn.handle(|_, e| {
        if e == Event::Leave {
            println!("Leave button");
            true
        } else {
            false
        }
    });

    app.run().unwrap();
}
```

 1. Move the cursor over the button.
 2. Move the cursor down.
     - When the cursor is no longer over the button, but over the `Frame`, appears: "Leave button". 
 3. Move the cursor down (Leaving the `Frame`);
    - When the `Frame` is leaved, appears "Leave button". <-- Wrong.
 
This has nothing to do with the `Frame`, but with the `Pack` where it ends at the same point as the `Frame`.  In other words: When the mouse leaves the parent group that contains the button, it also fires the event.

If you move the cursor up, the warning appears twice at the same time because the button starts at the same point as the parent.

**Comment by MoAlyousef** [comment]
This was reported also here:
https://github.com/fltk-rs/fltk-rs/discussions/759

It’s an FLTK behavior for some events and some widgets, you would compare which widget triggered the event with the added is_same() method.

**Comment by mvasi90** [comment]
Thanks, solved.
