### ISSUE TITLE
Help with build failure on MacOS

### ISSUE THREAD

**Issue by AllenDang** [fltk-rs/fltk-rs#853]
It happends on building fltk-sys v1.1.11

||   cd /Users/allendang/Desktop/Rust_learning/fl2rust-test/target/debug/build/fltk-sys-620deb82bb9c2af3/out/build && /usr/local/Cellar/cmake/3.21.1/bin/cmake -P cmake_install.cmake
||   ninja: build stopped: subcommand failed.
||   --- stderr
||   fatal: not a git repository (or any of the parent directories): .git

**Comment by MoAlyousef** [comment]
Please provide more info on the system, rust and C++ toolchain, and the full output of `cargo build -vv`

**Comment by eadf** [comment]
fltk 1.1.11 builds just fine on my M1, but as a test I uninstalled brew cmake.

It failed with the old `archive member 'cfl_box.cpp.o' with length 17512 is not mach-o or llvm bitcode for architecture arm64` message. So there seems to be some issue with the bundled cmake. 

Maybe you could try to build with [brew](https://brew.sh) cmake installed?

**Comment by MoAlyousef** [comment]
Yes although cmake supports universal/fat binaries on macos, Rust currently [doesn’t](
https://github.com/rust-lang/cargo/issues/8875). Also brew’s cmake supports only thin [binaries](https://github.com/Homebrew/brew/issues/9454). 

The cmake crate passes the architecture by default which would work with brew’s cmake, and fail on the official CMake package, being a univeral binary it expects universal binaries. I think this can be overriden by specifying the target triple. I for example have a mac 11 but it’s x64, so things work with the official cmake package.

**Comment by AllenDang** [comment]
@MoAlyousef After `cargo clean`, it says some directly in `target` folder cannot be removed. Then I delete `target` folder manually, everything works fine now.
