### ISSUE TITLE
A default modern look and a layout mechanism.

### ISSUE THREAD

**Issue by AllenDang** [fltk-rs/fltk-rs#867]
**Is your feature request related to a problem? Please describe.**
Fltk-rs is the most product ready cross-platform GUI solution right now for rust. It provides solid unicode string rendering and complete IME integration which is essential from my point of view.

After learning if for weeks, I think few things may help to promote this project to more people:
1. A good looking default look and feel theme. The default looking is old and ugly. Maybe we could make the BLACK_THEME be the default theme?'
2. A layout mechanism. I've tried Packer, Flex and relative-positioning, none of them are good for a resizable window.

**Describe the solution you'd like**
For the layout mechanism, maybe a Anchor setter like this `with_anchor(Left|Top|Right|Bottom)`. 
It could be used like this:
```rust
// This input will stay on it's initial position, and extend it's width during window resizing.
let mut input = Input::default().with_pos(8, 8).with_size(300, 30).with_anchor(Left | Top | Right);

// Output will fill remain spaces.
let mut output = Output::default().with_pos(30+8*2).with_size(300, 270).with_anchor(Left | Top | Right | Bottom);
```

**Describe alternatives you've considered**
Currently I'm setting the size and pos of widgets inside the RESIZE event of window to implement anchor-like solution.

**Comment by MoAlyousef** [comment]
I’ll try to implement something maybe as part of the fltk-flex crate. If things work well, I’ll eventually add things to the fltk crate.

**Comment by AllenDang** [comment]
@MoAlyousef That will be great! A layout mechanism is the last piece for FLTK to be a great GUI framework.

**Comment by MoAlyousef** [comment]
The fltk core developers are working on a grid widget which should be added hopefully soon. I'll close this issue now. As soon as that happens, it should be added here as well.
