### ISSUE TITLE
[BUG] Strange position of frame inside group.

### ISSUE THREAD

**Issue by AllenDang** [fltk-rs/fltk-rs#876]
## Describe the bug
The x position of first frame in group goes far out of group.
As my understanding, group will reset the x and y coordinates of all it's children to 0.
But it doesn't work as expect.

## To Reproduce
```rust
use fltk::{prelude::*, *};

const PADDING: i32 = 8;

fn create_cell(title: &str, sub_title: &str) {
    let mut group = group::Group::default().with_size(1, 60 + PADDING * 3);
    group.set_frame(enums::FrameType::DownBox);

    frame::Frame::default()
        .with_pos(1, 0) // <- Why this frame's x position is out of group?
        .with_size(300, 30)
        .with_align(enums::Align::Left | enums::Align::Inside)
        .with_label(title);

    frame::Frame::default()
        .with_pos(0, 30 + PADDING)
        .with_size(300, 30)
        .with_align(enums::Align::Left | enums::Align::Inside)
        .with_label(sub_title);

    group.end()
}

fn main() {
    let a = app::App::default().with_scheme(app::Scheme::Gtk);

    let mut win = window::Window::default().with_size(400, 300);

    let mut packer = group::Pack::default()
        .with_type(group::PackType::Vertical)
        .with_pos(PADDING, PADDING)
        .with_size(400 - PADDING * 2, 300 - PADDING * 2);

    packer.set_spacing(PADDING);

    for _ in 0..4 {
        create_cell("Title", "Subtitle");
    }

    packer.end();

    win.end();

    win = win.center_screen();
    win.show();

    a.run().unwrap();
}
```

## Expected behavior
I could set position to frame1 inside group and it behaves normally.

## Screenshots
![截屏2021-09-07 下午3 22 32](https://user-images.githubusercontent.com/18550/132302015-cb1717f0-e29e-471f-b67e-88e0b33ec44c.png)

## Desktop info
 - OS: macOS 11.15

**Comment by MoAlyousef** [comment]
Hi
The pack expands the group (whose width you specify to be 1), the first frame has an x of 1, so it gets expanded out of the group.
And any widgets inside a group doesn't get its layout modified by the pack, which is the group's parent.
FLTK resolves the position of children from bottom to top, so to avoid that, make the frame inside the group.
```rust
let mut group = group::Group::default().with_size(300, 60 + PADDING * 3); // same width as its children
```

**Comment by AllenDang** [comment]
@MoAlyousef This is the weired part. As my understanding (it seems to be wrong)

Packer
  |_ Group  <- Packer control it's width, so I could set packer's width once and affect all groups.
           |_ Frame <- Group controls it's pos and size, and it's pos is relative to Group, so x = 1 means Group.x + Frame.x.
           |_ Frame
  |_ Group

That is my understanding for a `Container`. 
So idealy, set Frame.x = 1 should be result as Frame.x = Group.x + 1, no matter what size the group got.

And why set group.width = 300 could solve the issue? Doesn't it should be override by Packer?

**Comment by MoAlyousef** [comment]
Yup it's the inverse. It's better to assume that a group is independent (has its own inner sizes etc). A group basically should be treated as a widget with multiple elements. Actually many of the widgets in FLTK are actually Fl_Group's which can be instantiated alone or within another container (such as packs etc).

**Comment by AllenDang** [comment]
@MoAlyousef So Group is just a widget with a border, can be used to group widgets *logically*, got it.
Is there any actual meaning `Container` inside fltk? Means a container who will set children's position relatively to it's own, and move it should result to move all it's children as well.

**Comment by MoAlyousef** [comment]
A group will move all it's children as well. The positions though aren't relative to it. You would specify that the positions are relative to their parent if you need to:
```rust
use fltk::{prelude::*, *};

fn main() {
    let a = app::App::default().with_scheme(app::Scheme::Gtk);

    let mut win = window::Window::default().with_size(400, 300);

    let mut group = group::Group::default()
        .with_size(200, 100)
        .center_of_parent();
    let mut btn = button::Button::default()
        .with_size(200, 100)
        .center_of_parent()
        .with_label("Click me");
    group.end();

    win.end();
    win.show();

    btn.set_callback(move |_| { // moving the group will also move the button
        group.set_pos(group.x() - 10, group.y() - 10);
        app::redraw();
    });

    a.run().unwrap();
}
```

The button's center_of parent() does it here automatically. Otherwise, you would specify something like:
```
    let mut group = group::Group::default()
        .with_size(200, 100)
        .center_of_parent();
    let mut btn = button::Button::default()
        .with_pos(group.x() + 10, group.y() + 10)
        .with_size(80, 40)
        .with_label("Click me");
    group.end();
```
