### ISSUE TITLE
`when()`

### ISSUE THREAD

**Issue by 1sra3l** [fltk-rs/fltk-rs#877]
I am looking for the 'when()' function to use in a widget callback, specifically the file chooser, because the default callback is performed on **any** action (even hitting the `..` to go up a directory).  [Here is the upstream](https://www.fltk.org/doc-1.3/classFl__Widget.html#acb46c71f55ccdfeead9e9dcb3fb2c23b).  Honestly if you only change the file choosers default to use something else that would be fine for me.  It is probably easier in the C backend to do than making `when()`, when you don't need to :rofl: 

Anyone could do:
```rs
file_chooser.set_callback(
//whatever I want
);
```
It would wait until the user pressed `Enter`, rather than changing it at all, by clicking.   I just use the `fltk::dialog::file_chooser`  to work around the issue.  If `when()` is in the docs, I searched, and it did not find it nor did the search engine, so it may be called something totally different akin to `Fl_Box = Frame` Since `Box` is obviously taken...

Thanks for continuing on your work, I've been contributing to a game using your fine work!   Over at: igorfs10 /rust_hero.  Thanks for making theming really easy to do, I am sure we will use that feature once the game becomes more of a real thing.  I'll be adding screenshots over there you can link to.  This is a different project than the ones I am doing in personal time.

I like FLTK even more in Rust form I think :grinning:

**Comment by MoAlyousef** [comment]
Hi
Thanks for your kind words. 

so when() has been translated into trigger() and set_trigger() which return and take an enums::CallbackTrigger. However note that Fl_File_Chooser doesn’t derive from Fl_Widget, so it doesn’t have a when() method. And although it exposes some buttons as public members, it doesn’t expose the ok button, so you won’t be able to set the trigger for it out of the box. This can probably be hacked by actually accessing the file chooser’s window then getting it’s children (groups), until reaching the ok button and adding a trigger. 
I’m away from my PC so I can’t test this theory.

**Comment by 1sra3l** [comment]
@MoAlyousef Thanks for the translation!
I may do that, but the code I have works for what I need, and since I can use `trigger()` I can use it in a pretty similar manner to `when()`.  I'll close this since I simply didn't know what it is called.  Could you add a hook to the search to pull that up, perhaps by putting something different than "Sets the default callback trigger for a widget"

Maybe just add:

This replaces `when()`

That is the only downside to the conversion, sometimes I don't know what it is called.  Glad you already coded it, I guess you would have had to with all the cool stuff you've been working on, you probably couldn't have avoided it this long.
