### ISSUE TITLE
Expose clipboard setting method.

### ISSUE THREAD

**Issue by AllenDang** [fltk-rs/fltk-rs#894]
**Is your feature request related to a problem? Please describe.**
I need to set the content (string) of system clipboard.

**Describe the solution you'd like**
I guess fltk may come with a clipboard setting function? If so, can you expose such funciton? I can only find method to get content from clipboard right now.

**Describe alternatives you've considered**
If it cannot be done, I'd have to find crossplatform clipboard solution, and I tried `clipboard` crate, it doesn't work with macOS 11.5.

**Comment by MoAlyousef** [comment]
Yeah the clipboard crate seems abandoned. I'd suggest copypasta. 
FLTK does have a function to write to the clipboard but it's limited to textual content. So you might prefer to use a dedicated Rust crate like copypasta, which we use in fltk-egui as well.

**Comment by AllenDang** [comment]
@MoAlyousef Sure thing. Thanks!
