### ISSUE TITLE
Is this library suitable to create a taskbar?

### ISSUE THREAD

**Issue by Joe23232** [fltk-rs/fltk-rs#897]
Hey guys I wanted to make a taskbar, kinda like [polybar](https://polybar.github.io/).

![image](https://user-images.githubusercontent.com/34926497/133958577-30923253-480c-4a3f-82d2-66a7197e72f7.png)

Is it possible to draw it directly on the screen using your library on Windows, Linux (x.org display server) and on Linux (Wayland display server)?

Furthermore does it use retained graphics or immediate graphics?

**Comment by MoAlyousef** [comment]
https://github.com/fltk-rs/fltk-rs/discussions/606

See prior discussion
