### ISSUE TITLE
[BUG] Animations on Windows 10

### ISSUE THREAD

**Issue by msenol86** [fltk-rs/fltk-rs#908]
## Describe the bug
Animations on Windows 10 does not work properly. Animation only animate when I keep my mouse on FLTK window and keep moving my mouse. 

## Screenshots
[My YouTube video](https://studio.youtube.com/video/2ihbmxvPHgg/edit)

## Desktop info
 - OS: Windows 10 x64
 - Version 20H2

## Additional info
https://github.com/msenol86/rust-fltk-animation

**Comment by MoAlyousef** [comment]
Can you try adding a `app::awake();` after the `app::sleep(0.03);`?

**Comment by msenol86** [comment]
It worked. Thx a lot.
