### ISSUE TITLE
[Need Help] flashing screen and weird behaviors while drawing image in spreadsheet/table cells 

### ISSUE THREAD

**Issue by wellitecho** [fltk-rs/fltk-rs#929]
## Describe the bug
First of all, thank you for this amazing crate, which is easy to use and produces small binaries with minimal memory footprint.
I try to create a spreadsheet-like project([reference taken: spreadsheet.rs in fltk/examples](https://github.com/fltk-rs/fltk-rs/blob/master/fltk/examples/spreadsheet.rs)) which simply displays data given to it. Some cells renders text, and some cells renders image.
The problem is,
   1. when I scroll up/down, the image will overlay the top column,  and covers the column header.
   2. when I scroll up/down, sometimes the images in cells will stuck together.
   3. when I scroll up/down, the image cell area will flash/blink.
## To Reproduce
code used to draw_data:
```rust
fn draw_data(
    info_table: &mut Table,
    row: i32,
    txt: &str,
    x: i32,
    y: i32,
    w: i32,
    h: i32,
    selected: bool,
) {
    draw::push_clip(x, y, w, h);
    if selected {
        draw::set_draw_color(enums::Color::from_u32(0x00D3_D3D3));
    } else {
        draw::set_draw_color(enums::Color::Light2);
    }
    draw::draw_rectf(x, y, w, h);
    draw::set_draw_color(enums::Color::Gray0);

    // draw text
    if !txt.ends_with(".png") {
        draw::draw_text2(txt, x, y, w, h, enums::Align::Center);
        draw::draw_rect(x, y, w, h);
    }

    // draw images
    else if txt.ends_with(".png") && txt.contains("resized") {  
        info_table.set_row_height(row, 170);

        let original = txt.to_string();
        let t = thread::spawn(move || {
            let mut img = PngImage::load(&original).unwrap();
            img.draw(x, y, w, h);
        });
    }

    draw::pop_clip();
    if selected {
        let txt_owned = txt.to_string();
        thread::spawn(move || {
            set_clipboard(formats::Unicode, txt_owned).expect("Failed to set clipboard");
        });
    }
}
```

## Expected behavior
Image cell should displays OK, no flashing screen;
Image should not go out of its cell.

## Screenshots
| ![Image goes out of its cell, and covering the column header.](https://i.imgur.com/jtnVWLp.png) |
|:--:| 
| *Image goes out of its cell, and covering the column header* |
| ![Image stuck together](https://i.imgur.com/NmLnWRd.png) |
| *Image stuck together* |

## Desktop info
 - OS: Windows 11
 - Version 21H2

**Comment by MoAlyousef** [comment]
Hi
This is a very heavy operation, at each change in the table (like scrolling), the image is reloaded from disc, hence the flickering. Also instantiating widgets/images in the draw callback is not recommended, see the discussion here:
https://groups.google.com/g/fltkgeneral/c/TB-vLS6ZghI
