### ISSUE TITLE
Windows build problem

### ISSUE THREAD

**Issue by jhill1440** [fltk-rs/fltk-rs#939]
I have installed rust on linux and MacOS and got my project to build.  I installed rust on a fresh Windows 10 machine and cannot get my fltk project to build.  I have installed the VC buildtools C++ module. I can build the hello world program and that works fine.  I get getting errors about linking with link.exe failing code 1120.  Any idea as to what could be the problem.

**Comment by MoAlyousef** [comment]
What’s the output of cargo build -vv?

There are instructions for windows here:
https://github.com/fltk-rs/fltk-rs/wiki/Setup#windows-msvc-toolchain

The link issue sounds like you might be using a gnu terminal which has link.exe which creates path links, and the toolchain isn’t using the VC linker "link.exe".
