### ISSUE TITLE
[BUG] Paint example draws at wrong coordinate

### ISSUE THREAD

**Issue by Diggsey** [fltk-rs/fltk-rs#953]
## Describe the bug

Likely related to #784.

When the window is on an external monitor, the mouse position does not match up with the drawing position. It lines up at (0, 0) and then gets more offset as you move away.

**Comment by Diggsey** [comment]
That mostly fixes it for my external monitor (although there's still a small fixed offset that looks like it corresponds to the grey margin) but now it's broken on my main monitor.

**Comment by MoAlyousef** [comment]
So it turns out it was an Offscreen rescaling issue. The latest example (and version 1.2.13) should have that fixed.
