### ISSUE TITLE
Issue updating ui from app.wait()

### ISSUE THREAD

**Issue by diminishedprime** [fltk-rs/fltk-rs#962]
## Describe the bug
I'm trying to show/hide a window based on some changes that happen externally. From looking through examples/etc, I think the way to do this is through an `app::channel` and `app.wait()`. However, when I call `my_window.hide()`, nothing happens. 

## To Reproduce
Call `window.hide()` from inside `app.wait()`

## Expected behavior
The UI can be updated from inside `app.wait()`

## Desktop info
 - OS: arch

## Additional info
I've been trying to make this work with the following code:

```
use std::thread;

use fltk::prelude::*;
use fltk::{app, window};

use crate::ApplicationError;

pub fn start() -> Result<(), ApplicationError> {
    let app = app::App::default();
    let mut my_window = window::Window::new(100, 100, 400, 300, "My Window");
    my_window.end();
    my_window.show();

    let (s, r) = app::channel();

    let handle = thread::spawn(|| {
        // this is some custom code that sends messages via s when some external changes happen.
        crate::i3::listen_to_i3(s).unwrap();
    });

    while app.wait() {
        if let Some(mode) = r.recv() {
            if mode.0.is_empty() {
                my_window.hide();
            } else {
                my_window.show();
            }
        }
    }
    handle.join().unwrap();
    Ok(())
}

```

I may not be using the right pattern for updating the UI when something happens in another thread, are there any resources on how to do that? I looked through the examples, but the only one I see that uses threads spawns the thread in a button callback. My changes happen without window interaction so that doesn't work for my use case.

**Comment by MoAlyousef** [comment]
I think it’s a timing issue. The thread spawn sends a single signal, it’s probably consumed before the window even shows. The while loop blocks until the window is manually hidden, and the join happens only before closing the app. 
I’d suggest trying to debug with button that you click after the window is shown and see if things actually work.

**Comment by diminishedprime** [comment]
I think you're right about this being a timing issue. After playing around with the example more I was able to get this to respond as I expected from a thread. Here is that code:

```
use std::thread::{self, sleep_ms};

use fltk::app;
use fltk::button::Button;
use fltk::prelude::*;
use fltk::window::Window;

use crate::ApplicationError;

pub fn start() -> Result<(), ApplicationError> {
    let app = app::App::default();
    let mut my_window = Window::new(100, 100, 400, 300, "My Window");
    let mut btn = Button::new(160, 210, 80, 40, "click me");
    my_window.end();
    my_window.show();

    let (s, r) = app::channel();

    btn.set_callback(move |_| {
        s.send(1);
    });

    let thread_s = s.clone();

    thread::spawn(move || {
        sleep_ms(5000);
        thread_s.send(1);
    });

    while app.wait() {
        if let Some(signal) = r.recv() {
            if signal == 1 {
                my_window.hide();
            }
        }
    }

    Ok(())
}
```

However, this leads me to a new question. What is the behavior of `window.hide()` supposed to be? As far as I can tell, calling that function causes the program to finish. Is this behavior platform-specific? 

I'm wanting to hide/show a window depending on some data that's pushed via the channel.

**Comment by MoAlyousef** [comment]
FLTK’s default behavior is to end the event loop (app.wait() or app.run()) when there are no windows shown. In your example, hiding the main window effectively terminates the program. 

You can use platform specific code on the window’s raw handle to hide/show the window (win32’s ShowWindow(flag) or x11´s XUnmapWindow/XMapWindow):

https://github.com/fltk-rs/fltk-rs/discussions/875

Or you can save the state of the window, and respawn it by calling show and running a new event loop. 

I’m thinking of adding a method which calls the platform’s hide/show window for such cases.

**Comment by diminishedprime** [comment]
Ah, I see. Thank you for the explanation. I had actually stumbled upon that bug earlier when I was searching, but didn't think about it in this context.
