### ISSUE TITLE
Link error on Windows 32 bit build (platform i686-pc-windows-msvc) with V 1.2.11

### ISSUE THREAD

**Issue by dheijl** [fltk-rs/fltk-rs#965]
Everything OK on 64 bit, but link error on 32 bit:

> note: libfltk-2c6a689d07ff333e.rlib(fltk-2c6a689d07ff333e.fltk.b01b0dec-cgu.13.rcgu.o) : error LNK2019: 
> unresolved external symbol _ShowWindow referenced in function __ZN4fltk6window12DoubleWindow13platform_show17hf982d2c2b17b4b89E
> 
> Hint on symbols that are defined and could potentially match:  _ShowWindow@8
>

**Comment by MoAlyousef** [comment]
Hi
I'm not sure why it's not finding it. It might be the function signature:
https://github.com/fltk-rs/fltk-rs/blob/465d3637a84442d8c37dc1a3a8c3dea1cb0ee700/fltk/src/window.rs#L388

and line 416.

I've changed the signature in the master branch. Can you try using the master branch, and see if things are resolved?

**Comment by dheijl** [comment]
Gives the same error:

    Updating git repository `https://github.com/fltk-rs/fltk-rs`
...snip...
> note: libfltk-52ba21cf28a28be8.rlib(fltk-52ba21cf28a28be8.fltk.beadc54d-cgu.13.rcgu.o) : error LNK2019: unresolved external symbol _ShowWindow referenced in function __ZN4fltk6window12DoubleWindow13platform_show17hffeba2b3575d6995E
>             Hint on symbols that are defined and could potentially match:
>               _ShowWindow@8
>           C:\Users\Danny\source\rust\projects\swyh-rs\target\i686-pc-windows-msvc\debug\deps\swyh_rs.exe : fatal error LNK1120: 1 unresolved externals
>

**Comment by MoAlyousef** [comment]
Apparently Windows 32 bit expects `extern "system"`, I just had a chance to try it on my windows machine, and it works. Can you try again?
If it works, I'll publish a quick fix in version 1.2.12.
Thank you.

**Comment by dheijl** [comment]
It works, thank you!!
