### ISSUE TITLE
Cross compiling windows-gnu from WSL2 can't run the binary (.exe) since FLTK v1.2.11

### ISSUE THREAD

**Issue by Ar37-rs** [fltk-rs/fltk-rs#970]
## Desktop info
 - Windows 10 x64 mingw64
 - FLTK Version: 1.2.12

## Build failures
build ok, but can't run the executable file. 
## Erorr info
The application was unable to start correctly (0xc000007b).
## Additional info
using FLTK <= v1.2.10 working fine,

thank you,

**Comment by MoAlyousef** [comment]
Hmm I think I know the cause of this. I'll try something.

**Comment by MoAlyousef** [comment]
Can you try building against the latest master changes?

**Comment by Ar37-rs** [comment]
master branch working fine now. thank you very much @MoAlyousef, can't say anything other than that.
