### ISSUE TITLE
Low periority: clipboard data

### ISSUE THREAD

**Issue by Ar37-rs** [fltk-rs/fltk-rs#971]
is there a way to pull clipboard data out of fltk::app directly, maybe?. using fltk::app::paste unfortunately requires input widget which cause unresponsive activity sometimes, e.g: on fltk-egui and fltk-egui-frontend (reverted to copypasta on the latest version).

**Comment by MoAlyousef** [comment]
Unfortunately FLTK doesn't appear to expose clipboard content. The performance issue might be because the input widget is created with each event. I'll try creating it only once in the first access to the GlWindow.

**Comment by Ar37-rs** [comment]
great, thank you @MoAlyousef
