### ISSUE TITLE
More Doc comments

### ISSUE THREAD

**Issue by 1sra3l** [fltk-rs/fltk-rs#990]
**Is your feature request related to a problem? Please describe.**
Going to individual parts of the API should be document with short usage examples.  For instance going to fltk::group::Group should give a very basic usage.

**Describe the solution you'd like**
multiline comments including 
```
// actual examples
```

**Describe alternatives you've considered**
remembering everything without needing it.

**Additional context**
Some things from the original API docs are not clearly documented.

I **can document code** decently, I just do not know *where* it should go.  If you give me direction I will make PRs as I go through.

**Comment by MoAlyousef** [comment]
Hi

I plan to provide nore thorough examples in the doc comments. There is also a new nightly feature in rustdoc which basically scrapes the examples directory for usage examples, so people using docs.rs would see more usage examples for structs and methods.

**Comment by 1sra3l** [comment]
Really?  That feature sounds great!  I've been meaning to ask them about allowing \```rs in Doc Comments so I can copy paste README.md and vice versa, retaining syntax highlighting in both...
