### ISSUE TITLE
[BUG] "linking with `link.exe` failed" when importing fltk.

### ISSUE THREAD

**Issue by DraftedDev** [fltk-rs/fltk-rs#999]
When trying to use/import any fltk module, I get the error:
`error: linking with `link.exe` failed: exit code: 1120
  |
  = note: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\link.exe" "/NOLOGO" `

I have msvc and if I try to run a normal rust program everything just works fine.
In my Cargo.toml stands 'fltk = "^1.2" '

The whole stack trace is, by the way, much bigger but I don't think it's worth mention.

OS: Windows 10 x64

**Comment by MoAlyousef** [comment]
Please don't ignore the issue template! And check the build instructions in the [wiki](https://github.com/fltk-rs/fltk-rs/wiki/Setup)
